#ifndef _M25X_PIN_CONFIG_H_
#define _M25X_PIN_CONFIG_H_

#include "SPI_CommonFunc.h"

//------------------------------------------------------------------------------
#define SPI0_MOSI_PIN_INIT                   xSPI0_MOSI_PIN
#define SPI0_MISO_PIN_INIT                   xSPI0_MISO_PIN
#define SPI0_CLK_PIN_INIT                    xSPI0_CLK_PIN
#define SPI0_CSS_PIN_INIT                    xSPI0_CSS_PIN

#if (QSPI_MODE == 1)
    #define SPI0_MOSI1_PIN_INIT                  xSPI0_MOSI1_PIN
    #define SPI0_MISO1_PIN_INIT                  xSPI0_MISO1_PIN
#endif //QSPI_MODE

#if (SPI_MODE == 1)
    #define SPI0_MCLK_PIN_INIT                   xSPI0_MCLK_PIN
#endif //SPI_MODE

#define xSPI0_MFOS_PIN_INIT                  xSPI0_MFOS_PIN

#if (QSPI_MODE == 1)

#if (CHIP_VER == VER_M252_C)
#if(QSPI0_PIN_OUT_GROUP == 0)
#define xSPI0_MOSI_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA0MFP_Msk)) | (SYS_GPA_MFPL_PA0MFP_QSPI0_MOSI0)
#define xSPI0_MISO_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA1MFP_Msk)) | (SYS_GPA_MFPL_PA1MFP_QSPI0_MISO0)
#define xSPI0_CLK_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA2MFP_Msk)) | (SYS_GPA_MFPL_PA2MFP_QSPI0_CLK)
#define xSPI0_CSS_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA3MFP_Msk)) | (SYS_GPA_MFPL_PA3MFP_QSPI0_SS)
#define xSPI0_MOSI1_PIN SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB0MFP_Msk)) | (SYS_GPB_MFPL_PB0MFP_QSPI0_MOSI1)
#define xSPI0_MISO1_PIN SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB1MFP_Msk)) | (SYS_GPB_MFPL_PB1MFP_QSPI0_MISO1)
#define xSPI0_MFOS_PIN  SYS->GPA_MFOS |= BIT0 | BIT1 | BIT2 | BIT3; \
    SYS->GPB_MFOS |= BIT0 | BIT1

#elif (QSPI0_PIN_OUT_GROUP == 1)
#define xSPI0_MOSI_PIN  SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC0MFP_Msk)) | (SYS_GPC_MFPL_PC0MFP_QSPI0_MOSI0)
#define xSPI0_MISO_PIN  SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC1MFP_Msk)) | (SYS_GPC_MFPL_PC1MFP_QSPI0_MISO0)
#define xSPI0_CLK_PIN   SYS->GPF_MFPL = (SYS->GPF_MFPL & (~SYS_GPF_MFPL_PF2MFP_Msk)) | (SYS_GPF_MFPL_PF2MFP_QSPI0_CLK)
#define xSPI0_CSS_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA3MFP_Msk)) | (SYS_GPA_MFPL_PA3MFP_QSPI0_SS)
#define xSPI0_MOSI1_PIN SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB0MFP_Msk)) | (SYS_GPB_MFPL_PB0MFP_QSPI0_MOSI1)
#define xSPI0_MISO1_PIN SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB1MFP_Msk)) | (SYS_GPB_MFPL_PB1MFP_QSPI0_MISO1)
#define xSPI0_MFOS_PIN  SYS->GPC_MFOS |= BIT0 | BIT1; \
    SYS->GPB_MFOS |= BIT0 | BIT1; \
    SYS->GPF_MFOS |= BIT2;        \
    SYS->GPA_MFOS |= BIT3

#endif //QSPI0_PIN_OUT_GROUP

#elif ((CHIP_VER == VER_M252_G) || ( CHIP_VER == VER_M252_D))

#if(QSPI0_PIN_OUT_GROUP == 0)
#define xSPI0_MOSI_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA0MFP_Msk)) | (SYS_GPA_MFPL_PA0MFP_QSPI0_MOSI0)
#define xSPI0_MISO_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA1MFP_Msk)) | (SYS_GPA_MFPL_PA1MFP_QSPI0_MISO0)
#define xSPI0_CLK_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA2MFP_Msk)) | (SYS_GPA_MFPL_PA2MFP_QSPI0_CLK)
#define xSPI0_CSS_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA3MFP_Msk)) | (SYS_GPA_MFPL_PA3MFP_QSPI0_SS)
#define xSPI0_MOSI1_PIN SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA4MFP_Msk)) | (SYS_GPA_MFPL_PA4MFP_QSPI0_MOSI1)
#define xSPI0_MISO1_PIN SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA5MFP_Msk)) | (SYS_GPA_MFPL_PA5MFP_QSPI0_MISO1)
//#define xSPI0_MOSI1_PIN SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC4MFP_Msk)) | (SYS_GPC_MFPL_PC4MFP_QSPI0_MOSI1)
//#define xSPI0_MISO1_PIN SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC5MFP_Msk)) | (SYS_GPC_MFPL_PC5MFP_QSPI0_MISO1)
//#define xSPI0_MOSI1_PIN SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB0MFP_Msk)) | (10 << SYS_GPB_MFPL_PB0MFP_Pos)
//#define xSPI0_MISO1_PIN SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB1MFP_Msk)) | (10 << SYS_GPB_MFPL_PB1MFP_Pos)
#define xSPI0_MFOS_PIN  SYS->GPA_MFOS |= BIT0 | BIT1 /*| BIT2 |BIT3*/; \
    SYS->GPB_MFOS |= BIT0 | BIT1
//        SYS->GPA_MFOS |= BIT4 | BIT5;
//        SYS->GPC_MFOS |= BIT4 | BIT5;

#elif(QSPI0_PIN_OUT_GROUP == 1)
#define xSPI0_MOSI_PIN  SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC0MFP_Msk)) | (SYS_GPC_MFPL_PC0MFP_QSPI0_MOSI0)
#define xSPI0_MISO_PIN  SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC1MFP_Msk)) | (SYS_GPC_MFPL_PC1MFP_QSPI0_MISO0)
#define xSPI0_CLK_PIN   SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC2MFP_Msk)) | (SYS_GPC_MFPL_PC2MFP_QSPI0_CLK)
#define xSPI0_CSS_PIN   SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC3MFP_Msk)) | (SYS_GPC_MFPL_PC3MFP_QSPI0_SS)
#define xSPI0_MOSI1_PIN SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC4MFP_Msk)) | (SYS_GPC_MFPL_PC4MFP_QSPI0_MOSI1)
#define xSPI0_MISO1_PIN SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC5MFP_Msk)) | (SYS_GPC_MFPL_PC5MFP_QSPI0_MISO1)
//#define xSPI0_MOSI1_PIN SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA4MFP_Msk)) | (SYS_GPA_MFPL_PA4MFP_SPI0_MOSI1)
//#define xSPI0_MISO1_PIN SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA5MFP_Msk)) | (SYS_GPA_MFPL_PA5MFP_SPI0_MISO1)

#define xSPI0_MFOS_PIN (SYS->GPC_MFOS |= BIT0 | BIT1 | BIT2 | BIT3 | BIT4 | BIT5)

#elif(QSPI0_PIN_OUT_GROUP == 1)
#if (CHIP_VER == VER_M252_G)
    #define xSPI0_MOSI_PIN  SYS->GPE_MFPL = (SYS->GPE_MFPL & (~SYS_GPE_MFPL_PE0MFP_Msk)) | (SYS_GPE_MFPL_PE0MFP_QSPI0_MOSI0)
    #define xSPI0_MISO_PIN  SYS->GPE_MFPL = (SYS->GPE_MFPL & (~SYS_GPE_MFPL_PE1MFP_Msk)) | (SYS_GPE_MFPL_PE1MFP_QSPI0_MISO0)
#endif //CHIP_VER

#if (CHIP_VER == VER_M252_D)
    #define xSPI0_MOSI_PIN  SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC0MFP_Msk)) | (SYS_GPC_MFPL_PC0MFP_QSPI0_MOSI0)
    #define xSPI0_MISO_PIN  SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC0MFP_Msk)) | (SYS_GPC_MFPL_PC0MFP_QSPI0_MOSI0)
#endif //CHIP_VER

#define xSPI0_CLK_PIN   SYS->GPC_MFPH = (SYS->GPC_MFPH & (~SYS_GPC_MFPH_PC14MFP_Msk)) | (SYS_GPC_MFPH_PC14MFP_QSPI0_CLK)
#define xSPI0_CSS_PIN   SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC3MFP_Msk)) | (SYS_GPC_MFPL_PC3MFP_QSPI0_SS)
#define xSPI0_MOSI1_PIN SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB1MFP_Msk)) | (10 << SYS_GPB_MFPL_PB1MFP_Pos)
#define xSPI0_MISO1_PIN SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB0MFP_Msk)) | (10 << SYS_GPB_MFPL_PB0MFP_Pos)

#if (CHIP_VER == VER_M252_G)
#define xSPI0_MFOS_PIN (SYS->GPE_MFOS |= BIT0 | BIT1; \
                        SYS->GPC_MFOS |= BIT3 | BIT14;\
                        SYS->GPB_MFOS |= BIT0 | BIT1)
//        SYS->GPA_MFOS |= BIT4 | BIT5;
#endif //VER_M252_G

#if (CHIP_VER == VER_M252_D)
#define xSPI0_MFOS_PIN (SYS->GPC_MFOS |= BIT0 | BIT1 /* | BIT4 | BIT5 */; \
                        SYS->GPC_MFOS |= BIT3 | BIT14;                    \
                        SYS->GPB_MFOS |= BIT0 | BIT1)
//        SYS->GPA_MFOS |= BIT4 | BIT5;
#endif //VER_M252_D

#elif(QSPI0_PIN_OUT_GROUP==3)
#define xSPI0_MOSI_PIN  SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC0MFP_Msk)) | (SYS_GPC_MFPL_PC0MFP_SPI0_MOSI0)
#define xSPI0_MISO_PIN  SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC1MFP_Msk)) | (SYS_GPC_MFPL_PC1MFP_SPI0_MISO0)
#define xSPI0_CLK_PIN   SYS->GPF_MFPL = (SYS->GPF_MFPL & (~SYS_GPF_MFPL_PF2MFP_Msk)) | (SYS_GPF_MFPL_PF2MFP_SPI0_CLK)
#define xSPI0_CSS_PIN   SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC3MFP_Msk)) | (SYS_GPC_MFPL_PC3MFP_SPI0_SS)
#define xSPI0_MOSI1_PIN SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB1MFP_Msk)) | (10 << SYS_GPB_MFPL_PB1MFP_Pos)
#define xSPI0_MISO1_PIN SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB0MFP_Msk)) | (10 << SYS_GPB_MFPL_PB0MFP_Pos)

#define xSPI0_MFOS_PIN  SYS->GPC_MFOS |= BIT0 | BIT1 /* | BIT4 | BIT5 */; \
    SYS->GPB_MFOS |= BIT0 | BIT1
#endif //QSPI0_PIN_OUT_GROUP

#endif //CHIP_VER

#endif //QSPI_MODE


//------------------------------------------------------------------------------
// SPI PIN Configure
//------------------------------------------------------------------------------
#if (SPI_MODE == 1)

    #if (CHIP_VER == VER_M252_G)
        #if(SPI0_PIN_OUT_GROUP == 0)
            #define xSPI0_MOSI_PIN  SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD0MFP_Msk)) | (SYS_GPD_MFPL_PD0MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD1MFP_Msk)) | (SYS_GPD_MFPL_PD1MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD2MFP_Msk)) | (SYS_GPD_MFPL_PD2MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD3MFP_Msk)) | (SYS_GPD_MFPL_PD3MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPD_MFPH = (SYS->GPD_MFPH & (~SYS_GPD_MFPH_PD13MFP_Msk)) | (SYS_GPD_MFPH_PD13MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN  SYS->GPD_MFOS |= BIT0 | BIT1

            #elif(SPI0_PIN_OUT_GROUP == 1)
            #define xSPI0_MOSI_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA0MFP_Msk)) | (SYS_GPA_MFPL_PA0MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA1MFP_Msk)) | (SYS_GPA_MFPL_PA1MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA2MFP_Msk)) | (SYS_GPA_MFPL_PA2MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA3MFP_Msk)) | (SYS_GPA_MFPL_PA3MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA4MFP_Msk)) | (SYS_GPA_MFPL_PA4MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN  SYS->GPA_MFOS |= BIT0 | BIT1

            #elif(SPI0_PIN_OUT_GROUP == 2)
            #define xSPI0_MOSI_PIN  SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB12MFP_Msk)) | (SYS_GPB_MFPH_PB12MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB13MFP_Msk)) | (SYS_GPB_MFPH_PB13MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB14MFP_Msk)) | (SYS_GPB_MFPH_PB14MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB15MFP_Msk)) | (SYS_GPB_MFPH_PB15MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPC_MFPH = (SYS->GPC_MFPH & (~SYS_GPC_MFPH_PC14MFP_Msk)) | (SYS_GPC_MFPH_PC14MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN  SYS->GPB_MFOS |= BIT12 | BIT13

            #elif(SPI0_PIN_OUT_GROUP==3)
            #define xSPI0_MOSI_PIN  SYS->GPF_MFPL = (SYS->GPF_MFPL & (~SYS_GPF_MFPL_PF6MFP_Msk)) | (SYS_GPF_MFPL_PF6MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPF_MFPL = (SYS->GPF_MFPL & (~SYS_GPF_MFPL_PF7MFP_Msk)) | (SYS_GPF_MFPL_PF7MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA2MFP_Msk)) | (SYS_GPA_MFPL_PA2MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA3MFP_Msk)) | (SYS_GPA_MFPL_PA3MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB11MFP_Msk)) | (SYS_GPB_MFPH_PB11MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN  SYS->GPF_MFOS |= BIT7 | BIT6
        #endif //SPI0_PIN_OUT_GROUP

    #elif (CHIP_VER == VER_M258)
        #if(SPI0_PIN_OUT_GROUP == 0)
            #define xSPI0_MOSI_PIN  SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB12MFP_Msk)) | (SYS_GPB_MFPH_PB12MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB13MFP_Msk)) | (SYS_GPB_MFPH_PB13MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB14MFP_Msk)) | (SYS_GPB_MFPH_PB14MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB15MFP_Msk)) | (SYS_GPB_MFPH_PB15MFP_SPI0_SS)
            //#define xSPI0_MCLK_PIN  SYS->GPC_MFPH = (SYS->GPC_MFPH & (~SYS_GPC_MFPH_PC14MFP_Msk)) | (SYS_GPC_MFPH_PC14MFP_SPI0_I2SMCLK)
            //#define xSPI0_MCLK_PIN  SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB0MFP_Msk)) | (SYS_GPB_MFPL_PB0MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN SYS->GPB_MFOS |= BIT12 | BIT13

            #elif(SPI0_PIN_OUT_GROUP == 1)
            #define xSPI0_MOSI_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA0MFP_Msk)) | (SYS_GPA_MFPL_PA0MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA1MFP_Msk)) | (SYS_GPA_MFPL_PA1MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA2MFP_Msk)) | (SYS_GPA_MFPL_PA2MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA3MFP_Msk)) | (SYS_GPA_MFPL_PA3MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA4MFP_Msk)) | (SYS_GPA_MFPL_PA4MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN  SYS->GPA_MFOS |= BIT0 | BIT1

            #elif(SPI0_PIN_OUT_GROUP == 2)
            #define xSPI0_MOSI_PIN  SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD0MFP_Msk)) | (SYS_GPD_MFPL_PD0MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD1MFP_Msk)) | (SYS_GPD_MFPL_PD1MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD2MFP_Msk)) | (SYS_GPD_MFPL_PD2MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD3MFP_Msk)) | (SYS_GPD_MFPL_PD3MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPD_MFPH = (SYS->GPD_MFPH & (~SYS_GPD_MFPH_PD13MFP_Msk)) | (SYS_GPD_MFPH_PD13MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN  SYS->GPD_MFOS |= BIT0 | BIT1

            #elif(SPI0_PIN_OUT_GROUP == 3)
            #define xSPI0_MOSI_PIN  SYS->GPF_MFPL = (SYS->GPF_MFPL & (~SYS_GPF_MFPL_PF6MFP_Msk)) | (SYS_GPF_MFPL_PF6MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPF_MFPL = (SYS->GPF_MFPL & (~SYS_GPF_MFPL_PF7MFP_Msk)) | (SYS_GPF_MFPL_PF7MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD2MFP_Msk)) | (SYS_GPD_MFPL_PD2MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD3MFP_Msk)) | (SYS_GPD_MFPL_PD3MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB11MFP_Msk)) | (SYS_GPB_MFPH_PB11MFP_SPI0_I2SMCLK)
            //#define xSPI0_MCLK_PIN  SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB0MFP_Msk)) | (SYS_GPB_MFPL_PB0MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN SYS->GPF_MFOS |= BIT7 | BIT6
        #endif //SPI0_PIN_OUT_GROUP

    #elif (CHIP_VER == VER_M252G)
        #if(SPI0_PIN_OUT_GROUP == 0)
            #define xSPI0_MOSI_PIN  SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB12MFP_Msk)) | (SYS_GPB_MFPH_PB12MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB13MFP_Msk)) | (SYS_GPB_MFPH_PB13MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB14MFP_Msk)) | (SYS_GPB_MFPH_PB14MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB15MFP_Msk)) | (SYS_GPB_MFPH_PB15MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPC_MFPH = (SYS->GPC_MFPH & (~SYS_GPC_MFPH_PC14MFP_Msk)) | (SYS_GPC_MFPH_PC14MFP_SPI0_I2SMCLK)
            //#define xSPI0_MCLK_PIN  SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB0MFP_Msk)) | (SYS_GPB_MFPL_PB0MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN SYS->GPB_MFOS |= BIT12 | BIT13

            #elif(SPI0_PIN_OUT_GROUP == 1)
            #define xSPI0_MOSI_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA0MFP_Msk)) | (SYS_GPA_MFPL_PA0MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA1MFP_Msk)) | (SYS_GPA_MFPL_PA1MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA2MFP_Msk)) | (SYS_GPA_MFPL_PA2MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA3MFP_Msk)) | (SYS_GPA_MFPL_PA3MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA4MFP_Msk)) | (SYS_GPA_MFPL_PA4MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN  SYS->GPA_MFOS |= BIT0 | BIT1
        #endif //SPI0_PIN_OUT_GROUP

    #elif (CHIP_VER == VER_M2379)
        #if(SPI0_PIN_OUT_GROUP == 0)
            #define xSPI0_MOSI_PIN  SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB12MFP_Msk)) | (SYS_GPB_MFPH_PB12MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB13MFP_Msk)) | (SYS_GPB_MFPH_PB13MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB14MFP_Msk)) | (SYS_GPB_MFPH_PB14MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB15MFP_Msk)) | (SYS_GPB_MFPH_PB15MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB0MFP_Msk)) | (SYS_GPB_MFPL_PB0MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN  SYS->GPB_MFOS |= BIT12 | BIT13

            #elif(SPI0_PIN_OUT_GROUP == 1)
            #define xSPI0_MOSI_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA0MFP_Msk)) | (SYS_GPA_MFPL_PA0MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA1MFP_Msk)) | (SYS_GPA_MFPL_PA1MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA2MFP_Msk)) | (SYS_GPA_MFPL_PA2MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA3MFP_Msk)) | (SYS_GPA_MFPL_PA3MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA4MFP_Msk)) | (SYS_GPA_MFPL_PA4MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN  SYS->GPA_MFOS |= BIT0 | BIT1

            #elif(SPI0_PIN_OUT_GROUP == 2)
            #define xSPI0_MOSI_PIN  SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD0MFP_Msk)) | (SYS_GPD_MFPL_PD0MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD1MFP_Msk)) | (SYS_GPD_MFPL_PD1MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD2MFP_Msk)) | (SYS_GPD_MFPL_PD2MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD3MFP_Msk)) | (SYS_GPD_MFPL_PD3MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPD_MFPH = (SYS->GPD_MFPH & (~SYS_GPD_MFPH_PD13MFP_Msk)) | (SYS_GPD_MFPH_PD13MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN  SYS->GPD_MFOS |= BIT0 | BIT1

            #elif(SPI0_PIN_OUT_GROUP == 3)
            #define xSPI0_MOSI_PIN  SYS->GPF_MFPL = (SYS->GPF_MFPL & (~SYS_GPF_MFPL_PF6MFP_Msk)) | (SYS_GPF_MFPL_PF6MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPF_MFPL = (SYS->GPF_MFPL & (~SYS_GPF_MFPL_PF7MFP_Msk)) | (SYS_GPF_MFPL_PF7MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD2MFP_Msk)) | (SYS_GPD_MFPL_PD2MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD3MFP_Msk)) | (SYS_GPD_MFPL_PD3MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB11MFP_Msk)) | (SYS_GPB_MFPH_PB11MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN  SYS->GPF_MFOS |= BIT7 | BIT6
        #endif // SPI0_PIN_OUT_GROUP

    #elif (CHIP_VER == VER_M256D)
        #if(SPI0_PIN_OUT_GROUP == 0)
            #define xSPI0_MOSI_PIN  SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB12MFP_Msk)) | (SYS_GPB_MFPH_PB12MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB13MFP_Msk)) | (SYS_GPB_MFPH_PB13MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB14MFP_Msk)) | (SYS_GPB_MFPH_PB14MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB15MFP_Msk)) | (SYS_GPB_MFPH_PB15MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPC_MFPH = (SYS->GPC_MFPH & (~SYS_GPC_MFPH_PC14MFP_Msk)) | (SYS_GPC_MFPH_PC14MFP_SPI0_I2SMCLK)
            //#define xSPI0_MCLK_PIN  SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB0MFP_Msk)) | (SYS_GPB_MFPL_PB0MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN SYS->GPB_MFOS |= BIT12 | BIT13

            #elif(SPI0_PIN_OUT_GROUP==1)
            #define xSPI0_MOSI_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA0MFP_Msk)) | (SYS_GPA_MFPL_PA0MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA1MFP_Msk)) | (SYS_GPA_MFPL_PA1MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA2MFP_Msk)) | (SYS_GPA_MFPL_PA2MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA3MFP_Msk)) | (SYS_GPA_MFPL_PA3MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA4MFP_Msk)) | (SYS_GPA_MFPL_PA4MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN  SYS->GPA_MFOS |= BIT0 | BIT1

            #elif(SPI0_PIN_OUT_GROUP == 2)
            #define xSPI0_MOSI_PIN  SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD0MFP_Msk)) | (SYS_GPD_MFPL_PD0MFP_SPI0_MOSI)
            #define xSPI0_MISO_PIN  SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD1MFP_Msk)) | (SYS_GPD_MFPL_PD1MFP_SPI0_MISO)
            #define xSPI0_CLK_PIN   SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD2MFP_Msk)) | (SYS_GPD_MFPL_PD2MFP_SPI0_CLK)
            #define xSPI0_CSS_PIN   SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD3MFP_Msk)) | (SYS_GPD_MFPL_PD3MFP_SPI0_SS)
            #define xSPI0_MCLK_PIN  SYS->GPB_MFPH = (SYS->GPB_MFPH & (~SYS_GPB_MFPH_PB11MFP_Msk)) | (SYS_GPB_MFPH_PB11MFP_SPI0_I2SMCLK)
            #define xSPI0_MFOS_PIN  SYS->GPD_MFOS |= BIT0 | BIT1

        #endif //SPI0_PIN_OUT_GROUP

    #endif //CHIP_VER

    //------------------------------------------------------------------------------
    // SPI1 PIN define
    //------------------------------------------------------------------------------
    #define SPI1_MOSI_PIN_INIT                     SPI1_MOSI_PIN
    #define SPI1_MISO_PIN_INIT                     SPI1_MISO_PIN
    #define SPI1_CLK_PIN_INIT                      SPI1_CLK_PIN
    #define SPI1_CSS_PIN_INIT                      SPI1_CSS_PIN
    #define SPI1_MCLK_PIN_INIT                     SPI1_MCLK_PIN
    #define SPI1_MFOS_PIN_INIT                     SPI1_MFOS_PIN

    //#if (CHIP_VER == VER_M258G)

    #if(SPI1_PIN_OUT_GROUP == 0)
        #define SPI1_MOSI_PIN SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC6MFP_Msk)) | (SYS_GPC_MFPL_PC6MFP_SPI1_MOSI)
        #define SPI1_MISO_PIN SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC7MFP_Msk)) | (SYS_GPC_MFPL_PC7MFP_SPI1_MISO)
        #define SPI1_CLK_PIN  SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB3MFP_Msk)) | (SYS_GPB_MFPL_PB3MFP_SPI1_CLK)
        #define SPI1_CSS_PIN  SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB2MFP_Msk)) | (SYS_GPB_MFPL_PB2MFP_SPI1_SS)
        #define SPI1_MCLK_PIN SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA5MFP_Msk)) | (SYS_GPA_MFPL_PA5MFP_SPI1_I2SMCLK)
        #define SPI1_MFOS_PIN SYS->GPC_MFOS |= BIT6 | BIT7

    #elif (SPI1_PIN_OUT_GROUP == 1)
        #define SPI1_MOSI_PIN SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB4MFP_Msk)) | (7 << SYS_GPB_MFPL_PB4MFP_Pos) //MOSI
        #define SPI1_MISO_PIN SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB5MFP_Msk)) | (7 << SYS_GPB_MFPL_PB5MFP_Pos) //MISO
        #define SPI1_CLK_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA7MFP_Msk)) | (SYS_GPA_MFPL_PA7MFP_SPI1_CLK)
        #define SPI1_CSS_PIN  SYS->GPA_MFPL = (SYS->GPA_MFPL & (~SYS_GPA_MFPL_PA6MFP_Msk)) | (SYS_GPA_MFPL_PA6MFP_SPI1_SS)
        #define SPI1_MCLK_PIN SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB0MFP_Msk)) | ( 6 << SYS_GPB_MFPL_PB1MFP_Pos)
        #define SPI1_MFOS_PIN SYS->GPB_MFOS |= BIT4 | BIT5

    #elif (SPI1_PIN_OUT_GROUP == 2)
        #define SPI1_MOSI_PIN SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC2MFP_Msk)) | (7 << SYS_GPC_MFPL_PC2MFP_Pos) //MOSI
        #define SPI1_MISO_PIN SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC3MFP_Msk)) | (7 << SYS_GPC_MFPL_PC3MFP_Pos) //MISO
        #define SPI1_CLK_PIN  SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC1MFP_Msk)) | (7 << SYS_GPC_MFPL_PC1MFP_Pos) //CLK
        #define SPI1_CSS_PIN  SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC0MFP_Msk)) | (7 << SYS_GPC_MFPL_PC0MFP_Pos) //SS
        #define SPI1_MCLK_PIN SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC4MFP_Msk)) | (7 << SYS_GPC_MFPL_PC4MFP_Pos)
        #define SPI1_MFOS_PIN SYS->GPC_MFOS |= BIT2 | BIT3

    #elif (SPI1_PIN_OUT_GROUP == 3)
        #define SPI1_MOSI_PIN SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD6MFP_Msk)) | (9 << SYS_GPD_MFPL_PD6MFP_Pos) //MOSI
        #define SPI1_MISO_PIN SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD7MFP_Msk)) | (9 << SYS_GPD_MFPL_PD7MFP_Pos) //MISO
        #define SPI1_CLK_PIN  SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD5MFP_Msk)) | (9 << SYS_GPD_MFPL_PD5MFP_Pos) //CLK
        #define SPI1_CSS_PIN  SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD4MFP_Msk)) | (9 << SYS_GPD_MFPL_PD4MFP_Pos) //SS
        #define SPI1_MCLK_PIN SYS->GPD_MFPH = (SYS->GPD_MFPH & (~SYS_GPD_MFPH_PD13MFP_Msk)) | SYS_GPD_MFPH_PD13MFP_SPI1_I2SMCLK
        #define SPI1_MFOS_PIN SYS->GPD_MFOS |= BIT6 | BIT7

    #elif (SPI1_PIN_OUT_GROUP == 4)
        #define SPI1_MOSI_PIN SYS->GPE_MFPL = (SYS->GPE_MFPL & (~SYS_GPE_MFPL_PE0MFP_Msk)) | (6 << SYS_GPE_MFPL_PE0MFP_Pos) //MOSI
        #define SPI1_MISO_PIN SYS->GPE_MFPL = (SYS->GPE_MFPL & (~SYS_GPE_MFPL_PE1MFP_Msk)) | (6 << SYS_GPE_MFPL_PE1MFP_Pos) //MISO
        #define SPI1_CLK_PIN  SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD5MFP_Msk)) | (9 << SYS_GPD_MFPL_PD5MFP_Pos) //CLK
        #define SPI1_CSS_PIN  SYS->GPD_MFPL = (SYS->GPD_MFPL & (~SYS_GPD_MFPL_PD4MFP_Msk)) | (9 << SYS_GPD_MFPL_PD4MFP_Pos) //SS
        #define SPI1_MCLK_PIN SYS->GPC_MFPL = (SYS->GPC_MFPL & (~SYS_GPC_MFPL_PC4MFP_Msk)) | (7 << SYS_GPC_MFPL_PC4MFP_Pos)
        #define SPI1_MFOS_PIN SYS->GPE_MFOS |= BIT0 | BIT1
    #endif //SPI1_PIN_OUT_GROUP

    //#endif //CHIP_VER

#endif //SPI_MODE

#endif /* _M25X_PIN_CONFIG_H_ */
