#ifndef _TC8263_PIN_CONFIG_H_
#define _TC8263_PIN_CONFIG_H_

#define SPI0_PIN_OUT_GROUP                      (1)
#define SPI1_PIN_OUT_GROUP                      (5)
#define SPI2_PIN_OUT_GROUP                      (0)
#define SPI3_PIN_OUT_GROUP                      (3)
#define LPSPI0_PIN_OUT_GROUP                    (1)

//------------------------------------------------------------------------------
// QSPI PIN Configure
//------------------------------------------------------------------------------
#define QSPI0_MOSI_PIN_INIT                   QSPI0_MOSI_PIN
#define QSPI0_MISO_PIN_INIT                   QSPI0_MISO_PIN
#define QSPI0_CLK_PIN_INIT                    QSPI0_CLK_PIN
#define QSPI0_CSS_PIN_INIT                    QSPI0_CSS_PIN
#define QSPI0_MOSI1_PIN_INIT                  QSPI0_MOSI1_PIN
#define QSPI0_MISO1_PIN_INIT                  QSPI0_MISO1_PIN

#define QSPI0_MOSI1_TO_GPIO_INIT              QSPI0_MOSI1_TO_GPIO_PIN
#define QSPI0_MISO1_TO_GPIO_INIT              QSPI0_MISO1_TO_GPIO_PIN

#define QSPI0_MFOS_PIN_INIT                   SPI0_MFOS_PIN

#if (QSPI0_PIN_OUT_GROUP == 0)
#define QSPI0_MOSI_PIN  SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA0MFP_Msk)) | SYS_GPA_MFP0_PA0MFP_QSPI0_MOSI0
#define QSPI0_MISO_PIN  SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA1MFP_Msk)) | SYS_GPA_MFP0_PA1MFP_QSPI0_MISO0
#define QSPI0_CLK_PIN   SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA2MFP_Msk)) | SYS_GPA_MFP0_PA2MFP_QSPI0_CLK
#define QSPI0_CSS_PIN   SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA3MFP_Msk)) | SYS_GPA_MFP0_PA3MFP_QSPI0_SS
#define QSPI0_MOSI1_PIN SYS->GPA_MFP1 = (SYS->GPA_MFP1 & (~SYS_GPA_MFP1_PA4MFP_Msk)) | SYS_GPA_MFP1_PA4MFP_QSPI0_MOSI1
#define QSPI0_MISO1_PIN SYS->GPA_MFP1 = (SYS->GPA_MFP1 & (~SYS_GPA_MFP1_PA5MFP_Msk)) | SYS_GPA_MFP1_PA5MFP_QSPI0_MISO1
#define QSPI0_MFOS_PIN  (SYS->GPA_MFOS |= BIT0 | BIT1)

#define QSPI0_MOSI1_TO_GPIO_PIN                   \
    do                                            \
    {                                             \
        SET_GPIO_PA4();                           \
        GPIO_SetMode(PA, BIT4, GPIO_MODE_OUTPUT); \
        PA4 = 1;                                  \
    } while (0)

#define QSPI0_MISO1_TO_GPIO_PIN                   \
    do                                            \
    {                                             \
        SET_GPIO_PA5();                           \
        GPIO_SetMode(PA, BIT5, GPIO_MODE_OUTPUT); \
        PA5 = 1;                                  \
    } while (0)

#elif (QSPI0_PIN_OUT_GROUP == 1)
#define QSPI0_MOSI_PIN  SYS->GPJ_MFP0 = (SYS->GPJ_MFP0 & (~SYS_GPJ_MFP0_PJ1MFP_Msk)) | SYS_GPJ_MFP0_PJ1MFP_QSPI0_MOSI0
#define QSPI0_MISO_PIN  SYS->GPJ_MFP0 = (SYS->GPJ_MFP0 & (~SYS_GPJ_MFP0_PJ0MFP_Msk)) | SYS_GPJ_MFP0_PJ0MFP_QSPI0_MISO0
#define QSPI0_CLK_PIN   SYS->GPI_MFP3 = (SYS->GPI_MFP3 & (~SYS_GPI_MFP3_PI15MFP_Msk)) | SYS_GPI_MFP3_PI15MFP_QSPI0_CLK
#define QSPI0_CSS_PIN   SYS->GPI_MFP3 = (SYS->GPI_MFP3 & (~SYS_GPI_MFP3_PI14MFP_Msk)) | SYS_GPI_MFP3_PI14MFP_QSPI0_SS
#define QSPI0_MOSI1_PIN SYS->GPI_MFP3 = (SYS->GPI_MFP3 & (~SYS_GPI_MFP3_PI13MFP_Msk)) | SYS_GPI_MFP3_PI13MFP_QSPI0_MOSI1
#define QSPI0_MISO1_PIN SYS->GPI_MFP3 = (SYS->GPI_MFP3 & (~SYS_GPI_MFP3_PI12MFP_Msk)) | SYS_GPI_MFP3_PI12MFP_QSPI0_MISO1
#define QSPI0_MFOS_PIN  (SYS->GPJ_MFOS |= BIT0 | BIT1)

#define QSPI0_MOSI1_TO_GPIO_PIN  \
    PI->MODE = (PI->MODE & ~(0x3ul << (13 << 1))) | (1 << (13 << 1));\
    SYS->GPI_MFP3 &= ~(SYS_GPI_MFP3_PI13MFP_Msk) | SYS_GPI_MFP3_PI13MFP_GPIO; \
    PI13 = 1

#define QSPI0_MISO1_TO_GPIO_PIN \
    PI->MODE = (PI->MODE & ~(0x3ul << (12 << 1))) | (1 << (12 << 1));\
    SYS->GPI_MFP3 &= ~(SYS_GPI_MFP3_PI12MFP_Msk) | SYS_GPI_MFP3_PI12MFP_GPIO; \
    PI12 = 1

#elif (QSPI0_PIN_OUT_GROUP == 2)
#define QSPI0_MOSI_PIN  SYS->GPC_MFP0 = (SYS->GPC_MFP0 & (~SYS_GPC_MFP0_PC0MFP_Msk)) | SYS_GPC_MFP0_PC0MFP_QSPI0_MOSI0
#define QSPI0_MISO_PIN  SYS->GPC_MFP0 = (SYS->GPC_MFP0 & (~SYS_GPC_MFP0_PC1MFP_Msk)) | SYS_GPC_MFP0_PC1MFP_QSPI0_MISO0
#define QSPI0_CLK_PIN   SYS->GPC_MFP0 = (SYS->GPC_MFP0 & (~SYS_GPC_MFP0_PC2MFP_Msk)) | SYS_GPC_MFP0_PC2MFP_QSPI0_CLK
#define QSPI0_CSS_PIN   SYS->GPC_MFP0 = (SYS->GPC_MFP0 & (~SYS_GPC_MFP0_PC3MFP_Msk)) | SYS_GPC_MFP0_PC3MFP_QSPI0_SS
#define QSPI0_MOSI1_PIN SYS->GPC_MFP1 = (SYS->GPC_MFP1 & (~SYS_GPC_MFP1_PC4MFP_Msk)) | SYS_GPC_MFP1_PC4MFP_QSPI0_MOSI1
#define QSPI0_MISO1_PIN SYS->GPC_MFP1 = (SYS->GPC_MFP1 & (~SYS_GPC_MFP1_PC5MFP_Msk)) | SYS_GPC_MFP1_PC5MFP_QSPI0_MISO1
#define QSPI0_MFOS_PIN  (SYS->GPC_MFOS |= BIT0 | BIT1)

#define QSPI0_MOSI1_TO_GPIO_PIN  \
    PC->MODE = (PC->MODE & ~(0x3ul << (4 << 1))) | (1 << (4 << 1));\
    SYS->GPC_MFP1 &= ~(SYS_GPC_MFP1_PC4MFP_Msk) | SYS_GPC_MFP1_PC4MFP_GPIO; \
    PC4 = 1

#define QSPI0_MISO1_TO_GPIO_PIN \
    PC->MODE = (PC->MODE & ~(0x3ul << (5 << 1))) | (1 << (5 << 1));\
    SYS->GPC_MFP1 &= ~(SYS_GPC_MFP1_PC5MFP_Msk) | SYS_GPC_MFP1_PC5MFP_GPIO; \
    PC5 = 1


#elif (QSPI0_PIN_OUT_GROUP == 3)
#define QSPI0_MOSI_PIN  SYS->GPE_MFP0 = (SYS->GPE_MFP0 & (~SYS_GPE_MFP0_PE0MFP_Msk)) | SYS_GPE_MFP0_PE0MFP_QSPI0_MOSI0
#define QSPI0_MISO_PIN  SYS->GPE_MFP0 = (SYS->GPE_MFP0 & (~SYS_GPE_MFP0_PE1MFP_Msk)) | SYS_GPE_MFP0_PE1MFP_QSPI0_MISO0
#define QSPI0_CLK_PIN   SYS->GPH_MFP2 = (SYS->GPH_MFP2 & (~SYS_GPH_MFP2_PH8MFP_Msk)) | SYS_GPH_MFP2_PH8MFP_QSPI0_CLK
#define QSPI0_CSS_PIN   SYS->GPH_MFP2 = (SYS->GPH_MFP2 & (~SYS_GPH_MFP2_PH9MFP_Msk)) | SYS_GPH_MFP2_PH9MFP_QSPI0_SS
#define QSPI0_MOSI1_PIN SYS->GPH_MFP2 = (SYS->GPH_MFP2 & (~SYS_GPH_MFP2_PH11MFP_Msk)) | SYS_GPH_MFP2_PH11MFP_QSPI0_MOSI1
#define QSPI0_MISO1_PIN SYS->GPC_MFP2 = (SYS->GPC_MFP2 & (~SYS_GPC_MFP2_PH10MFP_Msk)) | SYS_GPC_MFP2_PH10MFP_QSPI0_MISO1
#define QSPI0_MFOS_PIN  (SYS->GPE_MFOS |= BIT0 | BIT1)

#define QSPI0_MOSI1_TO_GPIO_PIN  \
    PH->MODE = (PH->MODE & ~(0x3ul << (11 << 1))) | (1 << (11 << 1));\
    SYS->GPH_MFP1 &= ~(SYS_GPH_MFP1_PH11MFP_Msk) | SYS_GPH_MFP1_PH11MFP_GPIO; \
    PH11 = 1

#define QSPI0_MISO1_TO_GPIO_PIN \
    PH->MODE = (PH->MODE & ~(0x3ul << (12 << 1))) | (1 << (12 << 1));\
    SYS->GPH_MFP1 &= ~(SYS_GPH_MFP1_PH12MFP_Msk) | SYS_GPH_MFP1_PH12MFP_GPIO; \
    PC12 = 1

#elif (QSPI0_PIN_OUT_GROUP == 4)
#define QSPI0_MOSI_PIN  SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA0MFP_Msk)) | SYS_GPA_MFP0_PA0MFP_QSPI0_MOSI0
#define QSPI0_MISO_PIN  SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA1MFP_Msk)) | SYS_GPA_MFP0_PA1MFP_QSPI0_MISO0
#define QSPI0_CLK_PIN   SYS->GPF_MFP0 = (SYS->GPF_MFP0 & (~SYS_GPF_MFP0_PF2MFP_Msk)) | SYS_GPF_MFP0_PA2MFP_QSPI0_CLK
#define QSPI0_CSS_PIN   SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA3MFP_Msk)) | SYS_GPA_MFP0_PA3MFP_QSPI0_SS
#define QSPI0_MOSI1_PIN SYS->GPA_MFP1 = (SYS->GPA_MFP1 & (~SYS_GPA_MFP1_PA4MFP_Msk)) | SYS_GPA_MFP1_PA4MFP_QSPI0_MOSI1
#define QSPI0_MISO1_PIN SYS->GPA_MFP1 = (SYS->GPA_MFP1 & (~SYS_GPA_MFP1_PA5MFP_Msk)) | SYS_GPA_MFP1_PA5MFP_QSPI0_MISO1
#define QSPI0_MFOS_PIN  (SYS->GPA_MFOS |= BIT0 | BIT1)

#define QSPI0_MOSI1_TO_GPIO_PIN  \
    PA->MODE = (PA->MODE & ~(0x3ul << (4 << 1))) | (1 << (4 << 1));\
    SYS->GPA_MFP1 &= ~(SYS_GPA_MFP1_PA4MFP_Msk) | SYS_GPA_MFP1_PA4MFP_GPIO; \
    PA4 = 1

#define QSPI0_MISO1_TO_GPIO_PIN \
    PA->MODE = (PA->MODE & ~(0x3ul << (5 << 1))) | (1 << (5 << 1));\
    SYS->GPA_MFP1 &= ~(SYS_GPA_MFP1_PA5MFP_Msk) | SYS_GPA_MFP1_PA5MFP_GPIO; \
    PA5 = 1

#elif (QSPI0_PIN_OUT_GROUP == 5)
#define QSPI0_MOSI_PIN  SYS->GPC_MFP0 = (SYS->GPC_MFP0 & (~SYS_GPC_MFP0_PC0MFP_Msk)) | SYS_GPC_MFP0_PC0MFP_QSPI0_MOSI0
#define QSPI0_MISO_PIN  SYS->GPC_MFP0 = (SYS->GPC_MFP0 & (~SYS_GPC_MFP0_PC1MFP_Msk)) | SYS_GPC_MFP0_PC1MFP_QSPI0_MISO0
#define QSPI0_CLK_PIN   SYS->GPC_MFP3 = (SYS->GPC_MFP3 & (~SYS_GPC_MFP3_PC14MFP_Msk)) | SYS_GPC_MFP3_PC14MFP_QSPI0_CLK
#define QSPI0_CSS_PIN   SYS->GPC_MFP0 = (SYS->GPC_MFP0 & (~SYS_GPC_MFP0_PC3MFP_Msk)) | SYS_GPC_MFP0_PC3MFP_QSPI0_SS
#define QSPI0_MOSI1_PIN SYS->GPC_MFP1 = (SYS->GPC_MFP1 & (~SYS_GPC_MFP1_PC4MFP_Msk)) | SYS_GPC_MFP1_PC4MFP_QSPI0_MOSI1
#define QSPI0_MISO1_PIN SYS->GPC_MFP1 = (SYS->GPC_MFP1 & (~SYS_GPC_MFP1_PC5MFP_Msk)) | SYS_GPC_MFP1_PC5MFP_QSPI0_MISO1
#define QSPI0_MFOS_PIN  (SYS->GPC_MFOS |= BIT0 | BIT1)

#define QSPI0_MOSI1_TO_GPIO_PIN                                                 \
    do                                                                          \
    {                                                                           \
        PC->MODE = (PC->MODE & ~(0x3ul << (4 << 1))) | (1 << (4 << 1));         \
        SYS->GPC_MFP1 &= ~(SYS_GPC_MFP1_PC4MFP_Msk) | SYS_GPC_MFP1_PC4MFP_GPIO; \
        PC4 = 1;                                                                \
    } while (0)

#define QSPI0_MISO1_TO_GPIO_PIN                                                 \
    do                                                                          \
    {                                                                           \
        PC->MODE = (PC->MODE & ~(0x3ul << (5 << 1))) | (1 << (5 << 1));         \
        SYS->GPC_MFP1 &= ~(SYS_GPC_MFP1_PC5MFP_Msk) | SYS_GPC_MFP1_PC5MFP_GPIO; \
        PC5 = 1;                                                                \
    } while (0)

#endif //QSPI0_PIN_OUT_GROUP

#define QSPI1_MOSI_PIN_INIT                   QSPI1_MOSI_PIN
#define QSPI1_MISO_PIN_INIT                   QSPI1_MISO_PIN
#define QSPI1_CLK_PIN_INIT                    QSPI1_CLK_PIN
#define QSPI1_CSS_PIN_INIT                    QSPI1_CSS_PIN
#define QSPI1_MOSI1_PIN_INIT                  QSPI1_MOSI1_PIN
#define QSPI1_MISO1_PIN_INIT                  QSPI1_MISO1_PIN

#define QSPI1_MOSI1_TO_GPIO_INIT              QSPI1_MOSI1_TO_GPIO_PIN
#define QSPI1_MISO1_TO_GPIO_INIT              QSPI1_MISO1_TO_GPIO_PIN

#define QSPI1_MFOS_PIN_INIT                   QSPI1_MFOS_PIN

#if (QSPI1_PIN_OUT_GROUP == 0)
#define QSPI1_MOSI_PIN  SYS->GPA_MFP3 = (SYS->GPA_MFP3 & (~SYS_GPA_MFP3_PA13MFP_Msk)) | SYS_GPA_MFP3_PA13MFP_QSPI1_MOSI0
#define QSPI1_MISO_PIN  SYS->GPA_MFP3 = (SYS->GPA_MFP3 & (~SYS_GPA_MFP3_PA12MFP_Msk)) | SYS_GPA_MFP3_PA12MFP_QSPI1_MISO0
#define QSPI1_CLK_PIN   SYS->GPC_MFP1 = (SYS->GPC_MFP1 & (~SYS_GPC_MFP1_PC4MFP_Msk)) | SYS_GPC_MFP1_PC4MFP_QSPI1_CLK
#define QSPI1_CSS_PIN   SYS->GPC_MFP1 = (SYS->GPC_MFP1 & (~SYS_GPC_MFP1_PC5MFP_Msk)) | SYS_GPC_MFP1_PC5MFP_QSPI1_SS
#define QSPI1_MOSI1_PIN SYS->GPA_MFP1 = (SYS->GPA_MFP1 & (~SYS_GPA_MFP1_PA6MFP_Msk)) | SYS_GPA_MFP1_PA6MFP_QSPI1_MOSI1
#define QSPI1_MISO1_PIN SYS->GPA_MFP1 = (SYS->GPA_MFP1 & (~SYS_GPA_MFP1_PA7MFP_Msk)) | SYS_GPA_MFP1_PA7MFP_QSPI1_MISO1
#define QSPI1_MFOS_PIN  (SYS->GPA_MFOS |= BIT12 | BIT13)

#define QSPI1_MOSI1_TO_GPIO_PIN                                                 \
    do                                                                          \
    {                                                                           \
        PA->MODE = (PA->MODE & ~(0x3ul << (4 << 1))) | (1 << (4 << 1));         \
        SYS->GPA_MFP1 &= ~(SYS_GPA_MFP1_PA4MFP_Msk) | SYS_GPA_MFP1_PA4MFP_GPIO; \
        PA4 = 1;                                                                \
    } while (0)

#define QSPI1_MISO1_TO_GPIO_PIN                                                 \
    do                                                                          \
    {                                                                           \
        PA->MODE = (PA->MODE & ~(0x3ul << (5 << 1))) | (1 << (5 << 1));         \
        SYS->GPA_MFP1 &= ~(SYS_GPA_MFP1_PA5MFP_Msk) | SYS_GPA_MFP1_PA5MFP_GPIO; \
        PA5 = 1;                                                                \
    } while (0)

#elif (QSPI1_PIN_OUT_GROUP == 1)
#define QSPI1_MOSI_PIN  SYS->GPG_MFP3 = (SYS->GPG_MFP3 & (~SYS_GPG_MFP3_PG14MFP_Msk)) | SYS_GPG_MFP3_PG14MFP_QSPI1_MOSI0
#define QSPI1_MISO_PIN  SYS->GPG_MFP3 = (SYS->GPG_MFP3 & (~SYS_GPG_MFP3_PG13MFP_Msk)) | SYS_GPG_MFP3_PG13MFP_QSPI1_MISO0
#define QSPI1_CLK_PIN   SYS->GPG_MFP3 = (SYS->GPG_MFP3 & (~SYS_GPG_MFP3_PG12MFP_Msk)) | SYS_GPG_MFP3_PG12MFP_QSPI1_CLK
#define QSPI1_CSS_PIN   SYS->GPG_MFP2 = (SYS->GPG_MFP2 & (~SYS_GPG_MFP2_PG11MFP_Msk)) | SYS_GPG_MFP2_PG11MFP_QSPI1_SS
#define QSPI1_MOSI1_PIN SYS->GPG_MFP2 = (SYS->GPG_MFP2 & (~SYS_GPG_MFP2_PG10MFP_Msk)) | SYS_GPG_MFP2_PG10MFP_QSPI1_MOSI1
#define QSPI1_MISO1_PIN SYS->GPG_MFP2 = (SYS->GPG_MFP2 & (~SYS_GPG_MFP2_PG9MFP_Msk)) | SYS_GPG_MFP2_PG9MFP_QSPI1_MISO1
#define QSPI1_MFOS_PIN  (SYS->GPG_MFOS |= BIT13 | BIT14)

#elif (QSPI1_PIN_OUT_GROUP == 2)
#define QSPI1_MOSI_PIN  SYS->GPJ_MFP1 = (SYS->GPJ_MFP1 & (~SYS_GPJ_MFP1_PJ5MFP_Msk)) | SYS_GPJ_MFP1_PJ5MFP_QSPI1_MOSI0
#define QSPI1_MISO_PIN  SYS->GPJ_MFP1 = (SYS->GPJ_MFP1 & (~SYS_GPJ_MFP1_PJ4MFP_Msk)) | SYS_GPJ_MFP1_PJ4MFP_QSPI1_MISO0
#define QSPI1_CLK_PIN   SYS->GPJ_MFP0 = (SYS->GPJ_MFP0 & (~SYS_GPJ_MFP0_PJ3MFP_Msk)) | SYS_GPJ_MFP0_PJ3MFP_QSPI1_CLK
#define QSPI1_CSS_PIN   SYS->GPJ_MFP0 = (SYS->GPJ_MFP0 & (~SYS_GPJ_MFP0_PJ2MFP_Msk)) | SYS_GPJ_MFP0_PJ2MFP_QSPI1_SS
#define QSPI1_MOSI1_PIN SYS->GPH_MFP3 = (SYS->GPH_MFP3 & (~SYS_GPH_MFP3_PH13MFP_Msk)) | SYS_GPH_MFP3_PH13MFP_QSPI1_MOSI1
#define QSPI1_MISO1_PIN SYS->GPH_MFP3 = (SYS->GPH_MFP3 & (~SYS_GPH_MFP3_PH12MFP_Msk)) | SYS_GPH_MFP3_PH12MFP_QSPI1_MISO1
#define QSPI1_MFOS_PIN  (SYS->GPJ_MFOS |= BIT4 | BIT5)

#elif (QSPI1_PIN_OUT_GROUP == 3)
#define QSPI1_MOSI_PIN  SYS->GPD_MFP1 = (SYS->GPD_MFP1 & (~SYS_GPD_MFP1_PD6MFP_Msk)) | SYS_GPD_MFP1_PD6MFP_QSPI1_MOSI0
#define QSPI1_MISO_PIN  SYS->GPD_MFP1 = (SYS->GPD_MFP1 & (~SYS_GPD_MFP1_PD7MFP_Msk)) | SYS_GPD_MFP1_PD7MFP_QSPI1_MISO0
#define QSPI1_CLK_PIN   SYS->GPH_MFP3 = (SYS->GPH_MFP3 & (~SYS_GPH_MFP3_PH15MFP_Msk)) | SYS_GPH_MFP3_PH15MFP_QSPI1_CLK
#define QSPI1_CSS_PIN   SYS->GPH_MFP3 = (SYS->GPH_MFP3 & (~SYS_GPH_MFP3_PH14MFP_Msk)) | SYS_GPH_MFP3_PH14MFP_QSPI1_SS
#define QSPI1_MOSI1_PIN SYS->GPH_MFP3 = (SYS->GPA_MFP3 & (~SYS_GPA_MFP3_PA13MFP_Msk)) | SYS_GPA_MFP3_PA13MFP_QSPI1_MOSI1
#define QSPI1_MISO1_PIN SYS->GPA_MFP3 = (SYS->GPA_MFP3 & (~SYS_GPA_MFP3_PA12MFP_Msk)) | SYS_GPA_MFP3_PA12MFP_QSPI1_MISO1
#define QSPI1_MFOS_PIN  (SYS->GPD_MFOS |= BIT6 | BIT7)

#endif //QSPI1_PIN_OUT_GROUP

//------------------------------------------------------------------------------
// SPI0 PIN Configure
//------------------------------------------------------------------------------
#define SPI0_MOSI_PIN_INIT                SPI0_MOSI_PIN
#define SPI0_MISO_PIN_INIT                SPI0_MISO_PIN
#define SPI0_CLK_PIN_INIT                 SPI0_CLK_PIN
#define SPI0_CSS_PIN_INIT                 SPI0_CSS_PIN
#define SPI0_MCLK_PIN_INIT                SPI0_MCLK_PIN
#define SPI0_MFOS_PIN_INIT                SPI0_MFOS_PIN

#if (SPI0_PIN_OUT_GROUP == 0)
    #define SPI0_MOSI_PIN  SYS->GPF_MFP1 = (SYS->GPF_MFP1 & (~SYS_GPF_MFP1_PF6MFP_Msk)) | SYS_GPF_MFP1_PF6MFP_SPI0_MOSI
    #define SPI0_MISO_PIN  SYS->GPF_MFP1 = (SYS->GPF_MFP1 & (~SYS_GPF_MFP1_PF7MFP_Msk)) | SYS_GPF_MFP1_PF7MFP_SPI0_MISO
    #define SPI0_CLK_PIN   SYS->GPF_MFP2 = (SYS->GPF_MFP2 & (~SYS_GPF_MFP2_PF8MFP_Msk)) | SYS_GPF_MFP2_PF8MFP_SPI0_CLK
    #define SPI0_CSS_PIN   SYS->GPF_MFP2 = (SYS->GPF_MFP2 & (~SYS_GPF_MFP2_PF9MFP_Msk)) | SYS_GPF_MFP2_PF9MFP_SPI0_SS
    #define SPI0_MCLK_PIN  SYS->GPF_MFP2 = (SYS->GPF_MFP2 & (~SYS_GPF_MFP2_PF10MFP_Msk)) | SYS_GPF_MFP2_PF10MFP_SPI0_I2SMCLK
    #define SPI0_MFOS_PIN  (SYS->GPF_MFOS |= BIT6 | BIT7)

#elif (SPI0_PIN_OUT_GROUP == 1)
    #define SPI0_MOSI_PIN  SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA0MFP_Msk)) | SYS_GPA_MFP0_PA0MFP_SPI0_MOSI
    #define SPI0_MISO_PIN  SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA1MFP_Msk)) | SYS_GPA_MFP0_PA1MFP_SPI0_MISO
    #define SPI0_CLK_PIN   SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA2MFP_Msk)) | SYS_GPA_MFP0_PA2MFP_SPI0_CLK
    #define SPI0_CSS_PIN   SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA3MFP_Msk)) | SYS_GPA_MFP0_PA3MFP_SPI0_SS
    #define SPI0_MCLK_PIN  SYS->GPA_MFP1 = (SYS->GPA_MFP1 & (~SYS_GPA_MFP1_PA4MFP_Msk)) | SYS_GPA_MFP1_PA4MFP_SPI0_I2SMCLK
    #define SPI0_MFOS_PIN  (SYS->GPA_MFOS |= BIT0 | BIT1)

#elif (SPI0_PIN_OUT_GROUP == 2)
    #define SPI0_MOSI_PIN  SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD0MFP_Msk)) | SYS_GPD_MFP0_PD0MFP_SPI0_MOSI
    #define SPI0_MISO_PIN  SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD1MFP_Msk)) | SYS_GPD_MFP0_PD1MFP_SPI0_MISO
    #define SPI0_CLK_PIN   SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD2MFP_Msk)) | SYS_GPD_MFP0_PD2MFP_SPI0_CLK
    #define SPI0_CSS_PIN   SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD3MFP_Msk)) | SYS_GPD_MFP0_PD3MFP_SPI0_SS
    #define SPI0_MCLK_PIN  SYS->GPD_MFP3 = (SYS->GPD_MFP3 & (~SYS_GPD_MFP3_PD13MFP_Msk)) | SYS_GPD_MFP3_PD13MFP_SPI0_I2SMCLK
    #define SPI0_MFOS_PIN  (SYS->GPD_MFOS |= BIT0 | BIT1)

#elif (SPI0_PIN_OUT_GROUP == 3)
    #define SPI0_MOSI_PIN  SYS->GPB_MFP3 = (SYS->GPB_MFP3 & (~SYS_GPB_MFP3_PB12MFP_Msk)) | SYS_GPB_MFP3_PB12MFP_SPI0_MOSI
    #define SPI0_MISO_PIN  SYS->GPB_MFP3 = (SYS->GPB_MFP3 & (~SYS_GPB_MFP3_PB13MFP_Msk)) | SYS_GPB_MFP3_PB13MFP_SPI0_MISO
    #define SPI0_CLK_PIN   SYS->GPB_MFP3 = (SYS->GPB_MFP3 & (~SYS_GPB_MFP3_PB14MFP_Msk)) | SYS_GPB_MFP3_PB14MFP_SPI0_CLK
    #define SPI0_CSS_PIN   SYS->GPB_MFP3 = (SYS->GPB_MFP3 & (~SYS_GPB_MFP3_PB15MFP_Msk)) | SYS_GPB_MFP3_PB15MFP_SPI0_SS
    #define SPI0_MCLK_PIN  SYS->GPC_MFP3 = (SYS->GPC_MFP3 & (~SYS_GPC_MFP3_PC14MFP_Msk)) | SYS_GPC_MFP3_PC14MFP_SPI0_I2SMCLK
    #define SPI0_MFOS_PIN  (SYS->GPB_MFOS |= BIT12 | BIT13)

#endif //SPI0_PIN_OUT_GROUP


//------------------------------------------------------------------------------
// SPI1 PIN define
//------------------------------------------------------------------------------
#define SPI1_MOSI_PIN_INIT                     SPI1_MOSI_PIN
#define SPI1_MISO_PIN_INIT                     SPI1_MISO_PIN
#define SPI1_CLK_PIN_INIT                      SPI1_CLK_PIN
#define SPI1_CSS_PIN_INIT                      SPI1_CSS_PIN
#define SPI1_MCLK_PIN_INIT                     SPI1_MCLK_PIN
#define SPI1_MFOS_PIN_INIT                     SPI1_MFOS_PIN

#if (SPI1_PIN_OUT_GROUP == 0)
    #define SPI1_MOSI_PIN  SYS->GPB_MFP1 = (SYS->GPB_MFP1 & (~SYS_GPB_MFP1_PB4MFP_Msk)) | SYS_GPB_MFP1_PB4MFP_SPI1_MOSI
    #define SPI1_MISO_PIN  SYS->GPB_MFP1 = (SYS->GPB_MFP1 & (~SYS_GPB_MFP1_PB5MFP_Msk)) | SYS_GPB_MFP1_PB5MFP_SPI1_MISO
    #define SPI1_CLK_PIN   SYS->GPB_MFP0 = (SYS->GPB_MFP0 & (~SYS_GPB_MFP0_PB3MFP_Msk)) | SYS_GPB_MFP0_PB3MFP_SPI1_CLK
    #define SPI1_CSS_PIN   SYS->GPB_MFP0 = (SYS->GPB_MFP0 & (~SYS_GPB_MFP0_PB2MFP_Msk)) | SYS_GPB_MFP0_PB2MFP_SPI1_SS
    #define SPI1_MCLK_PIN  SYS->GPA_MFP1 = (SYS->GPA_MFP1 & (~SYS_GPA_MFP1_PA5MFP_Msk)) | SYS_GPA_MFP1_PA5MFP_SPI1_I2SMCLK
    #define SPI1_MFOS_PIN  (SYS->GPB_MFOS |= BIT4 | BIT5)

#elif (SPI1_PIN_OUT_GROUP == 1)
    #define SPI1_MOSI_PIN  SYS->GPI_MFP2 = (SYS->GPI_MFP2 & (~SYS_GPI_MFP2_PI8MFP_Msk)) | SYS_GPI_MFP2_PI8MFP_SPI1_MOSI
    #define SPI1_MISO_PIN  SYS->GPI_MFP1 = (SYS->GPI_MFP1 & (~SYS_GPI_MFP1_PI7MFP_Msk)) | SYS_GPI_MFP1_PI7MFP_SPI1_MISO
    #define SPI1_CLK_PIN   SYS->GPI_MFP2 = (SYS->GPI_MFP2 & (~SYS_GPI_MFP2_PI9MFP_Msk)) | SYS_GPI_MFP2_PI9MFP_SPI1_CLK
    #define SPI1_CSS_PIN   SYS->GPI_MFP2 = (SYS->GPI_MFP2 & (~SYS_GPI_MFP2_PI10MFP_Msk)) | SYS_GPI_MFP2_PI10MFP_SPI1_SS
    #define SPI1_MCLK_PIN  SYS->GPI_MFP1 = (SYS->GPI_MFP1 & (~SYS_GPI_MFP1_PI6MFP_Msk)) | SYS_GPI_MFP1_PI6MFP_SPI1_I2SMCLK
    #define SPI1_MFOS_PIN  (SYS->GPI_MFOS |= BIT7 | BIT8)

#elif (SPI1_PIN_OUT_GROUP == 2)
    #define SPI1_MOSI_PIN  SYS->GPH_MFP2 = (SYS->GPH_MFP2 & (~SYS_GPH_MFP2_PH5MFP_Msk)) | SYS_GPH_MFP2_PH5MFP_SPI1_MOSI
    #define SPI1_MISO_PIN  SYS->GPH_MFP2 = (SYS->GPH_MFP2 & (~SYS_GPH_MFP2_PH4MFP_Msk)) | SYS_GPH_MFP2_PH4MFP_SPI1_MISO
    #define SPI1_CLK_PIN   SYS->GPH_MFP2 = (SYS->GPH_MFP2 & (~SYS_GPH_MFP2_PH6MFP_Msk)) | SYS_GPH_MFP2_PH6MFP_SPI1_CLK
    #define SPI1_CSS_PIN   SYS->GPH_MFP2 = (SYS->GPH_MFP2 & (~SYS_GPH_MFP2_PH7MFP_Msk)) | SYS_GPH_MFP2_PH7MFP_SPI1_SS
    #define SPI1_MCLK_PIN  SYS->GPH_MFP1 = (SYS->GPH_MFP1 & (~SYS_GPH_MFP1_PH3MFP_Msk)) | SYS_GPH_MFP1_PH3MFP_SPI1_I2SMCLK
    #define SPI1_MFOS_PIN  (SYS->GPH_MFOS |= BIT4 | BIT5)


#elif (SPI1_PIN_OUT_GROUP == 3)
    #define SPI1_MOSI_PIN  SYS->GPC_MFP1 = (SYS->GPC_MFP1 & (~SYS_GPC_MFP1_PC6MFP_Msk)) | SYS_GPC_MFP1_PC6MFP_SPI1_MOSI
    #define SPI1_MISO_PIN  SYS->GPC_MFP1 = (SYS->GPC_MFP1 & (~SYS_GPC_MFP1_PC7MFP_Msk)) | SYS_GPC_MFP1_PC7MFP_SPI1_MISO
    #define SPI1_CLK_PIN   SYS->GPA_MFP1 = (SYS->GPA_MFP1 & (~SYS_GPA_MFP1_PA7MFP_Msk)) | SYS_GPA_MFP1_PA7MFP_SPI1_CLK
    #define SPI1_CSS_PIN   SYS->GPA_MFP1 = (SYS->GPA_MFP1 & (~SYS_GPA_MFP1_PA6MFP_Msk)) | SYS_GPA_MFP1_PA6MFP_SPI1_SS
    #define SPI1_MCLK_PIN  SYS->GPA_MFP1 = (SYS->GPA_MFP1 & (~SYS_GPA_MFP1_PA5MFP_Msk)) | SYS_GPA_MFP1_PA5MFP_SPI1_I2SMCLK
    #define SPI1_MFOS_PIN  (SYS->GPC_MFOS |= BIT6 | BIT7)

#elif (SPI1_PIN_OUT_GROUP == 4)
    #define SPI1_MOSI_PIN  SYS->GPC_MFP0 = (SYS->GPC_MFP0 & (~SYS_GPC_MFP0_PC2MFP_Msk)) | SYS_GPC_MFP0_PC2MFP_SPI1_MOSI
    #define SPI1_MISO_PIN  SYS->GPC_MFP0 = (SYS->GPC_MFP0 & (~SYS_GPC_MFP0_PC3MFP_Msk)) | SYS_GPC_MFP0_PC3MFP_SPI1_MISO
    #define SPI1_CLK_PIN   SYS->GPC_MFP0 = (SYS->GPC_MFP0 & (~SYS_GPC_MFP0_PC1MFP_Msk)) | SYS_GPC_MFP0_PC1MFP_SPI1_CLK
    #define SPI1_CSS_PIN   SYS->GPC_MFP0 = (SYS->GPC_MFP0 & (~SYS_GPC_MFP0_PC0MFP_Msk)) | SYS_GPC_MFP0_PC0MFP_SPI1_SS
    #define SPI1_MCLK_PIN  SYS->GPC_MFP1 = (SYS->GPC_MFP1 & (~SYS_GPC_MFP1_PC4MFP_Msk)) | SYS_GPC_MFP1_PC4MFP_SPI1_I2SMCLK
    #define SPI1_MFOS_PIN  (SYS->GPC_MFOS |= BIT2 | BIT3)

#elif (SPI1_PIN_OUT_GROUP == 5)
    #define SPI1_MOSI_PIN  SYS->GPB_MFP1 = (SYS->GPB_MFP1 & (~SYS_GPB_MFP1_PB4MFP_Msk)) | SYS_GPB_MFP1_PB4MFP_SPI1_MOSI
    #define SPI1_MISO_PIN  SYS->GPB_MFP1 = (SYS->GPB_MFP1 & (~SYS_GPB_MFP1_PB5MFP_Msk)) | SYS_GPB_MFP1_PB5MFP_SPI1_MISO
    #define SPI1_CLK_PIN   SYS->GPA_MFP1 = (SYS->GPA_MFP1 & (~SYS_GPA_MFP1_PA7MFP_Msk)) | SYS_GPA_MFP1_PA7MFP_SPI1_CLK
    #define SPI1_CSS_PIN   SYS->GPA_MFP1 = (SYS->GPA_MFP1 & (~SYS_GPA_MFP1_PA6MFP_Msk)) | SYS_GPA_MFP1_PA6MFP_SPI1_SS
    #define SPI1_MCLK_PIN  SYS->GPD_MFP3 = (SYS->GPD_MFP3 & (~SYS_GPD_MFP3_PD13MFP_Msk)) | SYS_GPD_MFP3_PD13MFP_SPI1_I2SMCLK
    #define SPI1_MFOS_PIN  (SYS->GPD_MFOS |= BIT6 | BIT7)

#elif (SPI1_PIN_OUT_GROUP == 6)
    #define SPI1_MOSI_PIN  SYS->GPE_MFP0 = (SYS->GPE_MFP0 & (~SYS_GPE_MFP0_PE0MFP_Msk)) | SYS_GPE_MFP0_PE0MFP_SPI1_MOSI
    #define SPI1_MISO_PIN  SYS->GPE_MFP0 = (SYS->GPE_MFP0 & (~SYS_GPE_MFP0_PE1MFP_Msk)) | SYS_GPE_MFP0_PE1MFP_SPI1_MISO
    #define SPI1_CLK_PIN   SYS->GPH_MFP2 = (SYS->GPH_MFP2 & (~SYS_GPH_MFP2_PH8MFP_Msk)) | SYS_GPH_MFP2_PH8MFP_SPI1_CLK
    #define SPI1_CSS_PIN   SYS->GPH_MFP2 = (SYS->GPH_MFP2 & (~SYS_GPH_MFP2_PH9MFP_Msk)) | SYS_GPH_MFP2_PH9MFP_SPI1_SS
    #define SPI1_MCLK_PIN  SYS->GPH_MFP2 = (SYS->GPH_MFP2 & (~SYS_GPH_MFP2_PH10MFP_Msk)) | SYS_GPH_MFP2_PH10MFP_SPI1_I2SMCLK
    #define SPI1_MFOS_PIN  (SYS->GPE_MFOS |= BIT0 | BIT1)

#endif //SPI1_PIN_OUT_GROUP

//------------------------------------------------------------------------------
// SPI2 PIN define
//------------------------------------------------------------------------------
#define SPI2_MOSI_PIN_INIT                     SPI2_MOSI_PIN
#define SPI2_MISO_PIN_INIT                     SPI2_MISO_PIN
#define SPI2_CLK_PIN_INIT                      SPI2_CLK_PIN
#define SPI2_CSS_PIN_INIT                      SPI2_CSS_PIN
#define SPI2_MCLK_PIN_INIT                     SPI2_MCLK_PIN
#define SPI2_MFOS_PIN_INIT                     SPI2_MFOS_PIN

#if (SPI2_PIN_OUT_GROUP == 0)
#define SPI2_MOSI_PIN  SYS->GPA_MFP2 = (SYS->GPA_MFP2 & (~SYS_GPA_MFP2_PA8MFP_Msk)) | SYS_GPA_MFP2_PA8MFP_SPI2_MOSI
#define SPI2_MISO_PIN  SYS->GPA_MFP2 = (SYS->GPA_MFP2 & (~SYS_GPA_MFP2_PA9MFP_Msk)) | SYS_GPA_MFP2_PA9MFP_SPI2_MISO
#define SPI2_CLK_PIN   SYS->GPA_MFP2 = (SYS->GPA_MFP2 & (~SYS_GPA_MFP2_PA10MFP_Msk)) | SYS_GPA_MFP2_PA10MFP_SPI2_CLK
#define SPI2_CSS_PIN   SYS->GPA_MFP2 = (SYS->GPA_MFP2 & (~SYS_GPA_MFP2_PA11MFP_Msk)) | SYS_GPA_MFP2_PA11MFP_SPI2_SS
#define SPI2_MCLK_PIN  SYS->GPC_MFP3 = (SYS->GPC_MFP3 & (~SYS_GPC_MFP3_PC13MFP_Msk)) | SYS_GPC_MFP3_PC13MFP_SPI2_I2SMCLK
#define SPI2_MFOS_PIN  (SYS->GPA_MFOS |= BIT8 | BIT9)

#elif (SPI2_PIN_OUT_GROUP == 1)
#define SPI2_MOSI_PIN  SYS->GPF_MFP2 = (SYS->GPF_MFP2 & (~SYS_GPF_MFP2_PF11MFP_Msk)) | SYS_GPF_MFP2_PF11MFP_SPI2_MOSI
#define SPI2_MISO_PIN  SYS->GPG_MFP1 = (SYS->GPG_MFP1 & (~SYS_GPG_MFP1_PG4MFP_Msk)) | SYS_GPG_MFP1_PG4MFP_SPI2_MISO
#define SPI2_CLK_PIN   SYS->GPG_MFP0 = (SYS->GPG_MFP0 & (~SYS_GPG_MFP0_PG3MFP_Msk)) | SYS_GPG_MFP0_PG3MFP_SPI2_CLK
#define SPI2_CSS_PIN   SYS->GPG_MFP0 = (SYS->GPG_MFP0 & (~SYS_GPG_MFP0_PG2MFP_Msk)) | SYS_GPG_MFP0_PG2MFP_SPI2_SS
#define SPI2_MCLK_PIN  SYS->GPG_MFP0 = (SYS->GPG_MFP0 & (~SYS_GPG_MFP0_PG1MFP_Msk)) | SYS_GPG_MFP0_PG1MFP_SPI2_I2SMCLK
#define SPI2_MFOS_PIN  \
    do{\
        SYS->GPF_MFOS |= BIT11;\
        SYS->GPG_MFOS |= BIT4;\
    }while (0)

#elif (SPI2_PIN_OUT_GROUP == 2)
#define SPI2_MOSI_PIN  SYS->GPE_MFP2 = (SYS->GPE_MFP2 & (~SYS_GPE_MFP2_PE10MFP_Msk)) | SYS_GPE_MFP2_PE10MFP_SPI2_MOSI
#define SPI2_MISO_PIN  SYS->GPE_MFP2 = (SYS->GPE_MFP2 & (~SYS_GPE_MFP2_PE9MFP_Msk)) | SYS_GPE_MFP2_PE9MFP_SPI2_MISO
#define SPI2_CLK_PIN   SYS->GPE_MFP2 = (SYS->GPE_MFP2 & (~SYS_GPE_MFP2_PE8MFP_Msk)) | SYS_GPE_MFP2_PE8MFP_SPI2_CLK
#define SPI2_CSS_PIN   SYS->GPE_MFP2 = (SYS->GPE_MFP2 & (~SYS_GPE_MFP2_PE11MFP_Msk)) | SYS_GPE_MFP2_PE11MFP_SPI2_SS
#define SPI2_MCLK_PIN  SYS->GPE_MFP3 = (SYS->GPE_MFP3 & (~SYS_GPE_MFP3_PE12MFP_Msk)) | SYS_GPE_MFP3_PE12MFP_SPI2_I2SMCLK
#define SPI2_MFOS_PIN  (SYS->GPE_MFOS |= BIT9 | BIT10)


#elif (SPI2_PIN_OUT_GROUP == 3)
#define SPI2_MOSI_PIN  SYS->GPA_MFP3 = (SYS->GPA_MFP3 & (~SYS_GPA_MFP3_PA15MFP_Msk)) | SYS_GPA_MFP3_PA15MFP_SPI2_MOSI
#define SPI2_MISO_PIN  SYS->GPA_MFP3 = (SYS->GPA_MFP3 & (~SYS_GPA_MFP3_PA14MFP_Msk)) | SYS_GPA_MFP3_PA14MFP_SPI2_MISO
#define SPI2_CLK_PIN   SYS->GPA_MFP3 = (SYS->GPA_MFP3 & (~SYS_GPA_MFP3_PA13MFP_Msk)) | SYS_GPA_MFP3_PA13MFP_SPI2_CLK
#define SPI2_CSS_PIN   SYS->GPA_MFP3 = (SYS->GPA_MFP3 & (~SYS_GPA_MFP3_PA12MFP_Msk)) | SYS_GPA_MFP3_PA12MFP_SPI2_SS
#define SPI2_MCLK_PIN  SYS->GPB_MFP0 = (SYS->GPB_MFP0 & (~SYS_GPB_MFP0_PB0MFP_Msk)) | SYS_GPB_MFP0_PB0MFP_SPI2_I2SMCLK
#define SPI2_MFOS_PIN  (SYS->GPA_MFOS |= BIT14 | BIT15)

#endif //SPI2_PIN_OUT_GROUP

//------------------------------------------------------------------------------
// SPI3 PIN define
//------------------------------------------------------------------------------
#define SPI3_MOSI_PIN_INIT                     SPI3_MOSI_PIN
#define SPI3_MISO_PIN_INIT                     SPI3_MISO_PIN
#define SPI3_CLK_PIN_INIT                      SPI3_CLK_PIN
#define SPI3_CSS_PIN_INIT                      SPI3_CSS_PIN
#define SPI3_MCLK_PIN_INIT                     SPI3_MCLK_PIN
#define SPI3_MFOS_PIN_INIT                     SPI3_MFOS_PIN

#if (SPI3_PIN_OUT_GROUP == 0)
    #define SPI3_MOSI_PIN  SYS->GPC_MFP2 = (SYS->GPC_MFP2 & (~SYS_GPC_MFP2_PC11MFP_Msk)) | SYS_GPC_MFP2_PC11MFP_SPI3_MOSI
    #define SPI3_MISO_PIN  SYS->GPC_MFP2 = (SYS->GPC_MFP2 & (~SYS_GPC_MFP2_PC12MFP_Msk)) | SYS_GPC_MFP2_PC12MFP_SPI3_MISO
    #define SPI3_CLK_PIN   SYS->GPC_MFP2 = (SYS->GPC_MFP2 & (~SYS_GPC_MFP2_PC10MFP_Msk)) | SYS_GPC_MFP2_PC10MFP_SPI3_CLK
    #define SPI3_CSS_PIN   SYS->GPC_MFP2 = (SYS->GPC_MFP2 & (~SYS_GPC_MFP2_PC9MFP_Msk)) | SYS_GPC_MFP2_PC9MFP_SPI3_SS
    #define SPI3_MCLK_PIN  SYS->GPB_MFP0 = (SYS->GPB_MFP0 & (~SYS_GPB_MFP0_PB1MFP_Msk)) | SYS_GPB_MFP0_PB1MFP_SPI3_I2SMCLK
    #define SPI3_MFOS_PIN  (SYS->GPC_MFOS |= BIT11 | BIT12)

#elif (SPI3_PIN_OUT_GROUP == 1)
    #define SPI3_MOSI_PIN  SYS->GPE_MFP0 = (SYS->GPE_MFP0 & (~SYS_GPE_MFP0_PE2MFP_Msk)) | SYS_GPE_MFP0_PE2MFP_SPI3_MOSI
    #define SPI3_MISO_PIN  SYS->GPE_MFP0 = (SYS->GPE_MFP0 & (~SYS_GPE_MFP0_PE3MFP_Msk)) | SYS_GPE_MFP0_PE3MFP_SPI3_MISO
    #define SPI3_CLK_PIN   SYS->GPE_MFP1 = (SYS->GPE_MFP1 & (~SYS_GPE_MFP1_PE4MFP_Msk)) | SYS_GPE_MFP1_PE4MFP_SPI3_CLK
    #define SPI3_CSS_PIN   SYS->GPE_MFP1 = (SYS->GPE_MFP1 & (~SYS_GPE_MFP1_PE5MFP_Msk)) | SYS_GPE_MFP1_PE5MFP_SPI3_SS
    #define SPI3_MCLK_PIN  SYS->GPE_MFP1 = (SYS->GPE_MFP1 & (~SYS_GPE_MFP1_PE6MFP_Msk)) | SYS_GPE_MFP1_PE6MFP_SPI3_I2SMCLK
    #define SPI3_MFOS_PIN  (SYS->GPE_MFOS |= BIT2 | BIT3)

#elif (SPI3_PIN_OUT_GROUP == 2)
    #define SPI3_MOSI_PIN  SYS->GPG_MFP1 = (SYS->GPG_MFP1 & (~SYS_GPG_MFP1_PG8MFP_Msk)) | SYS_GPG_MFP1_PG8MFP_SPI3_MOSI
    #define SPI3_MISO_PIN  SYS->GPG_MFP1 = (SYS->GPG_MFP1 & (~SYS_GPG_MFP1_PG7MFP_Msk)) | SYS_GPG_MFP1_PG7MFP_SPI3_MISO
    #define SPI3_CLK_PIN   SYS->GPG_MFP1 = (SYS->GPG_MFP1 & (~SYS_GPG_MFP1_PG6MFP_Msk)) | SYS_GPG_MFP1_PG6MFP_SPI3_CLK
    #define SPI3_CSS_PIN   SYS->GPG_MFP1 = (SYS->GPG_MFP1 & (~SYS_GPG_MFP1_PG5MFP_Msk)) | SYS_GPG_MFP1_PG5MFP_SPI3_SS
    #define SPI3_MCLK_PIN  SYS->GPD_MFP3 = (SYS->GPD_MFP3 & (~SYS_GPD_MFP3_PD14MFP_Msk)) | SYS_GPD_MFP3_PD14MFP_SPI3_I2SMCLK
    #define SPI3_MFOS_PIN  (SYS->GPG_MFOS |= BIT7 | BIT8)

#elif (SPI3_PIN_OUT_GROUP == 3)
    #define SPI3_MOSI_PIN  SYS->GPB_MFP2 = (SYS->GPB_MFP2 & (~SYS_GPB_MFP2_PB8MFP_Msk)) | SYS_GPB_MFP2_PB8MFP_SPI3_MOSI
    #define SPI3_MISO_PIN  SYS->GPB_MFP2 = (SYS->GPB_MFP2 & (~SYS_GPB_MFP2_PB9MFP_Msk)) | SYS_GPB_MFP2_PB9MFP_SPI3_MISO
    #define SPI3_CLK_PIN   SYS->GPB_MFP2 = (SYS->GPB_MFP2 & (~SYS_GPB_MFP2_PB11MFP_Msk)) | SYS_GPB_MFP2_PB11MFP_SPI3_CLK
    #define SPI3_CSS_PIN   SYS->GPB_MFP2 = (SYS->GPB_MFP2 & (~SYS_GPB_MFP2_PB10MFP_Msk)) | SYS_GPB_MFP2_PB10MFP_SPI3_SS
    //#define SPI3_MCLK_PIN  SYS->GPF_MFP1 = (SYS->GPF_MFP1 & (~SYS_GPF_MFP1_PF6MFP_Msk)) | SYS_GPF_MFP1_PF6MFP_SPI3_I2SMCLK
    #define SPI3_MCLK_PIN  SYS->GPH_MFP1 = (SYS->GPH_MFP1 & (~SYS_GPH_MFP1_PH4MFP_Msk)) | SYS_GPH_MFP1_PH4MFP_SPI3_I2SMCLK
    #define SPI3_MFOS_PIN  (SYS->GPB_MFOS |= BIT8 | BIT9)

#endif //SPI3_PIN_OUT_GROUP

//------------------------------------------------------------------------------
// LPSPI0 PIN define
//------------------------------------------------------------------------------
#define LPSPI0_MOSI_PIN_INIT                     LPSPI0_MOSI_PIN
#define LPSPI0_MISO_PIN_INIT                     LPSPI0_MISO_PIN
#define LPSPI0_CLK_PIN_INIT                      LPSPI0_CLK_PIN
#define LPSPI0_CSS_PIN_INIT                      LPSPI0_CSS_PIN
#define LPSPI0_MFOS_PIN_INIT                     LPSPI0_MFOS_PIN

#if (LPSPI0_PIN_OUT_GROUP == 0)
    #define LPSPI0_MOSI_PIN SYS->GPF_MFP2 = (SYS->GPF_MFP2 & (~SYS_GPF_MFP2_PF6MFP_Msk)) | SYS_GPF_MFP2_PF6MFP_LPSPI0_MOSI
    #define LPSPI0_MISO_PIN SYS->GPF_MFP2 = (SYS->GPF_MFP2 & (~SYS_GPF_MFP2_PF7MFP_Msk)) | SYS_GPF_MFP2_PF7MFP_LPSPI0_MISO
    #define LPSPI0_CLK_PIN  SYS->GPF_MFP2 = (SYS->GPF_MFP2 & (~SYS_GPF_MFP2_PF8MFP_Msk)) | SYS_GPF_MFP2_PF8MFP_LPSPI0_CLK
    #define LPSPI0_CSS_PIN  SYS->GPF_MFP2 = (SYS->GPF_MFP2 & (~SYS_GPF_MFP2_PF9MFP_Msk)) | SYS_GPF_MFP2_PF9MFP_LPSPI0_SS
    #define LPSPI0_MFOS_PIN (SYS->GPF_MFOS |= BIT6 | BIT7)

#elif (LPSPI0_PIN_OUT_GROUP == 1)
    #define LPSPI0_MOSI_PIN SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA0MFP_Msk)) | SYS_GPA_MFP0_PA0MFP_LPSPI0_MOSI
    #define LPSPI0_MISO_PIN SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA1MFP_Msk)) | SYS_GPA_MFP0_PA1MFP_LPSPI0_MISO
    #define LPSPI0_CLK_PIN  SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA2MFP_Msk)) | SYS_GPA_MFP0_PA2MFP_LPSPI0_CLK
    #define LPSPI0_CSS_PIN  SYS->GPA_MFP0 = (SYS->GPA_MFP0 & (~SYS_GPA_MFP0_PA3MFP_Msk)) | SYS_GPA_MFP0_PA3MFP_LPSPI0_SS
    #define LPSPI0_MFOS_PIN (SYS->GPA_MFOS |= BIT0 | BIT1)

#elif (LPSPI0_PIN_OUT_GROUP == 2)
    #define LPSPI0_MOSI_PIN SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD0MFP_Msk)) | SYS_GPD_MFP0_PD0MFP_LPSPI0_MOSI
    #define LPSPI0_MISO_PIN SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD1MFP_Msk)) | SYS_GPD_MFP0_PD1MFP_LPSPI0_MISO
    #define LPSPI0_CLK_PIN  SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD2MFP_Msk)) | SYS_GPD_MFP0_PD2MFP_LPSPI0_CLK
    #define LPSPI0_CSS_PIN  SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD3MFP_Msk)) | SYS_GPD_MFP0_PD3MFP_LPSPI0_SS
    #define LPSPI0_MFOS_PIN (SYS->GPD_MFOS |= BIT0 | BIT1)

#elif (LPSPI0_PIN_OUT_GROUP == 3)
    #define LPSPI0_MOSI_PIN SYS->GPA_MFP3 = (SYS->GPA_MFP3 & (~SYS_GPA_MFP3_PA15MFP_Msk)) | SYS_GPA_MFP3_PA15MFP_LPSPI0_MOSI
    #define LPSPI0_MISO_PIN SYS->GPA_MFP3 = (SYS->GPA_MFP3 & (~SYS_GPA_MFP3_PA14MFP_Msk)) | SYS_GPA_MFP3_PA14MFP_LPSPI0_MISO
    #define LPSPI0_CLK_PIN  SYS->GPA_MFP3 = (SYS->GPA_MFP3 & (~SYS_GPA_MFP3_PA13MFP_Msk)) | SYS_GPA_MFP3_PA13MFP_LPSPI0_CLK
    #define LPSPI0_CSS_PIN  SYS->GPA_MFP3 = (SYS->GPA_MFP3 & (~SYS_GPA_MFP3_PA12MFP_Msk)) | SYS_GPA_MFP3_PA12MFP_LPSPI0_SS
    #define LPSPI0_MFOS_PIN (SYS->GPA_MFOS |= BIT15 | BIT14)

#elif (LPSPI0_PIN_OUT_GROUP == 4)
    #define LPSPI0_MOSI_PIN SYS->GPB_MFP3 = (SYS->GPB_MFP3 & (~SYS_GPB_MFP3_PB12MFP_Msk)) | SYS_GPB_MFP3_PB12MFP_LPSPI0_MOSI
    #define LPSPI0_MISO_PIN SYS->GPB_MFP3 = (SYS->GPB_MFP3 & (~SYS_GPB_MFP3_PB13MFP_Msk)) | SYS_GPB_MFP3_PB13MFP_LPSPI0_MISO
    #define LPSPI0_CLK_PIN  SYS->GPB_MFP3 = (SYS->GPB_MFP3 & (~SYS_GPB_MFP3_PB14MFP_Msk)) | SYS_GPB_MFP3_PB14MFP_LPSPI0_CLK
    #define LPSPI0_CSS_PIN  SYS->GPB_MFP3 = (SYS->GPB_MFP3 & (~SYS_GPB_MFP3_PB15MFP_Msk)) | SYS_GPB_MFP3_PB15MFP_LPSPI0_SS
    #define LPSPI0_MFOS_PIN (SYS->GPB_MFOS |= BIT12 | BIT13)

#endif //LPSPI0_PIN_OUT_GROUP

//#endif //CHIP_VER

#endif /* _TC8263_PIN_CONFIG_H_ */
