#ifndef _M55M1_PIN_CONFIG_H_
#define _M55M1_PIN_CONFIG_H_

//#include "sd_common.h"

#define SDH0_PIN_GROUP                  (0)
#define SDH1_PIN_GROUP                  (0)

//------------------------------------------------------------------------------
// SDH0 PIN Config
//------------------------------------------------------------------------------
#define SDH0_CD_PIN_INIT()              SDH0_CD_PIN
#define SDH0_CLK_PIN_INIT()             SDH0_CLK_PIN
#define SDH0_CMD_PIN_INIT()             SDH0_CMD_PIN
#define SDH0_DAT0_PIN_INIT()            SDH0_DAT0_PIN
#define SDH0_DAT1_PIN_INIT()            SDH0_DAT1_PIN
#define SDH0_DAT2_PIN_INIT()            SDH0_DAT2_PIN
#define SDH0_DAT3_PIN_INIT()            SDH0_DAT3_PIN

#if (SDH0_PIN_GROUP == 0)
    #define SDH0_CD_PIN    SYS->GPD_MFP3 |= (SYS->GPD_MFP3 & SYS_GPD_MFP3_PD13MFP_Msk) | SYS_GPD_MFP3_PD13MFP_SD0_nCD
    #define SDH0_CLK_PIN   SYS->GPE_MFP1 |= (SYS->GPE_MFP1 & SYS_GPE_MFP1_PE6MFP_Msk) | SYS_GPE_MFP1_PE6MFP_SD0_CLK
    #define SDH0_CMD_PIN   SYS->GPE_MFP1 |= (SYS->GPE_MFP1 & SYS_GPE_MFP1_PE7MFP_Msk) | SYS_GPE_MFP1_PE7MFP_SD0_CMD
    #define SDH0_DAT0_PIN  SYS->GPE_MFP0 |= (SYS->GPE_MFP0 & SYS_GPE_MFP0_PE2MFP_Msk) | SYS_GPE_MFP0_PE2MFP_SD0_DAT0
    #define SDH0_DAT1_PIN  SYS->GPE_MFP0 |= (SYS->GPE_MFP0 & SYS_GPE_MFP0_PE3MFP_Msk) | SYS_GPE_MFP0_PE3MFP_SD0_DAT1
    #define SDH0_DAT2_PIN  SYS->GPE_MFP1 |= (SYS->GPE_MFP1 & SYS_GPE_MFP1_PE4MFP_Msk) | SYS_GPE_MFP1_PE4MFP_SD0_DAT2
    #define SDH0_DAT3_PIN  SYS->GPE_MFP1 |= (SYS->GPE_MFP1 & SYS_GPE_MFP1_PE5MFP_Msk) | SYS_GPE_MFP1_PE5MFP_SD0_DAT3

#elif (SDH0_PIN_GROUP == 1)
    #define SDH0_CD_PIN    SYS->GPB_MFP3 |= (SYS->GPB_MFP3 & SYS_GPB_MFP3_PB12MFP_Msk) | SYS_GPB_MFP3_PB12MFP_SD0_nCD
    #define SDH0_CLK_PIN   SYS->GPB_MFP0 |= (SYS->GPB_MFP0 & SYS_GPB_MFP0_PB1MFP_Msk) | SYS_GPB_MFP0_PB1MFP_SD0_CLK
    #define SDH0_CMD_PIN   SYS->GPB_MFP0 |= (SYS->GPB_MFP0 & SYS_GPB_MFP0_PB0MFP_Msk) | SYS_GPB_MFP0_PB0MFP_SD0_CMD
    #define SDH0_DAT0_PIN  SYS->GPB_MFP0 |= (SYS->GPB_MFP0 & SYS_GPB_MFP0_PB2MFP_Msk) | SYS_GPB_MFP0_PB2MFP_SD0_DAT0
    #define SDH0_DAT1_PIN  SYS->GPB_MFP0 |= (SYS->GPB_MFP0 & SYS_GPB_MFP0_PB3MFP_Msk) | SYS_GPB_MFP0_PB3MFP_SD0_DAT1
    #define SDH0_DAT2_PIN  SYS->GPB_MFP1 |= (SYS->GPB_MFP1 & SYS_GPB_MFP1_PB4MFP_Msk) | SYS_GPB_MFP1_PB4MFP_SD0_DAT2
    #define SDH0_DAT3_PIN  SYS->GPB_MFP1 |= (SYS->GPB_MFP1 & SYS_GPB_MFP1_PB5MFP_Msk) | SYS_GPB_MFP1_PB5MFP_SD0_DAT3

#endif //SDH0_PIN_GROUP

//------------------------------------------------------------------------------
// SDH1 PIN Config
//------------------------------------------------------------------------------
#define SDH1_CD_PIN_INIT()                SDH1_CD_PIN
#define SDH1_CLK_PIN_INIT()               SDH1_CLK_PIN
#define SDH1_CMD_PIN_INIT()               SDH1_CMD_PIN
#define SDH1_DAT0_PIN_INIT()              SDH1_DAT0_PIN
#define SDH1_DAT1_PIN_INIT()              SDH1_DAT1_PIN
#define SDH1_DAT2_PIN_INIT()              SDH1_DAT2_PIN
#define SDH1_DAT3_PIN_INIT()              SDH1_DAT3_PIN

#if (SDH1_PIN_GROUP == 0)
    #define SDH1_CD_PIN    SYS->GPA_MFP1 |= (SYS->GPA_MFP1 & SYS_GPA_MFP1_PA6MFP_Msk) | SYS_GPA_MFP1_PA6MFP_SD1_nCD
    #define SDH1_CLK_PIN   SYS->GPA_MFP1 |= (SYS->GPA_MFP1 & SYS_GPA_MFP1_PA4MFP_Msk) | SYS_GPA_MFP1_PA4MFP_SD1_CLK
    #define SDH1_CMD_PIN   SYS->GPA_MFP1 |= (SYS->GPA_MFP1 & SYS_GPA_MFP1_PA5MFP_Msk) | SYS_GPA_MFP1_PA5MFP_SD1_CMD
    #define SDH1_DAT0_PIN  SYS->GPA_MFP0 |= (SYS->GPA_MFP0 & SYS_GPA_MFP0_PA0MFP_Msk) | SYS_GPA_MFP0_PA0MFP_SD1_DAT0
    #define SDH1_DAT1_PIN  SYS->GPA_MFP0 |= (SYS->GPA_MFP0 & SYS_GPA_MFP0_PA1MFP_Msk) | SYS_GPA_MFP0_PA1MFP_SD1_DAT1
    #define SDH1_DAT2_PIN  SYS->GPA_MFP0 |= (SYS->GPA_MFP0 & SYS_GPA_MFP0_PA2MFP_Msk) | SYS_GPA_MFP0_PA2MFP_SD1_DAT2
    #define SDH1_DAT3_PIN  SYS->GPA_MFP0 |= (SYS->GPA_MFP0 & SYS_GPA_MFP0_PA3MFP_Msk) | SYS_GPA_MFP0_PA3MFP_SD1_DAT3

#elif (SDH1_PIN_GROUP == 1)
    #define SDH1_CD_PIN    SYS->GPE_MFP3 |= (SYS->GPE_MFP3 & SYS_GPE_MFP3_PE14MFP_Msk) | SYS_GPE_MFP3_PE14MFP_SD1_nCD
    #define SDH1_CLK_PIN   SYS->GPB_MFP1 |= (SYS->GPB_MFP1 & SYS_GPB_MFP1_PB6MFP_Msk) | SYS_GPB_MFP1_PB6MFP_SD1_CLK
    #define SDH1_CMD_PIN   SYS->GPB_MFP1 |= (SYS->GPB_MFP1 & SYS_GPB_MFP1_PB7MFP_Msk) | SYS_GPB_MFP1_PB7MFP_SD1_CMD
    #define SDH1_DAT0_PIN  SYS->GPA_MFP0 |= (SYS->GPA_MFP0 & SYS_GPA_MFP0_PA0MFP_Msk) | SYS_GPA_MFP0_PA0MFP_SD1_DAT0
    #define SDH1_DAT1_PIN  SYS->GPA_MFP0 |= (SYS->GPA_MFP0 & SYS_GPA_MFP0_PA1MFP_Msk) | SYS_GPA_MFP0_PA1MFP_SD1_DAT1
    #define SDH1_DAT2_PIN  SYS->GPA_MFP0 |= (SYS->GPA_MFP0 & SYS_GPA_MFP0_PA2MFP_Msk) | SYS_GPA_MFP0_PA2MFP_SD1_DAT2
    #define SDH1_DAT3_PIN  SYS->GPA_MFP0 |= (SYS->GPA_MFP0 & SYS_GPA_MFP0_PA3MFP_Msk) | SYS_GPA_MFP0_PA3MFP_SD1_DAT3

#elif (SDH1_PIN_GROUP == 2)
    #define SDH1_CD_PIN    SYS->GPG_MFP3 |= (SYS->GPG_MFP3 & SYS_GPG_MFP3_PG15MFP_Msk) | SYS_GPG_MFP3_PG15MFP_SD1_nCD
    #define SDH1_CLK_PIN   SYS->GPG_MFP3 |= (SYS->GPG_MFP3 & SYS_GPG_MFP3_PG14MFP_Msk) | SYS_GPG_MFP3_PG14MFP_SD1_CLK
    #define SDH1_CMD_PIN   SYS->GPG_MFP3 |= (SYS->GPG_MFP3 & SYS_GPG_MFP3_PG13MFP_Msk) | SYS_GPG_MFP3_PG13MFP_SD1_CMD
    #define SDH1_DAT0_PIN  SYS->GPG_MFP3 |= (SYS->GPG_MFP3 & SYS_GPG_MFP3_PG12MFP_Msk) | SYS_GPG_MFP3_PG12MFP_SD1_DAT0
    #define SDH1_DAT1_PIN  SYS->GPG_MFP2 |= (SYS->GPG_MFP2 & SYS_GPG_MFP2_PG11MFP_Msk) | SYS_GPG_MFP2_PG11MFP_SD1_DAT1
    #define SDH1_DAT2_PIN  SYS->GPG_MFP2 |= (SYS->GPG_MFP2 & SYS_GPG_MFP2_PG10MFP_Msk) | SYS_GPG_MFP2_PG10MFP_SD1_DAT2
    #define SDH1_DAT3_PIN  SYS->GPG_MFP2 |= (SYS->GPG_MFP2 & SYS_GPG_MFP2_PG9MFP_Msk) | SYS_GPG_MFP2_PG9MFP_SD1_DAT3

#elif (SDH1_PIN_GROUP == 3)
    #define SDH1_CD_PIN    SYS->GPA_MFP3 |= (SYS->GPA_MFP3 & SYS_GPA_MFP3_PA12MFP_Msk) | SYS_GPA_MFP3_PA12MFP_SD1_nCD
    #define SDH1_CLK_PIN   SYS->GPJ_MFP3 |= (SYS->GPJ_MFP3 & SYS_GPJ_MFP3_PJ13MFP_Msk) | SYS_GPJ_MFP3_PJ13MFP_SD1_CLK
    #define SDH1_CMD_PIN   SYS->GPJ_MFP3 |= (SYS->GPJ_MFP3 & SYS_GPJ_MFP3_PJ12MFP_Msk) | SYS_GPJ_MFP3_PJ12MFP_SD1_CMD
    #define SDH1_DAT0_PIN  SYS->GPJ_MFP2 |= (SYS->GPJ_MFP2 & SYS_GPJ_MFP2_PJ11MFP_Msk) | SYS_GPJ_MFP2_PJ11MFP_SD1_DAT0
    #define SDH1_DAT1_PIN  SYS->GPJ_MFP2 |= (SYS->GPJ_MFP2 & SYS_GPJ_MFP2_PJ10MFP_Msk) | SYS_GPJ_MFP2_PJ10MFP_SD1_DAT1
    #define SDH1_DAT2_PIN  SYS->GPJ_MFP2 |= (SYS->GPJ_MFP2 & SYS_GPJ_MFP2_PJ9MFP_Msk) | SYS_GPJ_MFP2_PJ10MFP_SD1_DAT2
    #define SDH1_DAT3_PIN  SYS->GPJ_MFP2 |= (SYS->GPJ_MFP2 & SYS_GPJ_MFP2_PJ8MFP_Msk) | SYS_GPJ_MFP2_PJ8MFP_SD1_DAT3
#elif (SDH1_PIN_GROUP == 4)
    #define SDH1_CD_PIN    SYS->GPA_MFP1 |= (SYS->GPA_MFP1 & SYS_GPA_MFP1_PA6MFP_Msk) | SYS_GPA_MFP1_PA6MFP_SD1_nCD
    #define SDH1_CLK_PIN   SYS->GPA_MFP1 |= (SYS->GPA_MFP1 & SYS_GPA_MFP1_PA4MFP_Msk) | SYS_GPA_MFP1_PA4MFP_SD1_CLK
    #define SDH1_CMD_PIN   SYS->GPA_MFP1 |= (SYS->GPA_MFP1 & SYS_GPA_MFP1_PA5MFP_Msk) | SYS_GPA_MFP1_PA5MFP_SD1_CMD
    #define SDH1_DAT0_PIN  SYS->GPA_MFP2 |= (SYS->GPA_MFP2 & SYS_GPA_MFP2_PA8MFP_Msk) | SYS_GPA_MFP2_PA8MFP_SD1_DAT0
    #define SDH1_DAT1_PIN  SYS->GPA_MFP2 |= (SYS->GPA_MFP2 & SYS_GPA_MFP2_PA9MFP_Msk) | SYS_GPA_MFP2_PA9MFP_SD1_DAT1
    #define SDH1_DAT2_PIN  SYS->GPA_MFP2 |= (SYS->GPA_MFP2 & SYS_GPA_MFP2_PA10MFP_Msk) | SYS_GPA_MFP2_PA10MFP_SD1_DAT2
    #define SDH1_DAT3_PIN  SYS->GPA_MFP2 |= (SYS->GPA_MFP2 & SYS_GPA_MFP2_PA11MFP_Msk) | SYS_GPA_MFP2_PA11MFP_SD1_DAT3

#endif //SDH1_PIN_GROUP

#endif /* _M55M1_PIN_CONFIG_H_ */
