/**************************************************************************//**
 * @file     Sensor_PLDM.c
 * @version  V1.00
 * @brief    PLDM sensor driver
 *
 * @copyright (C) 2019 Nuvoton Technology Corp. All rights reserved.
 ******************************************************************************/
#include <stdio.h>
#include "NuMicro.h"
#include "../sensor_config.h"

#define PLDM_INPUT_FORMAT_YUV422_YUYV   (CCAP_PAR_INFMT_YUV422 | CCAP_PAR_INDATORD_YUYV)
#define PLDM_INPUT_FORMAT_YUV422_YVYU   (CCAP_PAR_INFMT_YUV422 | CCAP_PAR_INDATORD_YVYU)
#define PLDM_INPUT_FORMAT_YUV422_UYVY   (CCAP_PAR_INFMT_YUV422 | CCAP_PAR_INDATORD_UYVY)
#define PLDM_INPUT_FORMAT_YUV422_VYUY   (CCAP_PAR_INFMT_YUV422 | CCAP_PAR_INDATORD_VYUY)

#define PLDM_INPUT_FORMAT_RGB565_RGGB   (CCAP_PAR_INFMT_RGB565 | CCAP_PAR_INDATORD_RGGB)
#define PLDM_INPUT_FORMAT_RGB565_BGGR   (CCAP_PAR_INFMT_RGB565 | CCAP_PAR_INDATORD_BGGR)
#define PLDM_INPUT_FORMAT_RGB565_GBRG   (CCAP_PAR_INFMT_RGB565 | CCAP_PAR_INDATORD_GBRG)
#define PLDM_INPUT_FORMAT_RGB565_GRBG   (CCAP_PAR_INFMT_RGB565 | CCAP_PAR_INDATORD_GRBG)

#define PLDM_INPUT_FORMAT_RGB888_RGB    (CCAP_PAR_INFMT_RGB888 | CCAP_PAR_INDATORD_RGB888_RGB)
#define PLDM_INPUT_FORMAT_RGB888_RBG    (CCAP_PAR_INFMT_RGB888 | CCAP_PAR_INDATORD_RGB888_RBG)
#define PLDM_INPUT_FORMAT_RGB888_GRB    (CCAP_PAR_INFMT_RGB888 | CCAP_PAR_INDATORD_RGB888_GRB)
#define PLDM_INPUT_FORMAT_RGB888_GBR    (CCAP_PAR_INFMT_RGB888 | CCAP_PAR_INDATORD_RGB888_GBR)
#define PLDM_INPUT_FORMAT_RGB888_BRG    (CCAP_PAR_INFMT_RGB888 | CCAP_PAR_INDATORD_RGB888_BRG)
#define PLDM_INPUT_FORMAT_RGB888_BGR    (CCAP_PAR_INFMT_RGB888 | CCAP_PAR_INDATORD_RGB888_BGR)

// CCAP_CTL_MONO_Msk, CCAP_CTL_MY8_MY4, CCAP_CTL_MY8_MY8, CCAP_CTL_Luma_Y_One_Msk, CCAP_CTL_MY4_SWAP_Msk (with CCAP_CTL_MY8_MY4)
#define PLDM_INPUT_FORMAT_MONO_4BIT          (CCAP_CTL_MONO_Msk | CCAP_CTL_MY8_MY4)
#define PLDM_INPUT_FORMAT_MONO_4BIT_SWAP     (CCAP_CTL_MONO_Msk | CCAP_CTL_MY8_MY4_SWAP)
#define PLDM_INPUT_FORMAT_MONO_8BIT          (CCAP_CTL_MONO_Msk | CCAP_CTL_MY8_MY8)

#define PLDM_INPUT_WIDTH                320
#define PLDM_INPUT_HEIGHT               240
#define PLDM_INPUT_WIDTH_MAX            640
#define PLDM_INPUT_HEIGHT_MAX           480

struct NT_RegValue
{
    uint16_t    u16RegAddr;     /* Sensor Register Address */
    uint8_t     u8Value;        /* Sensor Register Data */
};

int InitPLDM_Sensor(uint32_t  u32DataBitCnt);

S_SENSOR_INFO g_sSensorYUV422 = { "PLDM_YUV422", (CCAP_PAR_VSP_HIGH | CCAP_PAR_HSP_HIGH   | CCAP_PAR_PCLKP_HIGH), PLDM_INPUT_FORMAT_YUV422_YUYV, PLDM_INPUT_WIDTH, PLDM_INPUT_HEIGHT, InitPLDM_Sensor };
S_SENSOR_INFO g_sSensorRGB565 = { "PLDM_RGB565", (CCAP_PAR_VSP_HIGH | CCAP_PAR_HSP_LOW   | CCAP_PAR_PCLKP_HIGH), PLDM_INPUT_FORMAT_RGB565_GRBG, PLDM_INPUT_WIDTH, PLDM_INPUT_HEIGHT, InitPLDM_Sensor };
//S_SENSOR_INFO g_sSensorRGB888 = { "PLDM_RGB888", (CCAP_PAR_VSP_HIGH | CCAP_PAR_HSP_HIGH  | CCAP_PAR_PCLKP_HIGH), PLDM_INPUT_FORMAT_RGB888_RGB,  PLDM_INPUT_WIDTH, PLDM_INPUT_HEIGHT, InitPLDM_Sensor };
S_SENSOR_INFO g_sSensorRGB888 = { "PLDM_RGB888", (CCAP_PAR_VSP_HIGH | CCAP_PAR_HSP_HIGH  | CCAP_PAR_PCLKP_HIGH), PLDM_INPUT_FORMAT_RGB888_RGB,  PLDM_INPUT_WIDTH_MAX, PLDM_INPUT_HEIGHT_MAX, InitPLDM_Sensor };
S_SENSOR_INFO g_sSensorMONO   = { "PLDM_MONO",   (CCAP_PAR_VSP_HIGH | CCAP_PAR_HSP_HIGH  | CCAP_PAR_PCLKP_HIGH), CCAP_CTL_MY8_MY4_SWAP,   PLDM_INPUT_WIDTH, PLDM_INPUT_HEIGHT, InitPLDM_Sensor };
S_SENSOR_INFO g_sSensorCCIR656 = { "PLDM_CCIR656",  (CCAP_PAR_CCIR656_NO_BLANK | CCAP_PAR_SENTYPE_CCIR656), PLDM_INPUT_FORMAT_YUV422_UYVY,   PLDM_INPUT_WIDTH, PLDM_INPUT_HEIGHT, InitPLDM_Sensor };

S_SENSOR_INFO g_sSensorYUV422_640x480 = { "PLDM_YUV422_1024x768", (CCAP_PAR_VSP_HIGH | CCAP_PAR_HSP_HIGH | CCAP_PAR_PCLKP_HIGH), PLDM_INPUT_FORMAT_YUV422_YUYV, PLDM_INPUT_WIDTH_MAX, PLDM_INPUT_HEIGHT_MAX, InitPLDM_Sensor };
S_SENSOR_INFO g_sSensorRGB565_640x480 = { "PLDM_RGB565_1024x768", (CCAP_PAR_VSP_HIGH | CCAP_PAR_HSP_HIGH | CCAP_PAR_PCLKP_HIGH), PLDM_INPUT_FORMAT_RGB565_GBRG, PLDM_INPUT_WIDTH_MAX, PLDM_INPUT_HEIGHT_MAX, InitPLDM_Sensor };

static void Delay(uint32_t nCount)
{
    volatile uint32_t i;

    for (; nCount != 0; nCount--)
        for (i = 0; i < 100; i++);
}

int InitPLDM_Sensor(uint32_t  u32DataBitCnt)
{
    return 0;
}
