/******************************************************************************
* @file    dmic_cunit.c
* @version V1.00
* @brief   CUnit test dmic
*
* SPDX-License-Identifier: Apache-2.0
* @copyright (C) 2023 Nuvoton Technology Corp. All rights reserved.
*****************************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "NuMicro.h"
#include "CUnit.h"
#include "Console.h"
#include "dmic_cunit.h"

#define SAMPLERATE_8K 8000
#define SAMPLERATE_16K 16000
#define SAMPLERATE_48K 48000

DMIC_VAD_BIQ_T sVAD_BIQCoeff;

int dmic_Test_Init(void)
{
    CLK_EnableAPLL(CLK_APLLCTL_APLLSRC_HIRC, 196575000, CLK_APLL1_SELECT);
    CLK_EnableXtalRC(CLK_SRCCTL_MIRCEN_Msk);
    CLK_WaitClockReady(CLK_STATUS_MIRCSTB_Msk);
    SYS->HIRC48MCFCTL = 0x00009999;
    CLK_EnableXtalRC(CLK_SRCCTL_HIRC48MEN_Msk);
    CLK_WaitClockReady(CLK_STATUS_HIRC48MSTB_Msk);

    CLK_EnableModuleClock(DMIC0_MODULE);
    CLK_EnableModuleClock(VAD0SEL_MODULE);
    return 0;
}
int dmic_Test_Clean(void)
{
    return 0;
}

void Const_DMIC_Test(void)
{
    CU_ASSERT_EQUAL(DMIC_CTL_FIFOWIDTH_24, (DMIC_CTL_FIFOWIDTH_Msk));
    CU_ASSERT_EQUAL(DMIC_CTL_FIFOWIDTH_16, (0UL << DMIC_CTL_FIFOWIDTH_Pos));
    CU_ASSERT_EQUAL(DMIC_CTL_GAINSTEP_1_2, (0UL << DMIC_CTL_GAINSTEP_Pos));
    CU_ASSERT_EQUAL(DMIC_CTL_GAINSTEP_1_4, (1UL << DMIC_CTL_GAINSTEP_Pos));
    CU_ASSERT_EQUAL(DMIC_CTL_GAINSTEP_1_8, (2UL << DMIC_CTL_GAINSTEP_Pos));
    CU_ASSERT_EQUAL(DMIC_CTL_GAINSTEP_1_16, (3UL << DMIC_CTL_GAINSTEP_Pos));
    CU_ASSERT_EQUAL(DMIC_DIV_DOWNSAMPLE_64, (0x0UL << DMIC_DIV_OSR_Pos));
    CU_ASSERT_EQUAL(DMIC_DIV_DOWNSAMPLE_128, (0x1UL << DMIC_DIV_OSR_Pos));
    CU_ASSERT_EQUAL(DMIC_DIV_DOWNSAMPLE_256, (0x2UL << DMIC_DIV_OSR_Pos));
    CU_ASSERT_EQUAL(DMIC_DIV_DOWNSAMPLE_100, (0x3UL << DMIC_DIV_OSR_Pos));
    CU_ASSERT_EQUAL(DMIC_DIV_DOWNSAMPLE_50, (0x7UL << DMIC_DIV_OSR_Pos));
    CU_ASSERT_EQUAL(DMIC_CTL_LATCHDATA_CH01F, (0x0UL << DMIC_CTL_LCHEDGE01_Pos));
    CU_ASSERT_EQUAL(DMIC_CTL_LATCHDATA_CH01R, (0x1UL << DMIC_CTL_LCHEDGE01_Pos));
    CU_ASSERT_EQUAL(DMIC_CTL_LATCHDATA_CH23F, (0x0UL << DMIC_CTL_LCHEDGE23_Pos));
    CU_ASSERT_EQUAL(DMIC_CTL_LATCHDATA_CH23R, (0x1UL << DMIC_CTL_LCHEDGE23_Pos));
    CU_PASS();
}

void Const_VAD_Test(void)
{
    CU_ASSERT_EQUAL(DMIC_VAD_SINC_CTL_DOWNSAMPLE_48, (0x0UL << VAD_SINCCTL_SINCOSR_Pos));
    CU_ASSERT_EQUAL(DMIC_VAD_SINC_CTL_DOWNSAMPLE_64, (0x1UL << VAD_SINCCTL_SINCOSR_Pos));
    CU_ASSERT_EQUAL(DMIC_VAD_SINC_CTL_DOWNSAMPLE_96, (0x2UL << VAD_SINCCTL_SINCOSR_Pos));
    CU_ASSERT_EQUAL(DMIC_VAD_CTL0_STAT_16MS, (0x99UL << VAD_CTL0_STAT_Pos));
    CU_ASSERT_EQUAL(DMIC_VAD_CTL0_STAT_8MS, (0xAAUL << VAD_CTL0_STAT_Pos));
    CU_ASSERT_EQUAL(DMIC_VAD_CTL0_STAT_4MS, (0xBBUL << VAD_CTL0_STAT_Pos));
    CU_ASSERT_EQUAL(DMIC_VAD_CTL0_STAT_2MS, (0xCCUL << VAD_CTL0_STAT_Pos));
    CU_ASSERT_EQUAL(DMIC_VAD_CTL0_LTAT_512MS, (0x4UL << VAD_CTL0_LTAT_Pos));
    CU_ASSERT_EQUAL(DMIC_VAD_CTL0_LTAT_256MS, (0x5UL << VAD_CTL0_LTAT_Pos));
    CU_ASSERT_EQUAL(DMIC_VAD_CTL0_LTAT_128MS, (0x6UL << VAD_CTL0_LTAT_Pos));
    CU_ASSERT_EQUAL(DMIC_VAD_CTL0_LTAT_64MS, (0x7UL << VAD_CTL0_LTAT_Pos));
    CU_ASSERT_EQUAL(DMIC_VAD_POWERTHRE_0DB, (0x0001UL));
    CU_ASSERT_EQUAL(DMIC_VAD_POWERTHRE_10DB, (0x0003UL));
    CU_ASSERT_EQUAL(DMIC_VAD_POWERTHRE_20DB, (0x000AUL));
    CU_ASSERT_EQUAL(DMIC_VAD_POWERTHRE_30DB, (0x0020UL));
    CU_ASSERT_EQUAL(DMIC_VAD_POWERTHRE_40DB, (0x0067UL));
    CU_ASSERT_EQUAL(DMIC_VAD_POWERTHRE_50DB, (0x0147UL));
    CU_ASSERT_EQUAL(DMIC_VAD_POWERTHRE_60DB, (0x040CUL));
    CU_ASSERT_EQUAL(DMIC_VAD_POWERTHRE_70DB, (0x0CCCUL));
    CU_ASSERT_EQUAL(DMIC_VAD_POWERTHRE_80DB, (0x2879UL));
    CU_ASSERT_EQUAL(DMIC_VAD_POWERTHRE_90DB, (0x7FFFUL));
    CU_PASS();
}

void INLINE_FUN_Test(void)
{
    DMIC_SetFIFOWidth(DMIC0, DMIC_CTL_FIFOWIDTH_24);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_FIFOWIDTH_Msk, BIT31);

    DMIC_SetFIFOWidth(DMIC0, DMIC_CTL_FIFOWIDTH_16);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_FIFOWIDTH_Msk, 0);

    DMIC_SetGainStep(DMIC0, DMIC_CTL_GAINSTEP_1_2);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_GAINSTEP_Msk, 0);

    DMIC_SetGainStep(DMIC0, DMIC_CTL_GAINSTEP_1_4);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_GAINSTEP_Msk, BIT27);

    DMIC_SetGainStep(DMIC0, DMIC_CTL_GAINSTEP_1_8);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_GAINSTEP_Msk, BIT28);

    DMIC_SetGainStep(DMIC0, DMIC_CTL_GAINSTEP_1_16);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_GAINSTEP_Msk, BIT27 | BIT28);

    DMIC_ResetDSP(DMIC0);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_SWRST_Msk, 0);

    DMIC_EnableHPF(DMIC0, DMIC_CTL_CH01HPFEN_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CH01HPFEN_Msk, BIT20);

    DMIC_DisableHPF(DMIC0, DMIC_CTL_CH01HPFEN_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CH01HPFEN_Msk, 0);

    DMIC_EnableHPF(DMIC0, DMIC_CTL_CH23HPFEN_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CH23HPFEN_Msk, BIT21);

    DMIC_DisableHPF(DMIC0, DMIC_CTL_CH23HPFEN_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CH23HPFEN_Msk, 0);

    DMIC_EnableHPF(DMIC0, DMIC_CTL_CH01HPFEN_Msk | DMIC_CTL_CH23HPFEN_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & (DMIC_CTL_CH01HPFEN_Msk | DMIC_CTL_CH23HPFEN_Msk), BIT20 | BIT21);

    DMIC_DisableHPF(DMIC0, DMIC_CTL_CH01HPFEN_Msk | DMIC_CTL_CH23HPFEN_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & (DMIC_CTL_CH01HPFEN_Msk | DMIC_CTL_CH23HPFEN_Msk), 0);

    DMIC_EnableMute(DMIC0, DMIC_CTL_CH0MUTE_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CH0MUTE_Msk, BIT12);

    DMIC_DisableMute(DMIC0, DMIC_CTL_CH0MUTE_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CH0MUTE_Msk, 0);

    DMIC_EnableMute(DMIC0, DMIC_CTL_CH1MUTE_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CH1MUTE_Msk, BIT13);

    DMIC_DisableMute(DMIC0, DMIC_CTL_CH1MUTE_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CH1MUTE_Msk, 0);

    DMIC_EnableMute(DMIC0, DMIC_CTL_CH2MUTE_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CH2MUTE_Msk, BIT14);

    DMIC_DisableMute(DMIC0, DMIC_CTL_CH2MUTE_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CH2MUTE_Msk, 0);

    DMIC_EnableMute(DMIC0, DMIC_CTL_CH3MUTE_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CH3MUTE_Msk, BIT15);

    DMIC_DisableMute(DMIC0, DMIC_CTL_CH3MUTE_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CH3MUTE_Msk, 0);

    DMIC_EnableMute(DMIC0, DMIC_CTL_CH1MUTE_Msk | DMIC_CTL_CH2MUTE_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & (DMIC_CTL_CH1MUTE_Msk | DMIC_CTL_CH2MUTE_Msk), BIT13 | BIT14);

    DMIC_DisableMute(DMIC0, DMIC_CTL_CH1MUTE_Msk | DMIC_CTL_CH2MUTE_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & (DMIC_CTL_CH1MUTE_Msk | DMIC_CTL_CH2MUTE_Msk), 0);

    DMIC_EnableMute(DMIC0, DMIC_CTL_CH0MUTE_Msk | DMIC_CTL_CH3MUTE_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & (DMIC_CTL_CH0MUTE_Msk | DMIC_CTL_CH3MUTE_Msk), BIT12 | BIT15);

    DMIC_DisableMute(DMIC0, DMIC_CTL_CH0MUTE_Msk | DMIC_CTL_CH3MUTE_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & (DMIC_CTL_CH0MUTE_Msk | DMIC_CTL_CH3MUTE_Msk), 0);

    DMIC_EnableMute(DMIC0, DMIC_CTL_CH1MUTE_Msk | DMIC_CTL_CH2MUTE_Msk | DMIC_CTL_CH0MUTE_Msk | DMIC_CTL_CH3MUTE_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & (0xF000), 0xF000);

    DMIC_DisableMute(DMIC0, DMIC_CTL_CH1MUTE_Msk | DMIC_CTL_CH2MUTE_Msk | DMIC_CTL_CH0MUTE_Msk | DMIC_CTL_CH3MUTE_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & (0xF000), 0);

    sVAD_BIQCoeff.u16BIQCoeffA1 = 0xc715;
    sVAD_BIQCoeff.u16BIQCoeffA2 = 0x19a0;
    sVAD_BIQCoeff.u16BIQCoeffB0 = 0x1ca3;
    sVAD_BIQCoeff.u16BIQCoeffB1 = 0xc6bb;
    sVAD_BIQCoeff.u16BIQCoeffB2 = 0x1ca3;
    DMIC_VAD_SetBIQCoeff(VAD0, &sVAD_BIQCoeff);
    CU_ASSERT_EQUAL(VAD0->BIQCTL0 & VAD_BIQCTL0_BIQA1_Msk, 0xc715);
    CU_ASSERT_EQUAL(VAD0->BIQCTL0 & VAD_BIQCTL0_BIQA2_Msk, 0x19a00000);
    CU_ASSERT_EQUAL(VAD0->BIQCTL1 & VAD_BIQCTL1_BIQB0_Msk, 0x1ca3);
    CU_ASSERT_EQUAL(VAD0->BIQCTL1 & VAD_BIQCTL1_BIQB1_Msk, 0xc6bb0000);
    CU_ASSERT_EQUAL(VAD0->BIQCTL2 & VAD_BIQCTL2_BIQB2_Msk, 0x1ca3);

    CU_PASS();
}

void Macro_DMIC_Test(void)
{
    DMIC_SET_LATCHEDGE_CH01(DMIC0, DMIC_CTL_LATCHDATA_CH01RF);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_LCHEDGE01_Msk, BIT8);

    DMIC_SET_LATCHEDGE_CH01(DMIC0, DMIC_CTL_LATCHDATA_CH01FR);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_LCHEDGE01_Msk, 0);

    DMIC_SET_LATCHEDGE_CH23(DMIC0, DMIC_CTL_LATCHDATA_CH23RF);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_LCHEDGE23_Msk, BIT9);

    DMIC_SET_LATCHEDGE_CH23(DMIC0, DMIC_CTL_LATCHDATA_CH23FR);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_LCHEDGE23_Msk, 0);

    DMIC_ENABLE_CHANNEL(DMIC0, DMIC_CTL_CHEN0_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CHEN0_Msk, BIT0);

    DMIC_DISABLE_CHANNEL(DMIC0, DMIC_CTL_CHEN0_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CHEN0_Msk, 0);

    DMIC_ENABLE_CHANNEL(DMIC0, DMIC_CTL_CHEN1_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CHEN1_Msk, BIT1);

    DMIC_DISABLE_CHANNEL(DMIC0, DMIC_CTL_CHEN1_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CHEN1_Msk, 0);

    DMIC_ENABLE_CHANNEL(DMIC0, DMIC_CTL_CHEN2_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CHEN2_Msk, BIT2);

    DMIC_DISABLE_CHANNEL(DMIC0, DMIC_CTL_CHEN2_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CHEN2_Msk, 0);

    DMIC_ENABLE_CHANNEL(DMIC0, DMIC_CTL_CHEN3_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CHEN3_Msk, BIT3);

    DMIC_DISABLE_CHANNEL(DMIC0, DMIC_CTL_CHEN3_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & DMIC_CTL_CHEN3_Msk, 0);

    DMIC_ENABLE_CHANNEL(DMIC0, DMIC_CTL_CHEN1_Msk | DMIC_CTL_CHEN2_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & (DMIC_CTL_CHEN1_Msk | DMIC_CTL_CHEN2_Msk), BIT1 | BIT2);

    DMIC_DISABLE_CHANNEL(DMIC0, DMIC_CTL_CHEN1_Msk | DMIC_CTL_CHEN2_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & (DMIC_CTL_CHEN1_Msk | DMIC_CTL_CHEN2_Msk), 0);

    DMIC_ENABLE_CHANNEL(DMIC0, DMIC_CTL_CHEN0_Msk | DMIC_CTL_CHEN3_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & (DMIC_CTL_CHEN0_Msk | DMIC_CTL_CHEN3_Msk), BIT0 | BIT3);

    DMIC_DISABLE_CHANNEL(DMIC0, DMIC_CTL_CHEN0_Msk | DMIC_CTL_CHEN3_Msk);
    CU_ASSERT_EQUAL(DMIC0->CTL & (DMIC_CTL_CHEN0_Msk | DMIC_CTL_CHEN3_Msk), 0);

    DMIC_ENABLE_FIFOTH_INT(DMIC0, 0xA);
    CU_ASSERT_EQUAL(DMIC0->DIV & (DMIC_DIV_DMTHIE_Msk | DMIC_DIV_DMTH_Msk), BIT21 | 0xA0000);

    DMIC_DISABLE_FIFOTH_INT(DMIC0);
    CU_ASSERT_EQUAL(DMIC0->DIV & (DMIC_DIV_DMTHIE_Msk | DMIC_DIV_DMTH_Msk), 0xA0000);

    DMIC_ENABLE_FIFOTH_INT(DMIC0, 0x15);
    CU_ASSERT_EQUAL(DMIC0->DIV & (DMIC_DIV_DMTHIE_Msk | DMIC_DIV_DMTH_Msk), BIT21 | 0x150000);

    DMIC_DISABLE_FIFOTH_INT(DMIC0);
    CU_ASSERT_EQUAL(DMIC0->DIV & (DMIC_DIV_DMTHIE_Msk | DMIC_DIV_DMTH_Msk), 0x150000);

    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_64);
    CU_ASSERT_EQUAL(DMIC0->DIV & (DMIC_DIV_OSR_Msk), 0);

    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_128);
    CU_ASSERT_EQUAL(DMIC0->DIV & (DMIC_DIV_OSR_Msk), BIT24);

    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_256);
    CU_ASSERT_EQUAL(DMIC0->DIV & (DMIC_DIV_OSR_Msk), BIT25);

    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_100);
    CU_ASSERT_EQUAL(DMIC0->DIV & (DMIC_DIV_OSR_Msk), BIT24 | BIT25);

    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_50);
    CU_ASSERT_EQUAL(DMIC0->DIV & (DMIC_DIV_OSR_Msk), BIT26 | BIT24 | BIT25);

    DMIC_ENABLE_LPPDMA(DMIC0);
    CU_ASSERT_EQUAL(DMIC0->LPPDMACTL & (DMIC_LPPDMACTL_LPPDMAEN_Msk), 1);

    DMIC_DISABLE_LPPDMA(DMIC0);
    CU_ASSERT_EQUAL(DMIC0->LPPDMACTL & (DMIC_LPPDMACTL_LPPDMAEN_Msk), 0);

    CU_ASSERT_EQUAL(DMIC_IS_FIFOEMPTY(DMIC0), BIT1);

    CU_ASSERT_EQUAL(DMIC_IS_FIFOFULL(DMIC0), 0);

    CU_ASSERT_EQUAL(DMIC_IS_FIFODMTH(DMIC0), 0);

    CU_PASS();
}

void Macro_VAD_Test(void)
{
    DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_64);
    CU_ASSERT_EQUAL(VAD0->SINCCTL & VAD_SINCCTL_SINCOSR_Msk, BIT8);

    DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_96);
    CU_ASSERT_EQUAL(VAD0->SINCCTL & VAD_SINCCTL_SINCOSR_Msk, BIT9);

    DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_48);
    CU_ASSERT_EQUAL(VAD0->SINCCTL & VAD_SINCCTL_SINCOSR_Msk, 0);

    DMIC_VAD_ENABLE(VAD0);
    CU_ASSERT_EQUAL(VAD0->SINCCTL & VAD_SINCCTL_VADEN_Msk, BIT31);

    DMIC_VAD_DISABLE(VAD0);
    CU_ASSERT_EQUAL(VAD0->SINCCTL & VAD_SINCCTL_VADEN_Msk, 0);

    DMIC_VAD_SET_STAT(VAD0, DMIC_VAD_CTL0_STAT_16MS);
    CU_ASSERT_EQUAL(VAD0->CTL0 & VAD_CTL0_STAT_Msk, 0x99);

    DMIC_VAD_SET_STAT(VAD0, DMIC_VAD_CTL0_STAT_8MS);
    CU_ASSERT_EQUAL(VAD0->CTL0 & VAD_CTL0_STAT_Msk, 0xAA);

    DMIC_VAD_SET_STAT(VAD0, DMIC_VAD_CTL0_STAT_4MS);
    CU_ASSERT_EQUAL(VAD0->CTL0 & VAD_CTL0_STAT_Msk, 0xBB);

    DMIC_VAD_SET_STAT(VAD0, DMIC_VAD_CTL0_STAT_2MS);
    CU_ASSERT_EQUAL(VAD0->CTL0 & VAD_CTL0_STAT_Msk, 0xCC);

    DMIC_VAD_SET_LTAT(VAD0, DMIC_VAD_CTL0_LTAT_512MS);
    CU_ASSERT_EQUAL(VAD0->CTL0 & VAD_CTL0_LTAT_Msk, (0x4UL << VAD_CTL0_LTAT_Pos));

    DMIC_VAD_SET_LTAT(VAD0, DMIC_VAD_CTL0_LTAT_256MS);
    CU_ASSERT_EQUAL(VAD0->CTL0 & VAD_CTL0_LTAT_Msk, (0x5UL << VAD_CTL0_LTAT_Pos));

    DMIC_VAD_SET_LTAT(VAD0, DMIC_VAD_CTL0_LTAT_128MS);
    CU_ASSERT_EQUAL(VAD0->CTL0 & VAD_CTL0_LTAT_Msk, (0x6UL << VAD_CTL0_LTAT_Pos));

    DMIC_VAD_SET_LTAT(VAD0, DMIC_VAD_CTL0_LTAT_64MS);
    CU_ASSERT_EQUAL(VAD0->CTL0 & VAD_CTL0_LTAT_Msk, (0x7UL << VAD_CTL0_LTAT_Pos));

    DMIC_VAD_SET_STTHRE(VAD0, DMIC_VAD_POWERTHRE_0DB);
    CU_ASSERT_EQUAL(VAD0->CTL1 & VAD_CTL1_STTHREHWM_Msk, (0x0001UL));

    DMIC_VAD_SET_STTHRE(VAD0, DMIC_VAD_POWERTHRE_10DB);
    CU_ASSERT_EQUAL(VAD0->CTL1 & VAD_CTL1_STTHREHWM_Msk, (0x0003UL));

    DMIC_VAD_SET_STTHRE(VAD0, DMIC_VAD_POWERTHRE_20DB);
    CU_ASSERT_EQUAL(VAD0->CTL1 & VAD_CTL1_STTHREHWM_Msk, (0x000AUL));

    DMIC_VAD_SET_STTHRE(VAD0, DMIC_VAD_POWERTHRE_30DB);
    CU_ASSERT_EQUAL(VAD0->CTL1 & VAD_CTL1_STTHREHWM_Msk, (0x0020UL));

    DMIC_VAD_SET_LTTHRE(VAD0, DMIC_VAD_POWERTHRE_40DB);
    CU_ASSERT_EQUAL(VAD0->CTL2 & VAD_CTL2_LTTHRE_Msk, (0x0067UL << VAD_CTL2_LTTHRE_Pos));

    DMIC_VAD_SET_LTTHRE(VAD0, DMIC_VAD_POWERTHRE_50DB);
    CU_ASSERT_EQUAL(VAD0->CTL2 & VAD_CTL2_LTTHRE_Msk, (0x0147UL << VAD_CTL2_LTTHRE_Pos));

    DMIC_VAD_SET_LTTHRE(VAD0, DMIC_VAD_POWERTHRE_60DB);
    CU_ASSERT_EQUAL(VAD0->CTL2 & VAD_CTL2_LTTHRE_Msk, (0x040CUL << VAD_CTL2_LTTHRE_Pos));

    DMIC_VAD_SET_LTTHRE(VAD0, DMIC_VAD_POWERTHRE_70DB);
    CU_ASSERT_EQUAL(VAD0->CTL2 & VAD_CTL2_LTTHRE_Msk, (0x0CCCUL << VAD_CTL2_LTTHRE_Pos));

    DMIC_VAD_SET_DEVTHRE(VAD0, DMIC_VAD_POWERTHRE_80DB);
    CU_ASSERT_EQUAL(VAD0->CTL3 & VAD_CTL3_DEVTHRE_Msk, (0x2879UL));

    DMIC_VAD_SET_DEVTHRE(VAD0, DMIC_VAD_POWERTHRE_90DB);
    CU_ASSERT_EQUAL(VAD0->CTL3 & VAD_CTL3_DEVTHRE_Msk, (0x7FFFUL));

    DMIC_VAD_ENABLE_BIQ(VAD0);
    CU_ASSERT_EQUAL(VAD0->BIQCTL2 & VAD_BIQCTL2_BIQEN_Msk, BIT31);

    DMIC_VAD_DISABLE_BIQ(VAD0);
    CU_ASSERT_EQUAL(VAD0->BIQCTL2 & VAD_BIQCTL2_BIQEN_Msk, 0);

    CU_PASS();
}

void Func1_Test(void)
{
    DMIC_SetDSPGainVolume(DMIC0, DMIC_CTL_CHEN0_Msk, -20);
    CU_ASSERT_EQUAL(DMIC0->GAINCTL0 & DMIC_GAINCTL0_CHyyLVOL_Msk, 0xCA00);
    DMIC_SetDSPGainVolume(DMIC0, DMIC_CTL_CHEN0_Msk, 0);
    CU_ASSERT_EQUAL(DMIC0->GAINCTL0 & DMIC_GAINCTL0_CHyyLVOL_Msk, 0xC000);
    DMIC_SetDSPGainVolume(DMIC0, DMIC_CTL_CHEN1_Msk, -20);
    CU_ASSERT_EQUAL(DMIC0->GAINCTL0 & DMIC_GAINCTL0_CHxxRVOL_Msk, 0xCA000000);
    DMIC_SetDSPGainVolume(DMIC0, DMIC_CTL_CHEN1_Msk, 0);
    CU_ASSERT_EQUAL(DMIC0->GAINCTL0 & DMIC_GAINCTL0_CHxxRVOL_Msk, 0xC0000000);
    DMIC_SetDSPGainVolume(DMIC0, DMIC_CTL_CHEN2_Msk, -20);
    CU_ASSERT_EQUAL(DMIC0->GAINCTL1 & DMIC_GAINCTL1_CHyyLVOL_Msk, 0xCA00);
    DMIC_SetDSPGainVolume(DMIC0, DMIC_CTL_CHEN2_Msk, 0);
    CU_ASSERT_EQUAL(DMIC0->GAINCTL1 & DMIC_GAINCTL1_CHyyLVOL_Msk, 0xC000);
    DMIC_SetDSPGainVolume(DMIC0, DMIC_CTL_CHEN3_Msk, -20);
    CU_ASSERT_EQUAL(DMIC0->GAINCTL1 & DMIC_GAINCTL1_CHxxRVOL_Msk, 0xCA000000);
    DMIC_SetDSPGainVolume(DMIC0, DMIC_CTL_CHEN3_Msk, 0);
    CU_ASSERT_EQUAL(DMIC0->GAINCTL1 & DMIC_GAINCTL1_CHxxRVOL_Msk, 0xC0000000);
    CU_PASS();
}

void Func_DMIC_SetSampleRate(void)
{
    CLK_SetModuleClock(DMIC0_MODULE, CLK_DMICSEL_DMIC0SEL_HIRC, CLK_DMICDIV_DMIC0DIV(1));
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_100);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), SAMPLERATE_8K);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_50);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), SAMPLERATE_8K);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_16K), SAMPLERATE_16K);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_48K), SAMPLERATE_48K);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_256);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_48K), SAMPLERATE_48K);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_128);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), 8522);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_64);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), 8152);
    CLK_SetModuleClock(DMIC0_MODULE, CLK_DMICSEL_DMIC0SEL_MIRC, CLK_DMICDIV_DMIC0DIV(1));
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_100);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), SAMPLERATE_8K);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_50);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), SAMPLERATE_8K);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_16K), SAMPLERATE_16K);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_256);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_16K), SAMPLERATE_16K);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_128);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), 10416);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_64);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), 8928);
    CLK_SetModuleClock(DMIC0_MODULE, CLK_DMICSEL_DMIC0SEL_PCLK4, CLK_DMICDIV_DMIC0DIV(1));
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_100);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), 8064);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_16K), 16129);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_50);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), 8064);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_16K), 16129);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_256);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), 8138);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_16K), 16276);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_48K), 48828);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_128);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), 8138);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_16K), 16276);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_48K), 48828);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_64);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), 8138);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_16K), 16276);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_48K), 48828);
    CLK_SetModuleClock(DMIC0_MODULE, CLK_DMICSEL_DMIC0SEL_HIRC48M, CLK_DMICDIV_DMIC0DIV(1));
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_100);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), SAMPLERATE_8K);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_16K), SAMPLERATE_16K);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_48K), SAMPLERATE_48K);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_50);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), SAMPLERATE_8K);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_16K), SAMPLERATE_16K);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_48K), SAMPLERATE_48K);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_256);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), 8152);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_128);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), 8152);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_16K), 16304);
    DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_64);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_8K), 8152);
    CU_ASSERT_EQUAL(DMIC_SetSampleRate(DMIC0, SAMPLERATE_16K), 16304);

    //    CLK_SetModuleClock(DMIC0_MODULE, CLK_DMICSEL_DMIC0SEL_HIRC, CLK_DMICDIV_DMIC0DIV(1));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_100);
    //    printf("100DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_50);
    //    printf("50DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_256);
    //    printf("256DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_128);
    //    printf("128DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_64);
    //    printf("64DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //    CLK_SetModuleClock(DMIC0_MODULE, CLK_DMICSEL_DMIC0SEL_MIRC, CLK_DMICDIV_DMIC0DIV(1));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_100);
    //    printf("100DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_50);
    //    printf("50DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_256);
    //    printf("256DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_128);
    //    printf("128DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_64);
    //    printf("64DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //    CLK_SetModuleClock(DMIC0_MODULE, CLK_DMICSEL_DMIC0SEL_PCLK4, CLK_DMICDIV_DMIC0DIV(1));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_100);
    //    printf("100DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_50);
    //    printf("50DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_256);
    //    printf("256DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_128);
    //    printf("128DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_64);
    //    printf("64DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //    CLK_SetModuleClock(DMIC0_MODULE, CLK_DMICSEL_DMIC0SEL_HIRC48M, CLK_DMICDIV_DMIC0DIV(1));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_100);
    //    printf("100DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_50);
    //    printf("50DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_256);
    //    printf("256DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_128);
    //    printf("128DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_64);
    //    printf("64DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //    CLK_SetModuleClock(DMIC0_MODULE, CLK_DMICSEL_DMIC0SEL_APLL1_DIV2, CLK_DMICDIV_DMIC0DIV(1));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_100);
    //    printf("100DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_50);
    //    printf("50DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_256);
    //    printf("256DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_128);
    //    printf("128DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    //      DMIC_SET_DOWNSAMPLE(DMIC0, DMIC_DIV_DOWNSAMPLE_64);
    //    printf("64DMIC_SetSampleRate(DMIC0, 8000) %d\n", DMIC_SetSampleRate(DMIC0, 8000));
    //    printf("DMIC_SetSampleRate(DMIC0, 16000) %d\n", DMIC_SetSampleRate(DMIC0, 16000));
    //    printf("DMIC_SetSampleRate(DMIC0, 24000) %d\n", DMIC_SetSampleRate(DMIC0, 24000));
    //    printf("DMIC_SetSampleRate(DMIC0, 32000) %d\n", DMIC_SetSampleRate(DMIC0, 32000));
    //    printf("DMIC_SetSampleRate(DMIC0, 40000) %d\n", DMIC_SetSampleRate(DMIC0, 40000));
    //    printf("DMIC_SetSampleRate(DMIC0, 48000) %d\n", DMIC_SetSampleRate(DMIC0, 48000));
    CU_PASS();
}

void Func_VAD_SetSampleRate(void)
{
    CLK_SetModuleClock(VAD0SEL_MODULE, CLK_DMICSEL_VAD0SEL_HIRC, 0);
    DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_48);
    CU_ASSERT_EQUAL(DMIC_VAD_SetSampleRate(VAD0, SAMPLERATE_8K), 8928);
    DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_96);
    CU_ASSERT_EQUAL(DMIC_VAD_SetSampleRate(VAD0, SAMPLERATE_8K), 10416);
    DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_64);
    CU_ASSERT_EQUAL(DMIC_VAD_SetSampleRate(VAD0, SAMPLERATE_8K), 9375);
    CU_ASSERT_EQUAL(DMIC_VAD_SetSampleRate(VAD0, SAMPLERATE_48K), 46875);
    CLK_SetModuleClock(VAD0SEL_MODULE, CLK_DMICSEL_VAD0SEL_MIRC, 0);
    DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_48);
    CU_ASSERT_EQUAL(DMIC_VAD_SetSampleRate(VAD0, SAMPLERATE_8K), 10416);
    DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_96);
    CU_ASSERT_EQUAL(DMIC_VAD_SetSampleRate(VAD0, SAMPLERATE_8K), 10416);
    DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_64);
    CU_ASSERT_EQUAL(DMIC_VAD_SetSampleRate(VAD0, SAMPLERATE_16K), 15625);
    CLK_SetModuleClock(VAD0SEL_MODULE, CLK_DMICSEL_VAD0SEL_PCLK4, 0);
    DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_48);
    CU_ASSERT_EQUAL(DMIC_VAD_SetSampleRate(VAD0, SAMPLERATE_8K), 8138);
    CU_ASSERT_EQUAL(DMIC_VAD_SetSampleRate(VAD0, SAMPLERATE_16K), 16276);
    DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_96);
    CU_ASSERT_EQUAL(DMIC_VAD_SetSampleRate(VAD0, SAMPLERATE_8K), 8138);
    CU_ASSERT_EQUAL(DMIC_VAD_SetSampleRate(VAD0, SAMPLERATE_16K), 16276);
    DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_64);
    CU_ASSERT_EQUAL(DMIC_VAD_SetSampleRate(VAD0, SAMPLERATE_8K), 8138);
    CU_ASSERT_EQUAL(DMIC_VAD_SetSampleRate(VAD0, SAMPLERATE_16K), 16276);
    CU_ASSERT_EQUAL(DMIC_VAD_SetSampleRate(VAD0, SAMPLERATE_48K), 48828);
    //    CLK_SetModuleClock(VAD0SEL_MODULE, CLK_DMICSEL_VAD0SEL_HIRC, 0);
    //      DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_48);
    //    printf("48DMIC_VAD_SetSampleRate(VAD0, 8000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 8000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 16000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 16000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 24000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 24000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 32000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 32000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 40000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 40000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 48000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 48000));
    //      DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_96);
    //    printf("96DMIC_VAD_SetSampleRate(VAD0, 8000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 8000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 16000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 16000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 24000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 24000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 32000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 32000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 40000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 40000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 48000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 48000));
    //      DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_64);
    //    printf("64DMIC_VAD_SetSampleRate(VAD0, 8000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 8000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 16000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 16000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 24000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 24000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 32000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 32000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 40000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 40000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 48000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 48000));
    //    CLK_SetModuleClock(VAD0SEL_MODULE, CLK_DMICSEL_VAD0SEL_MIRC, 0);
    //      DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_48);
    //    printf("48DMIC_VAD_SetSampleRate(VAD0, 8000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 8000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 16000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 16000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 24000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 24000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 32000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 32000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 40000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 40000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 48000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 48000));
    //      DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_96);
    //    printf("96DMIC_VAD_SetSampleRate(VAD0, 8000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 8000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 16000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 16000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 24000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 24000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 32000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 32000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 40000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 40000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 48000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 48000));
    //      DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_64);
    //    printf("64DMIC_VAD_SetSampleRate(VAD0, 8000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 8000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 16000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 16000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 24000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 24000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 32000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 32000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 40000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 40000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 48000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 48000));
    //    CLK_SetModuleClock(VAD0SEL_MODULE, CLK_DMICSEL_VAD0SEL_PCLK4, 0);
    //      DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_48);
    //    printf("48DMIC_VAD_SetSampleRate(VAD0, 8000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 8000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 16000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 16000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 24000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 24000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 32000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 32000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 40000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 40000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 48000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 48000));
    //      DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_96);
    //    printf("96DMIC_VAD_SetSampleRate(VAD0, 8000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 8000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 16000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 16000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 24000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 24000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 32000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 32000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 40000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 40000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 48000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 48000));
    //      DMIC_VAD_SET_DOWNSAMPLE(VAD0, DMIC_VAD_SINC_CTL_DOWNSAMPLE_64);
    //    printf("64DMIC_VAD_SetSampleRate(VAD0, 8000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 8000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 16000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 16000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 24000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 24000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 32000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 32000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 40000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 40000));
    //    printf("DMIC_VAD_SetSampleRate(VAD0, 48000) %d\n", DMIC_VAD_SetSampleRate(VAD0, 48000));
    CU_PASS();
}

CU_SuiteInfo dmicSuites[] =
{
    { "dmic Const Test", dmic_Test_Init, dmic_Test_Clean, NULL, NULL, dmic_ConstTest },
    { "dmic Macro Test", dmic_Test_Init, dmic_Test_Clean, NULL, NULL, dmic_MacroTest },
    { "dmic Func  Test", dmic_Test_Init, dmic_Test_Clean, NULL, NULL, dmic_FuncTest },
    CU_SUITE_INFO_NULL
};

CU_TestInfo  dmic_ConstTest[] =
{
    { "DMIC Const",  Const_DMIC_Test },
    { "VAD Const",  Const_VAD_Test },
    CU_TEST_INFO_NULL
};

CU_TestInfo  dmic_MacroTest[] =
{
    { "DMIC Macro",  Macro_DMIC_Test },
    { "VAD Macro",  Macro_VAD_Test },
    CU_TEST_INFO_NULL
};

CU_TestInfo  dmic_FuncTest[] =
{
    { "INLINE Func", INLINE_FUN_Test },
    { "Func1", Func1_Test },
    { "DMIC_SetSampleRate Func", Func_DMIC_SetSampleRate },
    { "VAD_SetSampleRate Func", Func_VAD_SetSampleRate },
    CU_TEST_INFO_NULL
};

/*** (C) COPYRIGHT 2023 Nuvoton Technology Corp. ***/