/******************************************************************************
* @file    scu_cunit.c
* @version V1.00
* @brief   SCU CUnit Test
*
* SPDX-License-Identifier: Apache-2.0
* @copyright (C) 2023 Nuvoton Technology Corp. All rights reserved.
*****************************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "NuMicro.h"
#include "CUnit.h"
#include "Console.h"
#include "scu_cunit.h"

int SCU_Test_Init(void)
{
    return 0;
}
int SCU_Test_Clean(void)
{
    return 0;
}

void Func_SCU_Test_DxPNSy(void)
{
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_NPU),       0);

    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SPIM0),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SPIM1),     0);

    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_PDMA0),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_PDMA1),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_USBH0),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_HSUSBH),    0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_HSUSBD),    0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SDH0),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SDH1),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EMAC0),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_CRYPTO),    0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_CRC),       0);

    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_KDF),       0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_CANFD0),    0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_CANFD1),    0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_ETMC),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SWDH),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SWODEC),    0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EBI),       0);

    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_WWDT0),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EADC0),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EPWM0),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_BPWM0),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EQEI0),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EQEI2),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_ECAP0),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_ECAP2),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_I2C0),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_I2C2),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_QSPI0),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SPI0),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SPI2),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART0),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART2),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART4),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART6),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART8),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_USCI0),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SC0),       0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SC2),       0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_PSIO),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_TMR01),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_DAC01),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_HSOTG),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_I2S0),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_ACMP01),    0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_USBD),      0);

    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_WWDT1),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EADC1),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EPWM1),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_BPWM1),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EQEI1),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EQEI3),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_ECAP1),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_ECAP3),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_I2C1),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_I2C3),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_QSPI1),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SPI1),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SPI3),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART1),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART3),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART5),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART7),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART9),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SC1),       0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_OTG),       0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_KPI),       0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_TMR23),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_TRNG),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_RTC),       0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_I2S1),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_ACMP23),    0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_I3C0),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UTCPD),     0);

    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_LPPDMA),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_CCAP),      0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_LPGPIO),    0);

    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_LPTMR01),   0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_TTMR01),    0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_LPADC0),    0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_LPI2C0),    0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_LPSPI0),    0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_DMIC0),     0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_LPUART0),   0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_AWF),       0);

    SCU_SET_PERI_NS(eSCU_PERI_IDX_NPU);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_NPU),       1);

    SCU_SET_PERI_NS(eSCU_PERI_IDX_SPIM0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SPIM0),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_SPIM1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SPIM1),     1);

    SCU_SET_PERI_NS(eSCU_PERI_IDX_PDMA0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_PDMA0),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_PDMA1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_PDMA1),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_USBH0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_USBH0),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_HSUSBH);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_HSUSBH),    1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_HSUSBD);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_HSUSBD),    1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_SDH0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SDH0),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_SDH1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SDH1),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_EMAC0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EMAC0),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_CRYPTO);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_CRYPTO),    1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_CRC);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_CRC),       1);

    SCU_SET_PERI_NS(eSCU_PERI_IDX_KDF);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_KDF),       1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_CANFD0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_CANFD0),    1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_CANFD1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_CANFD1),    1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_ETMC);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_ETMC),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_SWDH);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SWDH),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_SWODEC);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SWODEC),    1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_EBI);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EBI),       1);

    SCU_SET_PERI_NS(eSCU_PERI_IDX_WWDT0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_WWDT0),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_EADC0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EADC0),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_EPWM0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EPWM0),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_BPWM0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_BPWM0),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_EQEI0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EQEI0),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_EQEI2);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EQEI2),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_ECAP0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_ECAP0),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_ECAP2);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_ECAP2),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_I2C0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_I2C0),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_I2C2);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_I2C2),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_QSPI0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_QSPI0),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_SPI0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SPI0),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_SPI2);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SPI2),      1);
    // Skip debug port
    //SCU_SET_PERI_NS(eSCU_PERI_IDX_UART0);
    //CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART0),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_UART2);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART2),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_UART4);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART4),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_UART6);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART6),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_UART8);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART8),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_USCI0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_USCI0),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_SC0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SC0),       1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_SC2);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SC2),       1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_PSIO);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_PSIO),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_TMR01);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_TMR01),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_DAC01);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_DAC01),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_HSOTG);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_HSOTG),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_I2S0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_I2S0),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_ACMP01);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_ACMP01),    1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_USBD);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_USBD),      1);

    SCU_SET_PERI_NS(eSCU_PERI_IDX_WWDT1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_WWDT1),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_EADC1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EADC1),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_EPWM1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EPWM1),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_BPWM1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_BPWM1),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_EQEI1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EQEI1),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_EQEI3);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_EQEI3),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_ECAP1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_ECAP1),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_ECAP3);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_ECAP3),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_I2C1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_I2C1),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_I2C3);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_I2C3),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_QSPI1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_QSPI1),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_SPI1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SPI1),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_SPI3);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SPI3),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_UART1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART1),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_UART3);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART3),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_UART5);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART5),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_UART7);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART7),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_UART9);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UART9),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_SC1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_SC1),       1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_OTG);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_OTG),       1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_KPI);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_KPI),       1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_TMR23);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_TMR23),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_TRNG);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_TRNG),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_RTC);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_RTC),       1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_I2S1);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_I2S1),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_ACMP23);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_ACMP23),    1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_I3C0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_I3C0),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_UTCPD);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_UTCPD),     1);

    SCU_SET_PERI_NS(eSCU_PERI_IDX_LPPDMA);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_LPPDMA),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_CCAP);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_CCAP),      1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_LPGPIO);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_LPGPIO),    1);

    SCU_SET_PERI_NS(eSCU_PERI_IDX_LPTMR01);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_LPTMR01),   1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_TTMR01);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_TTMR01),    1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_LPADC0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_LPADC0),    1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_LPI2C0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_LPI2C0),    1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_LPSPI0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_LPSPI0),    1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_DMIC0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_DMIC0),     1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_LPUART0);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_LPUART0),   1);
    SCU_SET_PERI_NS(eSCU_PERI_IDX_AWF);
    CU_ASSERT_EQUAL(SCU_IS_PERI_NS(eSCU_PERI_IDX_AWF),       1);
}

void Func_SCU_Test_IONSx(void)
{
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PA), 0);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PB), 0);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PC), 0);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PD), 0);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PE), 0);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PF), 0);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PG), 0);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PH), 0);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PI), 0);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PJ), 0);

    SCU_SET_GPIO_NS(PA, BIT0);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PA), BIT0);

    SCU_SET_GPIO_NS(PB, BIT1);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PB), BIT1);

    SCU_SET_GPIO_NS(PC, BIT2);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PC), BIT2);

    SCU_SET_GPIO_NS(PD, BIT3);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PD), BIT3);

    SCU_SET_GPIO_NS(PE, BIT4);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PE), BIT4);

    SCU_SET_GPIO_NS(PF, BIT5);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PF), BIT5);

    SCU_SET_GPIO_NS(PG, BIT6);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PG), BIT6);

    SCU_SET_GPIO_NS(PH, BIT7);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PH), BIT7);

    SCU_SET_GPIO_NS(PI, BIT8);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PI), BIT8);

    SCU_SET_GPIO_NS(PJ, BIT9);
    CU_ASSERT_EQUAL(SCU_GET_GPIO_NS(PJ), BIT9);
}

void Func_SCU_Test_Const(void)
{
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[0], SCU_BASE + ((eSCU_PERI_IDX_NPU / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D0PNS0_NPU_Pos, eSCU_PERI_IDX_NPU % 32);

    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[2], SCU_BASE + ((eSCU_PERI_IDX_SPIM0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D0PNS2_SPIM0_Pos, eSCU_PERI_IDX_SPIM0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[2], SCU_BASE + ((eSCU_PERI_IDX_SPIM1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D0PNS2_SPIM1_Pos, eSCU_PERI_IDX_SPIM1 % 32);

    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[8], SCU_BASE + ((eSCU_PERI_IDX_PDMA0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS0_PDMA0_Pos, eSCU_PERI_IDX_PDMA0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[8], SCU_BASE + ((eSCU_PERI_IDX_PDMA1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS0_PDMA1_Pos, eSCU_PERI_IDX_PDMA1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[8], SCU_BASE + ((eSCU_PERI_IDX_USBH0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS0_USBH0_Pos, eSCU_PERI_IDX_USBH0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[8], SCU_BASE + ((eSCU_PERI_IDX_HSUSBH / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS0_HSUSBH_Pos, eSCU_PERI_IDX_HSUSBH % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[8], SCU_BASE + ((eSCU_PERI_IDX_HSUSBD / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS0_HSUSBD_Pos, eSCU_PERI_IDX_HSUSBD % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[8], SCU_BASE + ((eSCU_PERI_IDX_SDH0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS0_SDH0_Pos, eSCU_PERI_IDX_SDH0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[8], SCU_BASE + ((eSCU_PERI_IDX_SDH1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS0_SDH1_Pos, eSCU_PERI_IDX_SDH1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[8], SCU_BASE + ((eSCU_PERI_IDX_EMAC0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS0_EMAC0_Pos, eSCU_PERI_IDX_EMAC0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[8], SCU_BASE + ((eSCU_PERI_IDX_CRYPTO / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS0_CRYPTO_Pos, eSCU_PERI_IDX_CRYPTO % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[8], SCU_BASE + ((eSCU_PERI_IDX_CRC / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS0_CRC_Pos, eSCU_PERI_IDX_CRC % 32);

    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[9], SCU_BASE + ((eSCU_PERI_IDX_KDF / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS1_KDF_Pos, eSCU_PERI_IDX_KDF % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[9], SCU_BASE + ((eSCU_PERI_IDX_CANFD0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS1_CANFD0_Pos, eSCU_PERI_IDX_CANFD0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[9], SCU_BASE + ((eSCU_PERI_IDX_CANFD1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS1_CANFD1_Pos, eSCU_PERI_IDX_CANFD1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[9], SCU_BASE + ((eSCU_PERI_IDX_ETMC / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS1_ETMC_Pos, eSCU_PERI_IDX_ETMC % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[9], SCU_BASE + ((eSCU_PERI_IDX_SWDH / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS1_SWDH_Pos, eSCU_PERI_IDX_SWDH % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[9], SCU_BASE + ((eSCU_PERI_IDX_SWODEC / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS1_SWODEC_Pos, eSCU_PERI_IDX_SWODEC % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[9], SCU_BASE + ((eSCU_PERI_IDX_EBI / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS1_EBI_Pos, eSCU_PERI_IDX_EBI % 32);

    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_WWDT0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_WWDT0_Pos, eSCU_PERI_IDX_WWDT0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_EADC0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_EADC0_Pos, eSCU_PERI_IDX_EADC0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_EPWM0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_EPWM0_Pos, eSCU_PERI_IDX_EPWM0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_BPWM0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_BPWM0_Pos, eSCU_PERI_IDX_BPWM0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_EQEI0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_EQEI0_Pos, eSCU_PERI_IDX_EQEI0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_EQEI2 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_EQEI2_Pos, eSCU_PERI_IDX_EQEI2 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_ECAP0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_ECAP0_Pos, eSCU_PERI_IDX_ECAP0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_ECAP2 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_ECAP2_Pos, eSCU_PERI_IDX_ECAP2 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_I2C0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_I2C0_Pos, eSCU_PERI_IDX_I2C0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_I2C2 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_I2C2_Pos, eSCU_PERI_IDX_I2C2 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_QSPI0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_QSPI0_Pos, eSCU_PERI_IDX_QSPI0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_SPI0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_SPI0_Pos, eSCU_PERI_IDX_SPI0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_SPI2 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_SPI2_Pos, eSCU_PERI_IDX_SPI2 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_UART0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_UART0_Pos, eSCU_PERI_IDX_UART0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_UART2 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_UART2_Pos, eSCU_PERI_IDX_UART2 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_UART4 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_UART4_Pos, eSCU_PERI_IDX_UART4 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_UART6 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_UART6_Pos, eSCU_PERI_IDX_UART6 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_UART8 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_UART8_Pos, eSCU_PERI_IDX_UART8 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_USCI0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_USCI0_Pos, eSCU_PERI_IDX_USCI0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_SC0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_SC0_Pos, eSCU_PERI_IDX_SC0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_SC2 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_SC2_Pos, eSCU_PERI_IDX_SC2 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_PSIO / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_PSIO_Pos, eSCU_PERI_IDX_PSIO % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_TMR01 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_TMR01_Pos, eSCU_PERI_IDX_TMR01 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_DAC01 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_DAC01_Pos, eSCU_PERI_IDX_DAC01 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_HSOTG / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_HSOTG_Pos, eSCU_PERI_IDX_HSOTG % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_I2S0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_I2S0_Pos, eSCU_PERI_IDX_I2S0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_ACMP01 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_ACMP01_Pos, eSCU_PERI_IDX_ACMP01 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[10], SCU_BASE + ((eSCU_PERI_IDX_USBD / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS2_USBD_Pos, eSCU_PERI_IDX_USBD % 32);

    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_WWDT1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_WWDT1_Pos, eSCU_PERI_IDX_WWDT1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_EADC1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_EADC1_Pos, eSCU_PERI_IDX_EADC1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_EPWM1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_EPWM1_Pos, eSCU_PERI_IDX_EPWM1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_BPWM1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_BPWM1_Pos, eSCU_PERI_IDX_BPWM1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_EQEI1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_EQEI1_Pos, eSCU_PERI_IDX_EQEI1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_EQEI3 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_EQEI3_Pos, eSCU_PERI_IDX_EQEI3 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_ECAP1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_ECAP1_Pos, eSCU_PERI_IDX_ECAP1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_ECAP3 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_ECAP3_Pos, eSCU_PERI_IDX_ECAP3 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_I2C1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_I2C1_Pos, eSCU_PERI_IDX_I2C1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_I2C3 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_I2C3_Pos, eSCU_PERI_IDX_I2C3 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_QSPI1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_QSPI1_Pos, eSCU_PERI_IDX_QSPI1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_SPI1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_SPI1_Pos, eSCU_PERI_IDX_SPI1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_SPI3 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_SPI3_Pos, eSCU_PERI_IDX_SPI3 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_UART1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_UART1_Pos, eSCU_PERI_IDX_UART1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_UART3 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_UART3_Pos, eSCU_PERI_IDX_UART3 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_UART5 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_UART5_Pos, eSCU_PERI_IDX_UART5 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_UART7 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_UART7_Pos, eSCU_PERI_IDX_UART7 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_UART9 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_UART9_Pos, eSCU_PERI_IDX_UART9 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_SC1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_SC1_Pos, eSCU_PERI_IDX_SC1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_OTG / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_OTG_Pos, eSCU_PERI_IDX_OTG % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_KPI / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_KPI_Pos, eSCU_PERI_IDX_KPI % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_TMR23 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_TMR23_Pos, eSCU_PERI_IDX_TMR23 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_TRNG / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_TRNG_Pos, eSCU_PERI_IDX_TRNG % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_RTC / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_RTC_Pos, eSCU_PERI_IDX_RTC % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_I2S1 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_I2S1_Pos, eSCU_PERI_IDX_I2S1 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_ACMP23 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_ACMP23_Pos, eSCU_PERI_IDX_ACMP23 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_I3C0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_I3C0_Pos, eSCU_PERI_IDX_I3C0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[12], SCU_BASE + ((eSCU_PERI_IDX_UTCPD / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D1PNS4_UTCPD_Pos, eSCU_PERI_IDX_UTCPD % 32);

    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[16], SCU_BASE + ((eSCU_PERI_IDX_LPPDMA / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D2PNS0_LPPDMA_Pos, eSCU_PERI_IDX_LPPDMA % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[16], SCU_BASE + ((eSCU_PERI_IDX_CCAP / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D2PNS0_CCAP_Pos, eSCU_PERI_IDX_CCAP % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[16], SCU_BASE + ((eSCU_PERI_IDX_LPGPIO / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D2PNS0_LPGPIO_Pos, eSCU_PERI_IDX_LPGPIO % 32);

    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[18], SCU_BASE + ((eSCU_PERI_IDX_LPTMR01 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D2PNS2_LPTMR01_Pos, eSCU_PERI_IDX_LPTMR01 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[18], SCU_BASE + ((eSCU_PERI_IDX_TTMR01 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D2PNS2_TTMR01_Pos, eSCU_PERI_IDX_TTMR01 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[18], SCU_BASE + ((eSCU_PERI_IDX_LPADC0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D2PNS2_LPADC0_Pos, eSCU_PERI_IDX_LPADC0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[18], SCU_BASE + ((eSCU_PERI_IDX_LPI2C0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D2PNS2_LPI2C0_Pos, eSCU_PERI_IDX_LPI2C0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[18], SCU_BASE + ((eSCU_PERI_IDX_LPSPI0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D2PNS2_LPSPI0_Pos, eSCU_PERI_IDX_LPSPI0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[18], SCU_BASE + ((eSCU_PERI_IDX_DMIC0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D2PNS2_DMIC0_Pos, eSCU_PERI_IDX_DMIC0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[18], SCU_BASE + ((eSCU_PERI_IDX_LPUART0 / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D2PNS2_LPUART0_Pos, eSCU_PERI_IDX_LPUART0 % 32);
    CU_ASSERT_EQUAL((uint32_t)&SCU->DxPNSy[18], SCU_BASE + ((eSCU_PERI_IDX_AWF / 32) * 4));
    CU_ASSERT_EQUAL(SCU_D2PNS2_AWF_Pos, eSCU_PERI_IDX_AWF % 32);
}

void Func_SCU_Test_SVIENx(void)
{
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB0IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_APB0);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB0IEN_Msk, SCU_SVIEN0_APB0IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_APB0);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB0IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB1IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_APB1);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB1IEN_Msk, SCU_SVIEN0_APB1IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_APB1);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB1IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB2IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_APB2);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB2IEN_Msk, SCU_SVIEN0_APB2IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_APB2);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB2IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB3IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_APB3);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB3IEN_Msk, SCU_SVIEN0_APB3IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_APB3);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB3IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB4IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_APB4);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB4IEN_Msk, SCU_SVIEN0_APB4IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_APB4);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB4IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB5IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_APB5);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB5IEN_Msk, SCU_SVIEN0_APB5IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_APB5);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_APB5IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_D0PPC0IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_D0PPC0);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_D0PPC0IEN_Msk, SCU_SVIEN0_D0PPC0IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_D0PPC0);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_D0PPC0IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_D1PPC0IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_D1PPC0);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_D1PPC0IEN_Msk, SCU_SVIEN0_D1PPC0IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_D1PPC0);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_D1PPC0IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_D1PPC1IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_D1PPC1);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_D1PPC1IEN_Msk, SCU_SVIEN0_D1PPC1IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_D1PPC1);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_D1PPC1IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_D2PPC0IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_D2PPC0);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_D2PPC0IEN_Msk, SCU_SVIEN0_D2PPC0IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_D2PPC0);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_D2PPC0IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_EBIIEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_EBI);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_EBIIEN_Msk, SCU_SVIEN0_EBIIEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_EBI);
    CU_ASSERT_EQUAL(SCU->SVIEN0 & SCU_SVIEN0_EBIIEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_GDMAIEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_GDMA);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_GDMAIEN_Msk, SCU_SVIEN1_GDMAIEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_GDMA);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_GDMAIEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_PDMA0IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_PDMA0);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_PDMA0IEN_Msk, SCU_SVIEN1_PDMA0IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_PDMA0);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_PDMA0IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_PDMA1IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_PDMA1);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_PDMA1IEN_Msk, SCU_SVIEN1_PDMA1IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_PDMA1);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_PDMA1IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_USBH0IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_USBH0);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_USBH0IEN_Msk, SCU_SVIEN1_USBH0IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_USBH0);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_USBH0IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_HSUSBHIEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_HSUSBH);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_HSUSBHIEN_Msk, SCU_SVIEN1_HSUSBHIEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_HSUSBH);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_HSUSBHIEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_HSUSBDIEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_HSUSBD);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_HSUSBDIEN_Msk, SCU_SVIEN1_HSUSBDIEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_HSUSBD);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_HSUSBDIEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_SDH0IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_SDH0);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_SDH0IEN_Msk, SCU_SVIEN1_SDH0IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_SDH0);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_SDH0IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_SDH1IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_SDH1);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_SDH1IEN_Msk, SCU_SVIEN1_SDH1IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_SDH1);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_SDH1IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_EMACIEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_EMAC);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_EMACIEN_Msk, SCU_SVIEN1_EMACIEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_EMAC);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_EMACIEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_CRYPTOIEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_CRYPTO);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_CRYPTOIEN_Msk, SCU_SVIEN1_CRYPTOIEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_CRYPTO);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_CRYPTOIEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_CRCIEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_CRC);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_CRCIEN_Msk, SCU_SVIEN1_CRCIEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_CRC);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_CRCIEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_LPPDMAIEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_LPPDMA);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_LPPDMAIEN_Msk, SCU_SVIEN1_LPPDMAIEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_LPPDMA);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_LPPDMAIEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_CCAPIEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_CCAP);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_CCAPIEN_Msk, SCU_SVIEN1_CCAPIEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_CCAP);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_CCAPIEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_NPUIF1IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_NPUIF1);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_NPUIF1IEN_Msk, SCU_SVIEN1_NPUIF1IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_NPUIF1);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_NPUIF1IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_NPUIF0IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_NPUIF0);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_NPUIF0IEN_Msk, SCU_SVIEN1_NPUIF0IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_NPUIF0);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_NPUIF0IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_SPIM0IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_SPIM0);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_SPIM0IEN_Msk, SCU_SVIEN1_SPIM0IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_SPIM0);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_SPIM0IEN_Msk, 0);

    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_SPIM1IEN_Msk, 0);
    SCU_ENABLE_INT(eSCU_INT_IDX_SPIM1);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_SPIM1IEN_Msk, SCU_SVIEN1_SPIM1IEN_Msk);
    SCU_DISABLE_INT(eSCU_INT_IDX_SPIM1);
    CU_ASSERT_EQUAL(SCU->SVIEN1 & SCU_SVIEN1_SPIM1IEN_Msk, 0);
}

void Func_SCU_Test_SVINTSTSx(void)
{
    CU_ASSERT_EQUAL(SCU_GET_INT_FLAG(eSCU_INT_IDX_APB0), 0);
    inp32(UART0_NS);
    __DSB();
    SCU_CLR_INT_FLAG(eSCU_INT_IDX_APB0);
    CU_ASSERT_EQUAL(SCU_GET_INT_FLAG(eSCU_INT_IDX_APB0), 0);

    SCU->SVINTSTS0 = -1;
    CU_ASSERT_EQUAL(SCU_GET_INT_FLAG(eSCU_INT_IDX_APB1), 0);
    SCU_CLR_INT_FLAG(eSCU_INT_IDX_APB1);
    CU_ASSERT_EQUAL(SCU_GET_INT_FLAG(eSCU_INT_IDX_APB1), 0);

    SCU->SVINTSTS0 = -1;
    CU_ASSERT_EQUAL(SCU_GET_INT_FLAG(eSCU_INT_IDX_APB2), 0);
    SCU_CLR_INT_FLAG(eSCU_INT_IDX_APB2);
    CU_ASSERT_EQUAL(SCU_GET_INT_FLAG(eSCU_INT_IDX_APB2), 0);

    SCU->SVINTSTS0 = -1;
    CU_ASSERT_EQUAL(SCU_GET_INT_FLAG(eSCU_INT_IDX_APB3), 0);
    SCU_CLR_INT_FLAG(eSCU_INT_IDX_APB3);
    CU_ASSERT_EQUAL(SCU_GET_INT_FLAG(eSCU_INT_IDX_APB3), 0);

    SCU->SVINTSTS0 = -1;
    CU_ASSERT_EQUAL(SCU_GET_INT_FLAG(eSCU_INT_IDX_APB4), 0);
    SCU_CLR_INT_FLAG(eSCU_INT_IDX_APB4);
    CU_ASSERT_EQUAL(SCU_GET_INT_FLAG(eSCU_INT_IDX_APB4), 0);

    SCU->SVINTSTS0 = -1;
    CU_ASSERT_EQUAL(SCU_GET_INT_FLAG(eSCU_INT_IDX_APB5), 0);
    SCU_CLR_INT_FLAG(eSCU_INT_IDX_APB5);
    CU_ASSERT_EQUAL(SCU_GET_INT_FLAG(eSCU_INT_IDX_APB5), 0);
}

void Func_SCU_NSMConfig(void)
{
    int32_t i;

    for (i = 0; i < 256; i++)
    {
        SCU_NSMConfig(i, i);
        CU_ASSERT_EQUAL((SCU->NSMCTL & 0xFF), i);
        CU_ASSERT_EQUAL((SCU->NSMCTL & SCU_NSMCTL_NSMIEN_Msk),  SCU_NSMCTL_NSMIEN_Msk);
        CU_ASSERT_EQUAL((SCU->NSMCTL & SCU_NSMCTL_AUTORLD_Msk), SCU_NSMCTL_AUTORLD_Msk);
        CU_ASSERT_EQUAL((SCU->NSMCTL & SCU_NSMCTL_TMRMOD_Msk),  0);
        CU_ASSERT_EQUAL(SCU->NSMLOAD, i);
    }

    SCU_NSMConfig(0xFFFFFF, 0xFF);
    CU_ASSERT_EQUAL((SCU->NSMCTL & 0xFF), 0xFF);
    CU_ASSERT_EQUAL(SCU->NSMLOAD, 0xFFFFFF);
}

void Func_SCU_TimerConfig(void)
{
    int32_t i;

    for (i = 0; i < 256; i++)
    {
        SCU_TimerConfig(i, i);
        CU_ASSERT_EQUAL((SCU->NSMCTL & 0xFF), i);
        CU_ASSERT_EQUAL((SCU->NSMCTL & SCU_NSMCTL_NSMIEN_Msk),  SCU_NSMCTL_NSMIEN_Msk);
        CU_ASSERT_EQUAL((SCU->NSMCTL & SCU_NSMCTL_AUTORLD_Msk), SCU_NSMCTL_AUTORLD_Msk);
        CU_ASSERT_EQUAL((SCU->NSMCTL & SCU_NSMCTL_TMRMOD_Msk),  SCU_NSMCTL_TMRMOD_Msk);
        CU_ASSERT_EQUAL(SCU->NSMLOAD, i);
    }

    SCU_TimerConfig(0xFFFFFF, 0xFF);
    CU_ASSERT_EQUAL((SCU->NSMCTL & 0xFF), 0xFF);
    CU_ASSERT_EQUAL(SCU->NSMLOAD, 0xFFFFFF);
}

void Func_SCU_NSM_IDLE_DBG(void)
{
    SCU_NSM_IDLE_ON(0);
    CU_ASSERT_EQUAL(SCU->NSMCTL & SCU_NSMCTL_IDLEON_Msk, 0);

    SCU_NSM_IDLE_ON(1);
    CU_ASSERT_EQUAL(SCU->NSMCTL & SCU_NSMCTL_IDLEON_Msk, SCU_NSMCTL_IDLEON_Msk);

    SCU_NSM_DBG_ON(0);
    CU_ASSERT_EQUAL(SCU->NSMCTL & SCU_NSMCTL_DBGON_Msk, 0);

    SCU_NSM_DBG_ON(1);
    CU_ASSERT_EQUAL(SCU->NSMCTL & SCU_NSMCTL_DBGON_Msk, SCU_NSMCTL_DBGON_Msk);
}

CU_SuiteInfo SCU_Suites[] =
{
    { "SCU Macro Test", SCU_Test_Init, SCU_Test_Clean, NULL, NULL, SCU_MacroTest },
    { "SCU Func  Test", SCU_Test_Init, SCU_Test_Clean, NULL, NULL, SCU_FuncTest  },
    CU_SUITE_INFO_NULL
};

CU_TestInfo  SCU_MacroTest[] =
{
    { "DxPNSy    Test",     Func_SCU_Test_DxPNSy    },
    { "IONSx     Test",     Func_SCU_Test_IONSx     },
    { "SVIENx    Test",     Func_SCU_Test_SVIENx    },
    { "SVINTSTSx Test",     Func_SCU_Test_SVINTSTSx },
    { "NSM Idle/Dbg Test",  Func_SCU_NSM_IDLE_DBG   },
    { "Const",              Func_SCU_Test_Const     },
    CU_TEST_INFO_NULL
};

CU_TestInfo  SCU_FuncTest[] =
{
    { "NSMConfig Test",   Func_SCU_NSMConfig   },
    { "TimerConfig Test", Func_SCU_TimerConfig },
    CU_TEST_INFO_NULL
};

/*** (C) COPYRIGHT 2023 Nuvoton Technology Corp. ***/
