#ifndef _M468_PIN_CONFIG_H_
#define _M468_PIN_CONFIG_H_

#include <stdint.h>
#include "USPI_CommonFunc.h"

//------------------------------------------------------------------------------
// SPI PIN init define
//------------------------------------------------------------------------------
#define SPI0_MOSI_PIN_INIT                   SPI0_MOSI_PIN
#define SPI0_MISO_PIN_INIT                   SPI0_MISO_PIN
#define SPI0_CLK_PIN_INIT                    SPI0_CLK_PIN
#define SPI0_CSS_PIN_INIT                    SPI0_CSS_PIN
#define SPI0_MFOS_PIN_INIT                   SPI0_MFOS_PIN

#define SPI0_MOSI_PIN  SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD0MFP_Msk)) | SPI0_MOSI_PD0
#define SPI0_MISO_PIN  SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD1MFP_Msk)) | SPI0_MISO_PD1
#define SPI0_CLK_PIN   SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD2MFP_Msk)) | SPI0_CLK_PD2
#define SPI0_CSS_PIN   SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD3MFP_Msk)) | SPI0_SS_PD3
#define SPI0_MFOS_PIN  (SYS->GPD_MFOS |= 0x3)

//------------------------------------------------------------------------------
// CLKO PIN init define
//------------------------------------------------------------------------------
#define USPI_CLKO_PIN_INIT                                                                   \
    SYS->GPC_MFP3 = (SYS->GPC_MFP3 & ~SYS_GPC_MFP3_PC13MFP_Msk) | SYS_GPC_MFP3_PC13MFP_CLKO; \
    printf("Please Check CLKO PC13\n")

//------------------------------------------------------------------------------
// USPI0 PIN init define
//------------------------------------------------------------------------------
#define USPI0_MOSI_PIN_INIT                     USPI0_MOSI_PIN
#define USPI0_MISO_PIN_INIT                     USPI0_MISO_PIN
#define USPI0_CLK_PIN_INIT                      USPI0_CLK_PIN
#define USPI0_CSS_PIN_INIT                      USPI0_CSS_PIN
#define USPI0_MFOS_PIN_INIT                     USPI0_MFOS_PIN
#define USPI0_CLK_TO_GPIO_PIN_INIT              USPI0_CLK_TO_GPIO_PIN

#if (USPI0_PIN_OUT_GROUP == 0)
    #define USPI0_MOSI_PIN SYS->GPA_MFP2 = (SYS->GPA_MFP2 & (~SYS_GPA_MFP2_PA10MFP_Msk)) | SYS_GPA_MFP2_PA10MFP_USCI0_DAT0
    #define USPI0_MISO_PIN SYS->GPA_MFP2 = (SYS->GPA_MFP2 & (~SYS_GPA_MFP2_PA9MFP_Msk)) | SYS_GPA_MFP2_PA9MFP_USCI0_DAT1
    #define USPI0_CLK_PIN  SYS->GPA_MFP2 = (SYS->GPA_MFP2 & (~SYS_GPA_MFP2_PA11MFP_Msk))  | SYS_GPA_MFP2_PA11MFP_USCI0_CLK
    #define USPI0_CSS_PIN  SYS->GPC_MFP3 = (SYS->GPC_MFP3 & (~SYS_GPC_MFP3_PC13MFP_Msk)) | SYS_GPC_MFP3_PC13MFP_USCI0_CTL0
    #define USPI0_MFOS_PIN SYS->GPA_MFOS |= BIT10 | BIT9
    #define USPI0_CLK_TO_GPIO_PIN (uint32_t *)((GPIO_PIN_DATA_BASE + (0x40 * 0)) + (11 << 2))

#elif (USPI0_PIN_OUT_GROUP == 1)
    #define USPI0_MOSI_PIN SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD1MFP_Msk)) | SYS_GPD_MFP0_PD1MFP_USCI0_DAT0
    #define USPI0_MISO_PIN SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD2MFP_Msk)) | SYS_GPD_MFP0_PD2MFP_USCI0_DAT1
    #define USPI0_CLK_PIN  SYS->GPD_MFP0 = (SYS->GPD_MFP0 & (~SYS_GPD_MFP0_PD0MFP_Msk)) | SYS_GPD_MFP0_PD0MFP_USCI0_CLK
    #define USPI0_CSS_PIN  SYS->GPD_MFP1 = (SYS->GPD_MFP1 & (~SYS_GPD_MFP1_PD4MFP_Msk)) | SYS_GPD_MFP1_PD4MFP_USCI0_CTL0
    #define USPI0_MFOS_PIN SYS->GPD_MFOS |= BIT1 | BIT2
    #define USPI0_CLK_TO_GPIO_PIN (uint32_t *)((GPIO_PIN_DATA_BASE + (0x40 * 3)) + (0 << 2))

#elif (USPI0_PIN_OUT_GROUP == 2)
    #define USPI0_MOSI_PIN SYS->GPE_MFP0 = (SYS->GPE_MFP0 & (~SYS_GPE_MFP0_PE3MFP_Msk)) | SYS_GPE_MFP0_PE3MFP_USCI0_DAT0
    #define USPI0_MISO_PIN SYS->GPE_MFP1 = (SYS->GPE_MFP1 & (~SYS_GPE_MFP1_PE4MFP_Msk)) | SYS_GPE_MFP1_PE4MFP_USCI0_DAT1
    #define USPI0_CLK_PIN  SYS->GPE_MFP0 = (SYS->GPE_MFP0 & (~SYS_GPE_MFP0_PE2MFP_Msk)) | SYS_GPE_MFP0_PE2MFP_USCI0_CLK
    #define USPI0_CSS_PIN  SYS->GPE_MFP1 = (SYS->GPE_MFP1 & (~SYS_GPE_MFP1_PE6MFP_Msk)) | SYS_GPE_MFP1_PE6MFP_USCI0_CTL0
    #define USPI0_MFOS_PIN SYS->GPE_MFOS |= BIT3 | BIT4
    #define USPI0_CLK_TO_GPIO_PIN (uint32_t *)((GPIO_PIN_DATA_BASE + (0x40 * 4)) + (2 << 2))

#elif (USPI0_PIN_OUT_GROUP == 3)
    #define USPI0_MOSI_PIN SYS->GPB_MFP3 = (SYS->GPB_MFP3 & (~SYS_GPB_MFP3_PB13MFP_Msk)) | SYS_GPB_MFP3_PB13MFP_USCI0_DAT0
    #define USPI0_MISO_PIN SYS->GPB_MFP3 = (SYS->GPB_MFP3 & (~SYS_GPB_MFP3_PB14MFP_Msk)) | SYS_GPB_MFP3_PB14MFP_USCI0_DAT1
    #define USPI0_CLK_PIN  SYS->GPB_MFP3 = (SYS->GPB_MFP3 & (~SYS_GPB_MFP3_PB12MFP_Msk)) | SYS_GPB_MFP3_PB12MFP_USCI0_CLK
    #define USPI0_CSS_PIN  SYS->GPC_MFP3 = (SYS->GPC_MFP3 & (~SYS_GPC_MFP3_PC13MFP_Msk)) | SYS_GPC_MFP3_PC13MFP_USCI0_CTL0
    #define USPI0_MFOS_PIN SYS->GPB_MFOS |= BIT13 | BIT14
    #define USPI0_CLK_TO_GPIO_PIN (uint32_t *)((GPIO_PIN_DATA_BASE + (0x40 * 1)) + (12 << 2))

#elif (USPI0_PIN_OUT_GROUP == 4)
    #define USPI0_MOSI_PIN SYS->GPB_MFP3 = (SYS->GPB_MFP3 & (~SYS_GPB_MFP3_PB13MFP_Msk)) | SYS_GPB_MFP3_PB13MFP_USCI0_DAT0
    #define USPI0_MISO_PIN SYS->GPB_MFP3 = (SYS->GPB_MFP3 & (~SYS_GPB_MFP3_PB14MFP_Msk)) | SYS_GPB_MFP3_PB14MFP_USCI0_DAT1
    #define USPI0_CLK_PIN  SYS->GPB_MFP3 = (SYS->GPB_MFP3 & (~SYS_GPB_MFP3_PB12MFP_Msk)) | SYS_GPB_MFP3_PB12MFP_USCI0_CLK
    #define USPI0_CSS_PIN  SYS->GPC_MFP3 = (SYS->GPC_MFP3 & (~SYS_GPC_MFP3_PC13MFP_Msk)) | SYS_GPC_MFP3_PC14MFP_USCI0_CTL0
    #define USPI0_MFOS_PIN SYS->GPB_MFOS |= BIT13 | BIT14
    #define USPI0_CLK_TO_GPIO_PIN (uint32_t *)((GPIO_PIN_DATA_BASE + (0x40 * 1)) + (12 << 2))

#endif //USPI0_PIN_OUT_GROUP

//------------------------------------------------------------------------------
// USPI1 PIN init define
//------------------------------------------------------------------------------
#define USPI1_MOSI_PIN_INIT                     USPI1_MOSI_PIN
#define USPI1_MISO_PIN_INIT                     USPI1_MISO_PIN
#define USPI1_CLK_PIN_INIT                      USPI1_CLK_PIN
#define USPI1_CSS_PIN_INIT                      USPI1_CSS_PIN
#define USPI1_MFOS_PIN_INIT                     USPI1_MFOS_PIN
#define USPI1_CLK_TO_GPIO_PIN_INIT              USPI1_CLK_TO_GPIO_PIN

#if (USPI1_PIN_OUT_GROUP == 0)
    #define USPI1_MOSI_PIN SYS->GPE_MFPH |= (SYS->GPE_MFPH & ~SYS_GPE_MFPH_PE10MFP_Msk) | SYS_GPE_MFPH_PE10MFP_USCI1_DAT0
    #define USPI1_MISO_PIN SYS->GPE_MFPH |= (SYS->GPE_MFPH & ~SYS_GPE_MFPH_PE11MFP_Msk) | SYS_GPE_MFPH_PE11MFP_USCI1_DAT1
    #define USPI1_CLK_PIN  SYS->GPE_MFPH |= (SYS->GPE_MFPH & ~SYS_GPE_MFPH_PE12MFP_Msk) | SYS_GPE_MFPH_PE12MFP_USCI1_CLK
    #define USPI1_CSS_PIN  SYS->GPE_MFPH |= (SYS->GPE_MFPH & ~SYS_GPE_MFPH_PE9MFP_Msk) | SYS_GPE_MFPH_PE9MFP_USCI1_CTL0
    #define USPI1_MFOS_PIN SYS->GPE_MFOS |= BIT10 | BIT11
    #define USPI1_CLK_TO_GPIO_PIN (uint32_t *)((GPIO_PIN_DATA_BASE + (0x40 * 5)) + (12 << 2))

#elif (USPI1_PIN_OUT_GROUP == 1)
    #define USPI1_MOSI_PIN SYS->GPB_MFPL |= (SYS->GPB_MFPL & ~SYS_GPB_MFPL_PB2MFP_Msk) | SYS_GPB_MFPL_PB2MFP_USCI1_DAT0
    #define USPI1_MISO_PIN SYS->GPB_MFPL |= (SYS->GPB_MFPL & ~SYS_GPB_MFPL_PB3MFP_Msk) | SYS_GPB_MFPL_PB3MFP_USCI1_DAT1
    #define USPI1_CLK_PIN  SYS->GPB_MFPL |= (SYS->GPB_MFPL & ~SYS_GPB_MFPL_PB1MFP_Msk) | SYS_GPB_MFPL_PB1MFP_USCI1_CLK
    #define USPI1_CSS_PIN  SYS->GPB_MFPL |= (SYS->GPB_MFPL & ~SYS_GPB_MFPL_PB5MFP_Msk) | SYS_GPB_MFPL_PB5MFP_USCI1_CTL0
    #define USPI1_MFOS_PIN SYS->GPB_MFOS |= BIT2 | BIT3
    #define USPI1_CLK_TO_GPIO_PIN (uint32_t *)((GPIO_PIN_DATA_BASE + (0x40 * 1)) + (1 << 2))

#elif (USPI1_PIN_OUT_GROUP == 2)
    #define USPI1_MOSI_PIN //SYS->GPD_MFPL |= (SYS->GPD_MFPL & ~SYS_GPD_MFPL_PD5MFP_Msk) | SYS_GPD_MFPL_PD5MFP_USCI1_DAT0
    #define USPI1_MISO_PIN //SYS->GPD_MFPL |= (SYS->GPD_MFPL & ~SYS_GPD_MFPL_PD6MFP_Msk) | SYS_GPD_MFPL_PD6MFP_USCI1_DAT1
    #define USPI1_CLK_PIN  //SYS->GPD_MFPL |= (SYS->GPD_MFPL & ~SYS_GPD_MFPL_PD7MFP_Msk) | SYS_GPD_MFPL_PD7MFP_USCI1_CLK
    #define USPI1_CSS_PIN  //SYS->GPD_MFPL |= (SYS->GPD_MFPL & ~SYS_GPD_MFPL_PD3MFP_Msk) | SYS_GPD_MFPL_PD3MFP_USCI1_CTL0
    #define USPI1_MFOS_PIN //SYS->GPD_MFOS |= BIT5 | BIT6
    #define USPI1_CLK_TO_GPIO_PIN (uint32_t *)((GPIO_PIN_DATA_BASE + (0x40 * 3)) + (7 << 2))

#elif (USPI1_PIN_OUT_GROUP == 3)
    #define USPI1_MOSI_PIN SYS->GPB_MFPL |= (SYS->GPB_MFPL & ~SYS_GPB_MFPL_PB7MFP_Msk) | SYS_GPB_MFPL_PB7MFP_USCI1_DAT0
    #define USPI1_MISO_PIN SYS->GPB_MFPL |= (SYS->GPB_MFPL & ~SYS_GPB_MFPL_PB6MFP_Msk) | SYS_GPB_MFPL_PB6MFP_USCI1_DAT1
    #define USPI1_CLK_PIN  SYS->GPB_MFPH |= (SYS->GPB_MFPH & ~SYS_GPB_MFPH_PB8MFP_Msk) | SYS_GPB_MFPH_PB8MFP_USCI1_CLK
    #define USPI1_CSS_PIN  SYS->GPB_MFPH |= (SYS->GPB_MFPH & ~SYS_GPB_MFPH_PB10MFP_Msk) | SYS_GPB_MFPH_PB10MFP_USCI1_CTL0
    #define USPI1_MFOS_PIN SYS->GPB_MFOS |= BIT7 | BIT6
    #define USPI1_CLK_TO_GPIO_PIN (uint32_t *)((GPIO_PIN_DATA_BASE + (0x40 * 1)) + (8 << 2))

#endif //USPI1_PIN_OUT_GROUP

//------------------------------------------------------------------------------
// USPI1 PIN init define
//------------------------------------------------------------------------------
#define USPI2_MOSI_PIN_INIT                     USPI2_MOSI_PIN
#define USPI2_MISO_PIN_INIT                     USPI2_MISO_PIN
#define USPI2_CLK_PIN_INIT                      USPI2_CLK_PIN
#define USPI2_CSS_PIN_INIT                      USPI2_CSS_PIN
#define USPI2_MFOS_PIN_INIT                     USPI2_MFOS_PIN

#if (USPI2_PIN_OUT_GROUP == 0)
    #define USPI2_MOSI_PIN //SYS->GPA_MFPL |= (SYS->GPA_MFPL & ~SYS_GPA_MFPL_PA1MFP_Msk) | SYS_GPA_MFPL_PA1MFP_USCI2_DAT0
    #define USPI2_MISO_PIN //SYS->GPA_MFPL |= (SYS->GPA_MFPL & ~SYS_GPA_MFPL_PA0MFP_Msk) | SYS_GPA_MFPL_PA0MFP_USCI2_DAT1
    #define USPI2_CLK_PIN  //SYS->GPA_MFPL |= (SYS->GPA_MFPL & ~SYS_GPA_MFPL_PA2MFP_Msk) | SYS_GPA_MFPL_PA2MFP_USCI2_CLK
    #define USPI2_CSS_PIN  //SYS->GPA_MFPL |= (SYS->GPA_MFPL & ~SYS_GPA_MFPL_PA3MFP_Msk) | SYS_GPA_MFPL_PA3MFP_USCI2_CTL0
    #define USPI2_MFOS_PIN //SYS->GPA_MFOS |= BIT1 | BIT0

#elif (USPI2_PIN_OUT_GROUP == 1)
    #define USPI2_MOSI_PIN SYS->GPC_MFPL |= (SYS->GPC_MFPL & ~SYS_GPC_MFPL_PC1MFP_Msk) | SYS_GPC_MFPL_PC1MFP_USCI2_DAT0
    #define USPI2_MISO_PIN SYS->GPC_MFPL |= (SYS->GPC_MFPL & ~SYS_GPC_MFPL_PC0MFP_Msk) | SYS_GPC_MFPL_PC0MFP_USCI2_DAT1
    #define USPI2_CLK_PIN  SYS->GPC_MFPL |= (SYS->GPC_MFPL & ~SYS_GPC_MFPL_PC2MFP_Msk) | SYS_GPC_MFPL_PC2MFP_USCI2_CLK
    #define USPI2_CSS_PIN  SYS->GPC_MFPL |= (SYS->GPC_MFPL & ~SYS_GPC_MFPL_PC3MFP_Msk) | SYS_GPC_MFPL_PC3MFP_USCI2_CTL0
    #define USPI2_MFOS_PIN SYS->GPC_MFOS |= BIT1 | BIT0

#elif (USPI2_PIN_OUT_GROUP == 2)
    #define USPI2_MOSI_PIN SYS->GPA_MFPH |= (SYS->GPA_MFPH & ~SYS_GPA_MFPH_PA13MFP_Msk) | SYS_GPA_MFPH_PA13MFP_USCI2_DAT0;
    #define USPI2_MISO_PIN SYS->GPA_MFPH |= (SYS->GPA_MFPH & ~SYS_GPA_MFPH_PA12MFP_Msk) | SYS_GPA_MFPH_PA12MFP_USCI2_DAT1
    #define USPI2_CLK_PIN  SYS->GPA_MFPH |= (SYS->GPA_MFPH & ~SYS_GPA_MFPH_PA14MFP_Msk) | SYS_GPA_MFPH_PA14MFP_USCI2_CLK
    #define USPI2_CSS_PIN  SYS->GPD_MFPH |= (SYS->GPD_MFPH & ~SYS_GPD_MFPH_PD13MFP_Msk) | SYS_GPD_MFPH_PD13MFP_USCI2_CTL0
    #define USPI2_MFOS_PIN SYS->GPA_MFOS |= BIT13 | BIT12

#elif (USPI2_PIN_OUT_GROUP == 3)
    #define USPI2_MOSI_PIN SYS->GPE_MFPL |= (SYS->GPE_MFPL & ~SYS_GPE_MFPL_PE0MFP_Msk) | SYS_GPE_MFPL_PE0MFP_USCI2_DAT0;
    #define USPI2_MISO_PIN SYS->GPE_MFPL |= (SYS->GPE_MFPL & ~SYS_GPE_MFPL_PE1MFP_Msk) | SYS_GPE_MFPL_PE1MFP_USCI2_DAT1
    #define USPI2_CLK_PIN  SYS->GPC_MFPH |= (SYS->GPC_MFPH & ~SYS_GPC_MFPH_PC14MFP_Msk) | SYS_GPC_MFPH_PC14MFP_USCI2_CLK
    #define USPI2_CSS_PIN  SYS->GPE_MFPL |= (SYS->GPE_MFPL & ~SYS_GPE_MFPL_PE2MFP_Msk) | SYS_GPE_MFPL_PE2MFP_USCI2_CTL0
    #define USPI2_MFOS_PIN SYS->GPE_MFOS |= BIT0 | BIT1

#endif //USPI2_PIN_OUT_GROUP

#endif /* _M468_PIN_CONFIG_H_ */
