#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "NuMicro.h"
#include "CUnit.h"
#include "Console.h"
#include "clk_cunit.h"

int CLK_Test_Init(void)
{
    return 0;
}
int CLK_Test_Clean(void)
{
    return 0;
}

const uint64_t au64ModuleClkEnSel[] =
{
    ACMP01_MODULE,  (uint32_t) &CLK->ACMPCTL,   CLK_ACMPCTL_ACMP01CKEN_Msk,
    ACMP23_MODULE,  (uint32_t) &CLK->ACMPCTL,   CLK_ACMPCTL_ACMP23CKEN_Msk,
    AWF0_MODULE,    (uint32_t) &CLK->AWFCTL,    CLK_AWFCTL_AWF0CKEN_Msk,
    BPWM0_MODULE,   (uint32_t) &CLK->BPWMCTL,   CLK_BPWMCTL_BPWM0CKEN_Msk,
    BPWM1_MODULE,   (uint32_t) &CLK->BPWMCTL,   CLK_BPWMCTL_BPWM1CKEN_Msk,
    CANFD0_MODULE,  (uint32_t) &CLK->CANFDCTL,  CLK_CANFDCTL_CANFD0CKEN_Msk,
    CANFD1_MODULE,  (uint32_t) &CLK->CANFDCTL,  CLK_CANFDCTL_CANFD1CKEN_Msk,
    CCAP0_MODULE,   (uint32_t) &CLK->CCAPCTL,   CLK_CCAPCTL_CCAP0CKEN_Msk,
    CRC0_MODULE,    (uint32_t) &CLK->CRCCTL,    CLK_CRCCTL_CRC0CKEN_Msk,
    CRYPTO0_MODULE, (uint32_t) &CLK->CRYPTOCTL, CLK_CRYPTOCTL_CRYPTO0CKEN_Msk,
    DAC01_MODULE,   (uint32_t) &CLK->DACCTL,    CLK_DACCTL_DAC01CKEN_Msk,
    DMIC0_MODULE,   (uint32_t) &CLK->DMICCTL,   CLK_DMICCTL_DMIC0CKEN_Msk,
    EADC0_MODULE,   (uint32_t) &CLK->EADCCTL,   CLK_EADCCTL_EADC0CKEN_Msk,
    EADC1_MODULE,   (uint32_t) &CLK->EADCCTL,   CLK_EADCCTL_EADC1CKEN_Msk,
    EBI0_MODULE,    (uint32_t) &CLK->EBICTL,    CLK_EBICTL_EBI0CKEN_Msk,
    ECAP0_MODULE,   (uint32_t) &CLK->ECAPCTL,   CLK_ECAPCTL_ECAP0CKEN_Msk,
    ECAP1_MODULE,   (uint32_t) &CLK->ECAPCTL,   CLK_ECAPCTL_ECAP1CKEN_Msk,
    ECAP2_MODULE,   (uint32_t) &CLK->ECAPCTL,   CLK_ECAPCTL_ECAP2CKEN_Msk,
    ECAP3_MODULE,   (uint32_t) &CLK->ECAPCTL,   CLK_ECAPCTL_ECAP3CKEN_Msk,
    EMAC0_MODULE,   (uint32_t) &CLK->EMACCTL,   CLK_EMACCTL_EMAC0CKEN_Msk,
    EPWM0_MODULE,   (uint32_t) &CLK->EPWMCTL,   CLK_EPWMCTL_EPWM0CKEN_Msk,
    EPWM1_MODULE,   (uint32_t) &CLK->EPWMCTL,   CLK_EPWMCTL_EPWM1CKEN_Msk,
    EQEI0_MODULE,   (uint32_t) &CLK->EQEICTL,   CLK_EQEICTL_EQEI0CKEN_Msk,
    EQEI1_MODULE,   (uint32_t) &CLK->EQEICTL,   CLK_EQEICTL_EQEI1CKEN_Msk,
    EQEI2_MODULE,   (uint32_t) &CLK->EQEICTL,   CLK_EQEICTL_EQEI2CKEN_Msk,
    EQEI3_MODULE,   (uint32_t) &CLK->EQEICTL,   CLK_EQEICTL_EQEI3CKEN_Msk,
    FMC0_MODULE,    (uint32_t) &CLK->FMCCTL,    CLK_FMCCTL_FMC0CKEN_Msk,
    ISP0_MODULE,    (uint32_t) &CLK->FMCCTL,    CLK_FMCCTL_ISP0CKEN_Msk,
    GDMA0_MODULE,   (uint32_t) &CLK->GDMACTL,   CLK_GDMACTL_GDMA0CKEN_Msk,
    GPIOA_MODULE,   (uint32_t) &CLK->GPIOCTL,   CLK_GPIOCTL_GPIOACKEN_Msk,
    GPIOB_MODULE,   (uint32_t) &CLK->GPIOCTL,   CLK_GPIOCTL_GPIOBCKEN_Msk,    
    GPIOC_MODULE,   (uint32_t) &CLK->GPIOCTL,   CLK_GPIOCTL_GPIOCCKEN_Msk,
    GPIOD_MODULE,   (uint32_t) &CLK->GPIOCTL,   CLK_GPIOCTL_GPIODCKEN_Msk,
    GPIOE_MODULE,   (uint32_t) &CLK->GPIOCTL,   CLK_GPIOCTL_GPIOECKEN_Msk,
    GPIOF_MODULE,   (uint32_t) &CLK->GPIOCTL,   CLK_GPIOCTL_GPIOFCKEN_Msk,
    GPIOG_MODULE,   (uint32_t) &CLK->GPIOCTL,   CLK_GPIOCTL_GPIOGCKEN_Msk,
    GPIOH_MODULE,   (uint32_t) &CLK->GPIOCTL,   CLK_GPIOCTL_GPIOHCKEN_Msk,
    GPIOI_MODULE,   (uint32_t) &CLK->GPIOCTL,   CLK_GPIOCTL_GPIOICKEN_Msk,
    GPIOJ_MODULE,   (uint32_t) &CLK->GPIOCTL,   CLK_GPIOCTL_GPIOJCKEN_Msk,
    HSOTG0_MODULE,  (uint32_t) &CLK->HSOTGCTL,  CLK_HSOTGCTL_HSOTG0CKEN_Msk,
    HSUSBD0_MODULE, (uint32_t) &CLK->HSUSBDCTL, CLK_HSUSBDCTL_HSUSBD0CKEN_Msk,
    HSUSBH0_MODULE, (uint32_t) &CLK->HSUSBHCTL, CLK_HSUSBHCTL_HSUSBH0CKEN_Msk,   
    I2C0_MODULE,    (uint32_t) &CLK->I2CCTL,    CLK_I2CCTL_I2C0CKEN_Msk,    
    I2C1_MODULE,    (uint32_t) &CLK->I2CCTL,    CLK_I2CCTL_I2C1CKEN_Msk,
    I2C2_MODULE,    (uint32_t) &CLK->I2CCTL,    CLK_I2CCTL_I2C2CKEN_Msk,
    I2C3_MODULE,    (uint32_t) &CLK->I2CCTL,    CLK_I2CCTL_I2C3CKEN_Msk,
    I2S0_MODULE,    (uint32_t) &CLK->I2SCTL,    CLK_I2SCTL_I2S0CKEN_Msk,
    I2S1_MODULE,    (uint32_t) &CLK->I2SCTL,    CLK_I2SCTL_I2S1CKEN_Msk,
    I3C0_MODULE,    (uint32_t) &CLK->I3CCTL,    CLK_I3CCTL_I3C0CKEN_Msk,
    KDF0_MODULE,    (uint32_t) &CLK->KDFCTL,    CLK_KDFCTL_KDF0CKEN_Msk,
    KPI0_MODULE,    (uint32_t) &CLK->KPICTL,    CLK_KPICTL_KPI0CKEN_Msk,
    KS0_MODULE,     (uint32_t) &CLK->KSCTL,     CLK_KSCTL_KS0CKEN_Msk,
    LPADC0_MODULE,  (uint32_t) &CLK->LPADCCTL,  CLK_LPADCCTL_LPADC0CKEN_Msk,
    LPPDMA0_MODULE, (uint32_t) &CLK->LPPDMACTL, CLK_LPPDMACTL_LPPDMA0CKEN_Msk,
    LPGPIO0_MODULE, (uint32_t) &CLK->LPGPIOCTL, CLK_LPGPIOCTL_LPGPIO0CKEN_Msk,    
    LPI2C0_MODULE,  (uint32_t) &CLK->LPI2CCTL,  CLK_LPI2CCTL_LPI2C0CKEN_Msk,
    LPSPI0_MODULE,  (uint32_t) &CLK->LPSPICTL,  CLK_LPSPICTL_LPSPI0CKEN_Msk,
    LPSRAM0_MODULE, (uint32_t) &CLK->LPSRAMCTL, CLK_LPSRAMCTL_LPSRAM0CKEN_Msk,
    LPTMR0_MODULE,  (uint32_t) &CLK->LPTMRCTL,  CLK_LPTMRCTL_LPTMR0CKEN_Msk,
    LPTMR1_MODULE,  (uint32_t) &CLK->LPTMRCTL,  CLK_LPTMRCTL_LPTMR1CKEN_Msk,
    LPUART0_MODULE, (uint32_t) &CLK->LPUARTCTL, CLK_LPUARTCTL_LPUART0CKEN_Msk,
    NPU0_MODULE,    (uint32_t) &CLK->NPUCTL,    CLK_NPUCTL_NPU0CKEN_Msk,  
    OTFC0_MODULE,   (uint32_t) &CLK->OTFCCTL,   CLK_OTFCCTL_OTFC0CKEN_Msk,
    OTFC1_MODULE,   (uint32_t) &CLK->OTFCCTL,   CLK_OTFCCTL_OTFC1CKEN_Msk,
    OTG0_MODULE,    (uint32_t) &CLK->OTGCTL,    CLK_OTGCTL_OTG0CKEN_Msk,
    PDMA0_MODULE,   (uint32_t) &CLK->PDMACTL,   CLK_PDMACTL_PDMA0CKEN_Msk,
    PDMA1_MODULE,   (uint32_t) &CLK->PDMACTL,   CLK_PDMACTL_PDMA1CKEN_Msk,
    PSIO0_MODULE,   (uint32_t) &CLK->PSIOCTL,   CLK_PSIOCTL_PSIO0CKEN_Msk,
    QSPI0_MODULE,   (uint32_t) &CLK->QSPICTL,   CLK_QSPICTL_QSPI0CKEN_Msk,
    QSPI1_MODULE,   (uint32_t) &CLK->QSPICTL,   CLK_QSPICTL_QSPI1CKEN_Msk,
    RTC0_MODULE,    (uint32_t) &CLK->RTCCTL,    CLK_RTCCTL_RTC0CKEN_Msk,
    SC0_MODULE,     (uint32_t) &CLK->SCCTL,     CLK_SCCTL_SC0CKEN_Msk,
    SC1_MODULE,     (uint32_t) &CLK->SCCTL,     CLK_SCCTL_SC1CKEN_Msk,
    SC2_MODULE,     (uint32_t) &CLK->SCCTL,     CLK_SCCTL_SC2CKEN_Msk,
    SCU0_MODULE,    (uint32_t) &CLK->SCUCTL,    CLK_SCUCTL_SCU0CKEN_Msk,
    SDH0_MODULE,    (uint32_t) &CLK->SDHCTL,    CLK_SDHCTL_SDH0CKEN_Msk,
    SDH1_MODULE,    (uint32_t) &CLK->SDHCTL,    CLK_SDHCTL_SDH1CKEN_Msk,
    SPI0_MODULE,    (uint32_t) &CLK->SPICTL,    CLK_SPICTL_SPI0CKEN_Msk,
    SPI1_MODULE,    (uint32_t) &CLK->SPICTL,    CLK_SPICTL_SPI1CKEN_Msk,
    SPI2_MODULE,    (uint32_t) &CLK->SPICTL,    CLK_SPICTL_SPI2CKEN_Msk,
    SPI3_MODULE,    (uint32_t) &CLK->SPICTL,    CLK_SPICTL_SPI3CKEN_Msk,
    SPIM0_MODULE,   (uint32_t) &CLK->SPIMCTL,   CLK_SPIMCTL_SPIM0CKEN_Msk,
    SPIM1_MODULE,   (uint32_t) &CLK->SPIMCTL,   CLK_SPIMCTL_SPIM1CKEN_Msk,
//    SRAM0_MODULE,   (uint32_t) &CLK->SRAMCTL,   CLK_SRAMCTL_SRAM0CKEN_Msk,
//    SRAM1_MODULE,   (uint32_t) &CLK->SRAMCTL,   CLK_SRAMCTL_SRAM1CKEN_Msk,
//    SRAM2_MODULE,   (uint32_t) &CLK->SRAMCTL,   CLK_SRAMCTL_SRAM2CKEN_Msk,
//    SRAM2_MODULE,   (uint32_t) &CLK->SRAMCTL,   CLK_SRAMCTL_SRAM3CKEN_Msk,    
//    SWDH0_MODULE,   (uint32_t) &CLK->SWDHCTL,   CLK_SWDHCTL_SWDH0CKEN_Msk,
//    SWODEC0_MODULE, (uint32_t) &CLK->SWODECCTL, CLK_SWODECCTL_SWODEC0CKEN_Msk,
    ST0_MODULE,     (uint32_t) &CLK->STCTL,     CLK_STCTL_ST0CKEN_Msk,
    TAMPER0_MODULE, (uint32_t) &CLK->TAMPERCTL, CLK_TAMPERCTL_TAMPER0CKEN_Msk,
    TMR0_MODULE,    (uint32_t) &CLK->TMRCTL,    CLK_TMRCTL_TMR0CKEN_Msk,
    TMR1_MODULE,    (uint32_t) &CLK->TMRCTL,    CLK_TMRCTL_TMR1CKEN_Msk,
    TMR2_MODULE,    (uint32_t) &CLK->TMRCTL,    CLK_TMRCTL_TMR2CKEN_Msk,
    TMR3_MODULE,    (uint32_t) &CLK->TMRCTL,    CLK_TMRCTL_TMR3CKEN_Msk,
    TRNG0_MODULE,   (uint32_t) &CLK->TRNGCTL,   CLK_TRNGCTL_TRNG0CKEN_Msk,
    TTMR0_MODULE,   (uint32_t) &CLK->TTMRCTL,   CLK_TTMRCTL_TTMR0CKEN_Msk,
    TTMR1_MODULE,   (uint32_t) &CLK->TTMRCTL,   CLK_TTMRCTL_TTMR1CKEN_Msk,
    UART0_MODULE,   (uint32_t) &CLK->UARTCTL,   CLK_UARTCTL_UART0CKEN_Msk,
    UART1_MODULE,   (uint32_t) &CLK->UARTCTL,   CLK_UARTCTL_UART1CKEN_Msk,
    UART2_MODULE,   (uint32_t) &CLK->UARTCTL,   CLK_UARTCTL_UART2CKEN_Msk,
    UART3_MODULE,   (uint32_t) &CLK->UARTCTL,   CLK_UARTCTL_UART3CKEN_Msk,
    UART4_MODULE,   (uint32_t) &CLK->UARTCTL,   CLK_UARTCTL_UART4CKEN_Msk,
    UART5_MODULE,   (uint32_t) &CLK->UARTCTL,   CLK_UARTCTL_UART5CKEN_Msk,
    UART6_MODULE,   (uint32_t) &CLK->UARTCTL,   CLK_UARTCTL_UART6CKEN_Msk,
    UART7_MODULE,   (uint32_t) &CLK->UARTCTL,   CLK_UARTCTL_UART7CKEN_Msk,
    UART8_MODULE,   (uint32_t) &CLK->UARTCTL,   CLK_UARTCTL_UART8CKEN_Msk,
    UART9_MODULE,   (uint32_t) &CLK->UARTCTL,   CLK_UARTCTL_UART9CKEN_Msk,
    USBD0_MODULE,   (uint32_t) &CLK->USBDCTL,   CLK_USBDCTL_USBD0CKEN_Msk,
    USBH0_MODULE,   (uint32_t) &CLK->USBHCTL,   CLK_USBHCTL_USBH0CKEN_Msk,
    USCI0_MODULE,   (uint32_t) &CLK->USCICTL,   CLK_USCICTL_USCI0CKEN_Msk,
    UTCPD0_MODULE,  (uint32_t) &CLK->UTCPDCTL,  CLK_UTCPDCTL_UTCPD0CKEN_Msk,
    WDT0_MODULE,    (uint32_t) &CLK->WDTCTL,    CLK_WDTCTL_WDT0CKEN_Msk,
    WDT1_MODULE,    (uint32_t) &CLK->WDTCTL,    CLK_WDTCTL_WDT1CKEN_Msk,
    WWDT0_MODULE,   (uint32_t) &CLK->WWDTCTL,   CLK_WWDTCTL_WWDT0CKEN_Msk,
    WWDT1_MODULE,   (uint32_t) &CLK->WWDTCTL,   CLK_WWDTCTL_WWDT1CKEN_Msk,
};

void TestFunc_CLK_EnableModuleClock()
{
    uint16_t u16ModuleClkEnSelIdx;    //clock enable

    /* Enable all clock */
    CLK_EnableXtalRC(CLK_SRCCTL_HXTEN_Msk);
    CLK_EnableXtalRC(CLK_SRCCTL_HIRC48MEN_Msk);
    CLK_EnableXtalRC(CLK_SRCCTL_HIRCEN_Msk);
    CLK_EnableXtalRC(CLK_SRCCTL_MIRCEN_Msk);
    CLK_EnableXtalRC(CLK_SRCCTL_LIRCEN_Msk);
    CLK_EnableXtalRC(CLK_SRCCTL_LXTEN_Msk);
    CLK_WaitClockReady(CLK_STATUS_LXTSTB_Msk);
    CLK_WaitClockReady(CLK_STATUS_HXTSTB_Msk);
    CLK_WaitClockReady(CLK_STATUS_HIRC48MSTB_Msk);
    CLK_WaitClockReady(CLK_STATUS_HIRCSTB_Msk);
    CLK_WaitClockReady(CLK_STATUS_MIRCSTB_Msk);
    CLK_WaitClockReady(CLK_STATUS_LIRCSTB_Msk);
    CLK_SetSCLK(CLK_SCLKSEL_SCLKSEL_HIRC48M);    
    CLK_EnableAPLL(CLK_APLLCTL_APLLSRC_HIRC, FREQ_180MHZ, CLK_APLL0_SELECT);    
    CLK_EnableAPLL(CLK_APLLCTL_APLLSRC_HIRC, FREQ_180MHZ, CLK_APLL1_SELECT); 
    /* Switch SCLK clock source to PLL0 and divide 1 */
    CLK_SetSCLK(CLK_SCLKSEL_SCLKSEL_APLL0);
    /* Set HCLK2 divide 2 */
    CLK_SET_HCLK2DIV(2);
    /* Set both PCLK0 and PCLK1 as HCLK/2 */
    CLK_SET_PCLK0DIV(2);
    CLK_SET_PCLK1DIV(2);
    CLK_SET_PCLK2DIV(2);
    CLK_SET_PCLK3DIV(2);
    CLK_SET_PCLK4DIV(2);
    
    //wait UART print message finish
    UART_WAIT_TX_EMPTY(UART6);

    /* test loop */
    for (u16ModuleClkEnSelIdx = 0; u16ModuleClkEnSelIdx < (sizeof(au64ModuleClkEnSel) / sizeof(uint64_t)); u16ModuleClkEnSelIdx += 3)
    {
        //printf("address = 0x%08x\n",(uint32_t)(au64ModuleClkEnSel[u16ModuleClkEnSelIdx+1]));
        CLK_EnableModuleClock(au64ModuleClkEnSel[u16ModuleClkEnSelIdx]);
        CU_ASSERT((inp32(au64ModuleClkEnSel[u16ModuleClkEnSelIdx + 1]) & au64ModuleClkEnSel[u16ModuleClkEnSelIdx + 2]) == au64ModuleClkEnSel[u16ModuleClkEnSelIdx + 2]);
        CLK_DisableModuleClock(au64ModuleClkEnSel[u16ModuleClkEnSelIdx]);
        CU_ASSERT((inp32(au64ModuleClkEnSel[u16ModuleClkEnSelIdx + 1]) & au64ModuleClkEnSel[u16ModuleClkEnSelIdx + 2]) == 0);
    }

    /* Enable UART clock after test*/
    CLK_EnableModuleClock(UART6_MODULE);
    /* Others are default enable */
    CLK_EnableModuleClock(FMC0_MODULE);
    CLK_EnableModuleClock(SCU0_MODULE);
    CLK_EnableModuleClock(WDT0_MODULE);
    CLK_EnableModuleClock(WDT1_MODULE);
    CLK_EnableModuleClock(WWDT0_MODULE);
    CLK_EnableModuleClock(WWDT1_MODULE);
}

void TestFunc_CLK_GetFreq()
{
    /* Enable all clock */
    CLK_EnableXtalRC(CLK_SRCCTL_HXTEN_Msk);
    CLK_EnableXtalRC(CLK_SRCCTL_HIRC48MEN_Msk);
    CLK_EnableXtalRC(CLK_SRCCTL_HIRCEN_Msk);
    CLK_EnableXtalRC(CLK_SRCCTL_MIRCEN_Msk);
    CLK_EnableXtalRC(CLK_SRCCTL_LIRCEN_Msk);
    CLK_EnableXtalRC(CLK_SRCCTL_LXTEN_Msk);
    CLK_WaitClockReady(CLK_STATUS_LXTSTB_Msk);
    CLK_WaitClockReady(CLK_STATUS_HXTSTB_Msk);
    CLK_WaitClockReady(CLK_STATUS_HIRC48MSTB_Msk);
    CLK_WaitClockReady(CLK_STATUS_HIRCSTB_Msk);
    CLK_WaitClockReady(CLK_STATUS_MIRCSTB_Msk);
    CLK_WaitClockReady(CLK_STATUS_LIRCSTB_Msk);
    CLK_SetSCLK(CLK_SCLKSEL_SCLKSEL_HIRC48M);
    CLK_EnableAPLL(CLK_APLLCTL_APLLSRC_HIRC, FREQ_180MHZ, CLK_APLL0_SELECT);    
    CLK_EnableAPLL(CLK_APLLCTL_APLLSRC_HIRC, FREQ_180MHZ, CLK_APLL1_SELECT); 

    /* Switch SCLK clock source to PLL0 and divide 1 */
    CLK_SetSCLK(CLK_SCLKSEL_SCLKSEL_APLL0);
    /* Set HCLK2 divide 2 */
    CLK_SET_HCLK2DIV(2);
    /* Set both PCLK0 and PCLK1 as HCLK/2 */
    CLK_SET_PCLK0DIV(2);
    CLK_SET_PCLK1DIV(2);
    CLK_SET_PCLK2DIV(2);
    CLK_SET_PCLK3DIV(2);
    CLK_SET_PCLK4DIV(2);
    
    /*-----HXT Test-----*/
    CU_ASSERT(CLK_GetHXTFreq() == __HXT);

    /*-----LXT Test-----*/
    CU_ASSERT(CLK_GetLXTFreq() == __LXT);

    /*-----MIRC Test-----*/
#if 0   // TESTCHIP_ONLY not support    
    CLK_DisableMIRC();
    CU_ASSERT(CLK_GetMIRCFreq() == 0UL);
    CLK_EnableMIRC(CLK_MIRCCTL_MIRCFSEL_1MHZ);
    CU_ASSERT(CLK_GetMIRCFreq() == FREQ_1MHZ);
    CLK_EnableMIRC(CLK_MIRCCTL_MIRCFSEL_2MHZ);
    CU_ASSERT(CLK_GetMIRCFreq() == FREQ_2MHZ);    
    CLK_EnableMIRC(CLK_MIRCCTL_MIRCFSEL_4MHZ);
    CU_ASSERT(CLK_GetMIRCFreq() == FREQ_4MHZ);    
    CLK_EnableMIRC(CLK_MIRCCTL_MIRCFSEL_8MHZ);
    CU_ASSERT(CLK_GetMIRCFreq() == FREQ_8MHZ);
#else
    CU_ASSERT(CLK_GetMIRCFreq() == FREQ_1MHZ);
#endif
    /*-----APLL0 Test-----*/
    CU_ASSERT(CLK_GetAPLL0ClockFreq() == FREQ_180MHZ);

    /*-----APLL1 Test-----*/
    CU_ASSERT(CLK_GetAPLL1ClockFreq() == FREQ_180MHZ);

    /*-----SCLK Test-----*/
    CU_ASSERT(CLK_GetSCLKFreq() == FREQ_180MHZ);

    /*-----ACLK Test-----*/
    CU_ASSERT(CLK_GetACLKFreq() == FREQ_180MHZ);

    /*-----HCLK0 Test-----*/
    CU_ASSERT(CLK_GetHCLK0Freq() == FREQ_180MHZ);
  
    /*-----HCLK1 Test-----*/
    CU_ASSERT(CLK_GetHCLK1Freq() == FREQ_180MHZ);

    /*-----HCLK2 Test-----*/
    CU_ASSERT(CLK_GetHCLK2Freq() == FREQ_90MHZ);
   
    /*-----PCLK0 Test-----*/
    CU_ASSERT(CLK_GetPCLK0Freq() == FREQ_90MHZ);
    
    /*-----PCLK1 Test-----*/
    CU_ASSERT(CLK_GetPCLK1Freq() == FREQ_90MHZ);
    
    /*-----PCLK2 Test-----*/
    CU_ASSERT(CLK_GetPCLK2Freq() == FREQ_90MHZ);
    
    /*-----PCLK3 Test-----*/
    CU_ASSERT(CLK_GetPCLK3Freq() == FREQ_90MHZ);
    
    /*-----PCLK4 Test-----*/
    CU_ASSERT(CLK_GetPCLK4Freq() == FREQ_45MHZ);
    
    /*-----PCLK5 Test-----*/
    CU_ASSERT(CLK_GetPCLK5Freq() == FREQ_180MHZ);
}

void TestFunc_CLK_EnableXtalRC()
{
    /* need to disable isp so that hirc can be disabled. */
    FMC_DISABLE_ISP();

    /*-----HXT Test-----*/
    CLK_DisableXtalRC(CLK_SRCCTL_HXTEN_Msk);
    CU_ASSERT(CLK_WaitClockDisable(CLK_STATUS_HXTSTB_Msk) == 1UL);

    CLK_EnableXtalRC(CLK_SRCCTL_HXTEN_Msk);
    CU_ASSERT(CLK_WaitClockReady(CLK_STATUS_HXTSTB_Msk) == 1UL);

    /*-----LXT Test-----*/
    CLK_DisableXtalRC(CLK_SRCCTL_LXTEN_Msk);
    CU_ASSERT(CLK_WaitClockDisable(CLK_STATUS_LXTSTB_Msk) == 1UL);

    CLK_EnableXtalRC(CLK_SRCCTL_LXTEN_Msk);
    CU_ASSERT(CLK_WaitClockReady(CLK_STATUS_LXTSTB_Msk) == 1UL);

    /*-----HIRC Test-----*/
    CLK_SetSCLK(CLK_SCLKSEL_SCLKSEL_HIRC48M);
    CLK_DisableXtalRC(CLK_SRCCTL_HIRCEN_Msk);
    CU_ASSERT(CLK_WaitClockDisable(CLK_STATUS_HIRCSTB_Msk) == 1UL);

    CLK_EnableXtalRC(CLK_SRCCTL_HIRCEN_Msk);
    CU_ASSERT(CLK_WaitClockReady(CLK_STATUS_HIRCSTB_Msk) == 1UL);    
    CLK_SetBusClock(CLK_SCLKSEL_SCLKSEL_APLL0, CLK_APLLCTL_APLLSRC_HXT, FREQ_180MHZ);
    
    /*-----LIRC Test-----*/
    CLK_DisableXtalRC(CLK_SRCCTL_LIRCEN_Msk);
    CU_ASSERT(CLK_WaitClockDisable(CLK_STATUS_LIRCSTB_Msk) == 1UL);

    CLK_EnableXtalRC(CLK_SRCCTL_LIRCEN_Msk);
    CU_ASSERT(CLK_WaitClockReady(CLK_STATUS_LIRCSTB_Msk) == 1UL);    

    /*-----HIRC48 Test-----*/
    CLK_DisableXtalRC(CLK_SRCCTL_HIRC48MEN_Msk);
    CU_ASSERT(CLK_WaitClockDisable(CLK_STATUS_HIRC48MSTB_Msk) == 1UL);

    CLK_EnableXtalRC(CLK_SRCCTL_HIRC48MEN_Msk);
    CU_ASSERT(CLK_WaitClockReady(CLK_STATUS_HIRC48MSTB_Msk) == 1UL);
}

void TestFunc_CLK_EnableMIRC()
{
#if 0   // TESTCHIP_ONLY not support
    CLK_DisableMIRC();
    CU_ASSERT(CLK_WaitClockDisable(CLK_STATUS_MIRCSTB_Msk) == 1UL);
    CLK_EnableMIRC(CLK_MIRCCTL_MIRCFSEL_1MHZ);
    CU_ASSERT(CLK_WaitClockReady(CLK_STATUS_MIRCSTB_Msk) == 1UL);

    CLK_DisableMIRC();
    CU_ASSERT(CLK_WaitClockDisable(CLK_STATUS_MIRCSTB_Msk) == 1UL);    
    CLK_EnableMIRC(CLK_MIRCCTL_MIRCFSEL_2MHZ);
    CU_ASSERT(CLK_WaitClockReady(CLK_STATUS_MIRCSTB_Msk) == 1UL);

    CLK_DisableMIRC();
    CU_ASSERT(CLK_WaitClockDisable(CLK_STATUS_MIRCSTB_Msk) == 1UL);     
    CLK_EnableMIRC(CLK_MIRCCTL_MIRCFSEL_4MHZ);
    CU_ASSERT(CLK_WaitClockReady(CLK_STATUS_MIRCSTB_Msk) == 1UL);

    CLK_DisableMIRC();
    CU_ASSERT(CLK_WaitClockDisable(CLK_STATUS_MIRCSTB_Msk) == 1UL);      
    CLK_EnableMIRC(CLK_MIRCCTL_MIRCFSEL_8MHZ);
    CU_ASSERT(CLK_WaitClockReady(CLK_STATUS_MIRCSTB_Msk) == 1UL);
#endif
}

void TestFunc_CLK_SetCoreClock()
{
    CLK_EnableXtalRC(CLK_SRCCTL_HIRCEN_Msk);
    CLK_WaitClockReady(CLK_STATUS_HIRCSTB_Msk);

    CLK_SetCoreClock(FREQ_50MHZ);
    CU_ASSERT(CLK_GetACLKFreq() == FREQ_50MHZ);

    CLK_SetCoreClock(FREQ_100MHZ);
    CU_ASSERT(CLK_GetACLKFreq() == FREQ_100MHZ);

    CLK_SetCoreClock(FREQ_100MHZ);
    CU_ASSERT(CLK_GetACLKFreq() == FREQ_100MHZ);

    CLK_SetCoreClock(FREQ_180MHZ);
    CU_ASSERT(CLK_GetACLKFreq() == FREQ_180MHZ);
}

const uint32_t au32CLKOClkSrcSel[] =
{
    CLK_CLKOSEL_CLKOSEL_SYSCLK,
    CLK_CLKOSEL_CLKOSEL_ACLK,
    CLK_CLKOSEL_CLKOSEL_HCLK0,
    CLK_CLKOSEL_CLKOSEL_HCLK1,
    CLK_CLKOSEL_CLKOSEL_HCLK2,
    CLK_CLKOSEL_CLKOSEL_APLL0_DIV2,
    CLK_CLKOSEL_CLKOSEL_APLL1_DIV2,
    CLK_CLKOSEL_CLKOSEL_HIRC48M,
    CLK_CLKOSEL_CLKOSEL_HXT,
    CLK_CLKOSEL_CLKOSEL_HIRC,
    CLK_CLKOSEL_CLKOSEL_MIRC,
    CLK_CLKOSEL_CLKOSEL_LXT,
    CLK_CLKOSEL_CLKOSEL_LIRC,
    CLK_CLKOSEL_CLKOSEL_SOF,
};

void TestFunc_CLK_EnableCKO()
{
    uint8_t u8TestClkSrc;   //CLKO cloclk source
    uint8_t u8TestFreqDiv;  //CLKO frequency divider

    /* Test loop */
    /* Select CLKO cloclk source */
    for (u8TestClkSrc = 0; u8TestClkSrc < (sizeof(au32CLKOClkSrcSel) / sizeof(uint32_t)); u8TestClkSrc++)
    {
        //select CLKO frequency divider
        for (u8TestFreqDiv = 0; u8TestFreqDiv < 16; u8TestFreqDiv++)
        {
            //test function: enable CKO
            CLK_EnableCKO(au32CLKOClkSrcSel[u8TestClkSrc], u8TestFreqDiv, 1);
            //check result
            CU_ASSERT((CLK->CLKOSEL & CLK_CLKOSEL_CLKOSEL_Msk) == au32CLKOClkSrcSel[u8TestClkSrc]);
            CU_ASSERT((CLK->CLKOCTL & CLK_CLKOCTL_CLKOEN_Msk) == CLK_CLKOCTL_CLKOEN_Msk);
            CU_ASSERT((CLK->CLKOCTL & CLK_CLKOCTL_FREQSEL_Msk) == u8TestFreqDiv);
            CU_ASSERT((CLK->CLKOCTL & CLK_CLKOCTL_DIV1EN_Msk) == CLK_CLKOCTL_DIV1EN_Msk);

            //test function: disable CKO clock
            CLK_DisableCKO();

            //check result
            CU_ASSERT((CLK->CLKOCTL & CLK_CLKOCTL_CLKOEN_Msk) == 0);

            //test function: enable CKO
            CLK_EnableCKO(au32CLKOClkSrcSel[u8TestClkSrc], u8TestFreqDiv, 0);

            //check result
            CU_ASSERT((CLK->CLKOSEL & CLK_CLKOSEL_CLKOSEL_Msk) == au32CLKOClkSrcSel[u8TestClkSrc]);
            CU_ASSERT((CLK->CLKOCTL & CLK_CLKOCTL_CLKOEN_Msk) == CLK_CLKOCTL_CLKOEN_Msk);
            CU_ASSERT((CLK->CLKOCTL & CLK_CLKOCTL_FREQSEL_Msk) == u8TestFreqDiv);
            CU_ASSERT((CLK->CLKOCTL & CLK_CLKOCTL_DIV1EN_Msk) == 0);

            //test function: disable CKO clock
            CLK_DisableCKO();

            //check result
            CU_ASSERT((CLK->CLKOCTL & CLK_CLKOCTL_CLKOEN_Msk) == 0);
        }
    }
}

const uint32_t au32SysTickClkSrcSel[] =
{
    CLK_STSEL_ST0SEL_HXT,
    CLK_STSEL_ST0SEL_LXT,
    CLK_STSEL_ST0SEL_HXT_DIV2,
    CLK_STSEL_ST0SEL_ACLK_DIV2,
    CLK_STSEL_ST0SEL_HIRC_DIV2,
};

void TestFunc_CLK_SetSysTickClockSrc()
{
    uint8_t u8SysTickClkSrcSelIdx;  //systick clock source

    /* Test loop */
    for (u8SysTickClkSrcSelIdx = 0; u8SysTickClkSrcSelIdx < (sizeof(au32SysTickClkSrcSel) / sizeof(uint32_t)); u8SysTickClkSrcSelIdx++)
    {
        CLK_SetSysTickClockSrc(au32SysTickClkSrcSel[u8SysTickClkSrcSelIdx]);
        CU_ASSERT((CLK->STSEL & CLK_STSEL_ST0SEL_Msk) == au32SysTickClkSrcSel[u8SysTickClkSrcSelIdx]);
    }
}

const uint64_t au64ModuleClkSrcSel[] =
{
    BPWM0_MODULE,   (uint32_t)&CLK->BPWMSEL,    CLK_BPWMSEL_BPWM0SEL_Msk,       CLK_BPWMSEL_BPWM0SEL_PCLK0,
    BPWM0_MODULE,   (uint32_t)&CLK->BPWMSEL,    CLK_BPWMSEL_BPWM0SEL_Msk,       CLK_BPWMSEL_BPWM0SEL_HCLK0,
    BPWM1_MODULE,   (uint32_t)&CLK->BPWMSEL,    CLK_BPWMSEL_BPWM1SEL_Msk,       CLK_BPWMSEL_BPWM1SEL_PCLK2,
    BPWM1_MODULE,   (uint32_t)&CLK->BPWMSEL,    CLK_BPWMSEL_BPWM1SEL_Msk,       CLK_BPWMSEL_BPWM1SEL_HCLK0,
    CANFD0_MODULE,  (uint32_t)&CLK->CANFDSEL,   CLK_CANFDSEL_CANFD0SEL_Msk,     CLK_CANFDSEL_CANFD0SEL_HXT,
    CANFD0_MODULE,  (uint32_t)&CLK->CANFDSEL,   CLK_CANFDSEL_CANFD0SEL_Msk,     CLK_CANFDSEL_CANFD0SEL_APLL0_DIV2,
    CANFD0_MODULE,  (uint32_t)&CLK->CANFDSEL,   CLK_CANFDSEL_CANFD0SEL_Msk,     CLK_CANFDSEL_CANFD0SEL_HCLK0,
    CANFD0_MODULE,  (uint32_t)&CLK->CANFDSEL,   CLK_CANFDSEL_CANFD0SEL_Msk,     CLK_CANFDSEL_CANFD0SEL_HIRC,
    CANFD0_MODULE,  (uint32_t)&CLK->CANFDSEL,   CLK_CANFDSEL_CANFD0SEL_Msk,     CLK_CANFDSEL_CANFD0SEL_HIRC48M_DIV4,
    CANFD1_MODULE,  (uint32_t)&CLK->CANFDSEL,   CLK_CANFDSEL_CANFD1SEL_Msk,     CLK_CANFDSEL_CANFD1SEL_HXT,
    CANFD1_MODULE,  (uint32_t)&CLK->CANFDSEL,   CLK_CANFDSEL_CANFD1SEL_Msk,     CLK_CANFDSEL_CANFD1SEL_APLL0_DIV2,
    CANFD1_MODULE,  (uint32_t)&CLK->CANFDSEL,   CLK_CANFDSEL_CANFD1SEL_Msk,     CLK_CANFDSEL_CANFD1SEL_HCLK0,
    CANFD1_MODULE,  (uint32_t)&CLK->CANFDSEL,   CLK_CANFDSEL_CANFD1SEL_Msk,     CLK_CANFDSEL_CANFD1SEL_HIRC,
    CANFD1_MODULE,  (uint32_t)&CLK->CANFDSEL,   CLK_CANFDSEL_CANFD1SEL_Msk,     CLK_CANFDSEL_CANFD1SEL_HIRC48M_DIV4,    
    CCAP0_MODULE,   (uint32_t)&CLK->CCAPSEL,    CLK_CCAPSEL_CCAP0SEL_Msk,       CLK_CCAPSEL_CCAP0SEL_MIRC,
    CCAP0_MODULE,   (uint32_t)&CLK->CCAPSEL,    CLK_CCAPSEL_CCAP0SEL_Msk,       CLK_CCAPSEL_CCAP0SEL_HIRC,
    CCAP0_MODULE,   (uint32_t)&CLK->CCAPSEL,    CLK_CCAPSEL_CCAP0SEL_Msk,       CLK_CCAPSEL_CCAP0SEL_HXT,
    DMIC0_MODULE,   (uint32_t)&CLK->DMICSEL,    CLK_DMICSEL_DMIC0SEL_Msk,       CLK_DMICSEL_DMIC0SEL_HXT,
    DMIC0_MODULE,   (uint32_t)&CLK->DMICSEL,    CLK_DMICSEL_DMIC0SEL_Msk,       CLK_DMICSEL_DMIC0SEL_APLL1_DIV2,
    DMIC0_MODULE,   (uint32_t)&CLK->DMICSEL,    CLK_DMICSEL_DMIC0SEL_Msk,       CLK_DMICSEL_DMIC0SEL_MIRC,
    DMIC0_MODULE,   (uint32_t)&CLK->DMICSEL,    CLK_DMICSEL_DMIC0SEL_Msk,       CLK_DMICSEL_DMIC0SEL_HIRC,
    DMIC0_MODULE,   (uint32_t)&CLK->DMICSEL,    CLK_DMICSEL_DMIC0SEL_Msk,       CLK_DMICSEL_DMIC0SEL_HIRC48M,
    DMIC0_MODULE,   (uint32_t)&CLK->DMICSEL,    CLK_DMICSEL_DMIC0SEL_Msk,       CLK_DMICSEL_DMIC0SEL_PCLK4,
    EADC0_MODULE,   (uint32_t)&CLK->EADCSEL,    CLK_EADCSEL_EADC0SEL_Msk,       CLK_EADCSEL_EADC0SEL_APLL1_DIV2,
    EADC0_MODULE,   (uint32_t)&CLK->EADCSEL,    CLK_EADCSEL_EADC0SEL_Msk,       CLK_EADCSEL_EADC0SEL_APLL0_DIV2,
    EADC0_MODULE,   (uint32_t)&CLK->EADCSEL,    CLK_EADCSEL_EADC0SEL_Msk,       CLK_EADCSEL_EADC0SEL_PCLK0,
    EADC1_MODULE,   (uint32_t)&CLK->EADCSEL,    CLK_EADCSEL_EADC1SEL_Msk,       CLK_EADCSEL_EADC1SEL_APLL1_DIV2,
    EADC1_MODULE,   (uint32_t)&CLK->EADCSEL,    CLK_EADCSEL_EADC1SEL_Msk,       CLK_EADCSEL_EADC1SEL_APLL0_DIV2,
    EADC1_MODULE,   (uint32_t)&CLK->EADCSEL,    CLK_EADCSEL_EADC1SEL_Msk,       CLK_EADCSEL_EADC1SEL_PCLK2,    
    EPWM0_MODULE,   (uint32_t)&CLK->EPWMSEL,    CLK_EPWMSEL_EPWM0SEL_Msk,       CLK_EPWMSEL_EPWM0SEL_PCLK0,
    EPWM0_MODULE,   (uint32_t)&CLK->EPWMSEL,    CLK_EPWMSEL_EPWM0SEL_Msk,       CLK_EPWMSEL_EPWM0SEL_HCLK0,
    EPWM1_MODULE,   (uint32_t)&CLK->EPWMSEL,    CLK_EPWMSEL_EPWM1SEL_Msk,       CLK_EPWMSEL_EPWM1SEL_PCLK2,
    EPWM1_MODULE,   (uint32_t)&CLK->EPWMSEL,    CLK_EPWMSEL_EPWM1SEL_Msk,       CLK_EPWMSEL_EPWM1SEL_HCLK0,
    FMC0_MODULE,    (uint32_t)&CLK->FMCSEL,     CLK_FMCSEL_FMC0SEL_Msk,         CLK_FMCSEL_FMC0SEL_HIRC,
    FMC0_MODULE,    (uint32_t)&CLK->FMCSEL,     CLK_FMCSEL_FMC0SEL_Msk,         CLK_FMCSEL_FMC0SEL_HIRC48M_DIV4,
    I2S0_MODULE,    (uint32_t)&CLK->I2SSEL,     CLK_I2SSEL_I2S0SEL_Msk,         CLK_I2SSEL_I2S0SEL_HXT,
    I2S0_MODULE,    (uint32_t)&CLK->I2SSEL,     CLK_I2SSEL_I2S0SEL_Msk,         CLK_I2SSEL_I2S0SEL_APLL1_DIV2,
    I2S0_MODULE,    (uint32_t)&CLK->I2SSEL,     CLK_I2SSEL_I2S0SEL_Msk,         CLK_I2SSEL_I2S0SEL_APLL0_DIV2,
    I2S0_MODULE,    (uint32_t)&CLK->I2SSEL,     CLK_I2SSEL_I2S0SEL_Msk,         CLK_I2SSEL_I2S0SEL_PCLK1,
    I2S0_MODULE,    (uint32_t)&CLK->I2SSEL,     CLK_I2SSEL_I2S0SEL_Msk,         CLK_I2SSEL_I2S0SEL_HIRC,
    I2S0_MODULE,    (uint32_t)&CLK->I2SSEL,     CLK_I2SSEL_I2S0SEL_Msk,         CLK_I2SSEL_I2S0SEL_HIRC48M,
    I2S1_MODULE,    (uint32_t)&CLK->I2SSEL,     CLK_I2SSEL_I2S1SEL_Msk,         CLK_I2SSEL_I2S1SEL_HXT,
    I2S1_MODULE,    (uint32_t)&CLK->I2SSEL,     CLK_I2SSEL_I2S1SEL_Msk,         CLK_I2SSEL_I2S1SEL_APLL1_DIV2,
    I2S1_MODULE,    (uint32_t)&CLK->I2SSEL,     CLK_I2SSEL_I2S1SEL_Msk,         CLK_I2SSEL_I2S1SEL_APLL0_DIV2,
    I2S1_MODULE,    (uint32_t)&CLK->I2SSEL,     CLK_I2SSEL_I2S1SEL_Msk,         CLK_I2SSEL_I2S1SEL_PCLK3,
    I2S1_MODULE,    (uint32_t)&CLK->I2SSEL,     CLK_I2SSEL_I2S1SEL_Msk,         CLK_I2SSEL_I2S1SEL_HIRC,
    I2S1_MODULE,    (uint32_t)&CLK->I2SSEL,     CLK_I2SSEL_I2S1SEL_Msk,         CLK_I2SSEL_I2S1SEL_HIRC48M,
    I3C0_MODULE,    (uint32_t)&CLK->I3CSEL,     CLK_I3CSEL_I3C0SEL_Msk,         CLK_I3CSEL_I3C0SEL_HCLK0,
    I3C0_MODULE,    (uint32_t)&CLK->I3CSEL,     CLK_I3CSEL_I3C0SEL_Msk,         CLK_I3CSEL_I3C0SEL_APLL1,  
    KPI0_MODULE,    (uint32_t)&CLK->KPISEL,     CLK_KPISEL_KPI0SEL_Msk,         CLK_KPISEL_KPI0SEL_HIRC48M_DIV4,
    KPI0_MODULE,    (uint32_t)&CLK->KPISEL,     CLK_KPISEL_KPI0SEL_Msk,         CLK_KPISEL_KPI0SEL_HIRC,
    KPI0_MODULE,    (uint32_t)&CLK->KPISEL,     CLK_KPISEL_KPI0SEL_Msk,         CLK_KPISEL_KPI0SEL_LIRC,
    KPI0_MODULE,    (uint32_t)&CLK->KPISEL,     CLK_KPISEL_KPI0SEL_Msk,         CLK_KPISEL_KPI0SEL_HXT,
    LPADC0_MODULE,  (uint32_t)&CLK->LPADCSEL,   CLK_LPADCSEL_LPADC0SEL_Msk,     CLK_LPADCSEL_LPADC0SEL_PCLK4,
    LPADC0_MODULE,  (uint32_t)&CLK->LPADCSEL,   CLK_LPADCSEL_LPADC0SEL_Msk,     CLK_LPADCSEL_LPADC0SEL_LXT,
    LPADC0_MODULE,  (uint32_t)&CLK->LPADCSEL,   CLK_LPADCSEL_LPADC0SEL_Msk,     CLK_LPADCSEL_LPADC0SEL_MIRC,
    LPADC0_MODULE,  (uint32_t)&CLK->LPADCSEL,   CLK_LPADCSEL_LPADC0SEL_Msk,     CLK_LPADCSEL_LPADC0SEL_HIRC,    
    LPSPI0_MODULE,  (uint32_t)&CLK->LPSPISEL,   CLK_LPSPISEL_LPSPI0SEL_Msk,     CLK_LPSPISEL_LPSPI0SEL_PCLK4,
    LPSPI0_MODULE,  (uint32_t)&CLK->LPSPISEL,   CLK_LPSPISEL_LPSPI0SEL_Msk,     CLK_LPSPISEL_LPSPI0SEL_MIRC,
    LPSPI0_MODULE,  (uint32_t)&CLK->LPSPISEL,   CLK_LPSPISEL_LPSPI0SEL_Msk,     CLK_LPSPISEL_LPSPI0SEL_HIRC,
    LPTMR0_MODULE,  (uint32_t)&CLK->LPTMRSEL,   CLK_LPTMRSEL_LPTMR0SEL_Msk,     CLK_LPTMRSEL_LPTMR0SEL_PCLK4,
    LPTMR0_MODULE,  (uint32_t)&CLK->LPTMRSEL,   CLK_LPTMRSEL_LPTMR0SEL_Msk,     CLK_LPTMRSEL_LPTMR0SEL_LXT,
    LPTMR0_MODULE,  (uint32_t)&CLK->LPTMRSEL,   CLK_LPTMRSEL_LPTMR0SEL_Msk,     CLK_LPTMRSEL_LPTMR0SEL_LIRC,
    LPTMR0_MODULE,  (uint32_t)&CLK->LPTMRSEL,   CLK_LPTMRSEL_LPTMR0SEL_Msk,     CLK_LPTMRSEL_LPTMR0SEL_MIRC,
    LPTMR0_MODULE,  (uint32_t)&CLK->LPTMRSEL,   CLK_LPTMRSEL_LPTMR0SEL_Msk,     CLK_LPTMRSEL_LPTMR0SEL_HIRC,
    LPTMR0_MODULE,  (uint32_t)&CLK->LPTMRSEL,   CLK_LPTMRSEL_LPTMR0SEL_Msk,     CLK_LPTMRSEL_LPTMR0SEL_EXT,
    LPTMR1_MODULE,  (uint32_t)&CLK->LPTMRSEL,   CLK_LPTMRSEL_LPTMR1SEL_Msk,     CLK_LPTMRSEL_LPTMR1SEL_PCLK4,
    LPTMR1_MODULE,  (uint32_t)&CLK->LPTMRSEL,   CLK_LPTMRSEL_LPTMR1SEL_Msk,     CLK_LPTMRSEL_LPTMR1SEL_LXT,
    LPTMR1_MODULE,  (uint32_t)&CLK->LPTMRSEL,   CLK_LPTMRSEL_LPTMR1SEL_Msk,     CLK_LPTMRSEL_LPTMR1SEL_LIRC,
    LPTMR1_MODULE,  (uint32_t)&CLK->LPTMRSEL,   CLK_LPTMRSEL_LPTMR1SEL_Msk,     CLK_LPTMRSEL_LPTMR1SEL_MIRC,
    LPTMR1_MODULE,  (uint32_t)&CLK->LPTMRSEL,   CLK_LPTMRSEL_LPTMR1SEL_Msk,     CLK_LPTMRSEL_LPTMR1SEL_HIRC,
    LPTMR1_MODULE,  (uint32_t)&CLK->LPTMRSEL,   CLK_LPTMRSEL_LPTMR1SEL_Msk,     CLK_LPTMRSEL_LPTMR1SEL_EXT,
    LPUART0_MODULE, (uint32_t)&CLK->LPUARTSEL,  CLK_LPUARTSEL_LPUART0SEL_Msk,   CLK_LPUARTSEL_LPUART0SEL_PCLK4,
    LPUART0_MODULE, (uint32_t)&CLK->LPUARTSEL,  CLK_LPUARTSEL_LPUART0SEL_Msk,   CLK_LPUARTSEL_LPUART0SEL_LXT,
    LPUART0_MODULE, (uint32_t)&CLK->LPUARTSEL,  CLK_LPUARTSEL_LPUART0SEL_Msk,   CLK_LPUARTSEL_LPUART0SEL_MIRC,
    LPUART0_MODULE, (uint32_t)&CLK->LPUARTSEL,  CLK_LPUARTSEL_LPUART0SEL_Msk,   CLK_LPUARTSEL_LPUART0SEL_HIRC,
    PSIO0_MODULE,   (uint32_t)&CLK->PSIOSEL,    CLK_PSIOSEL_PSIO0SEL_Msk,       CLK_PSIOSEL_PSIO0SEL_LXT,
    PSIO0_MODULE,   (uint32_t)&CLK->PSIOSEL,    CLK_PSIOSEL_PSIO0SEL_Msk,       CLK_PSIOSEL_PSIO0SEL_HXT,
    PSIO0_MODULE,   (uint32_t)&CLK->PSIOSEL,    CLK_PSIOSEL_PSIO0SEL_Msk,       CLK_PSIOSEL_PSIO0SEL_LIRC,
    PSIO0_MODULE,   (uint32_t)&CLK->PSIOSEL,    CLK_PSIOSEL_PSIO0SEL_Msk,       CLK_PSIOSEL_PSIO0SEL_HIRC,
    PSIO0_MODULE,   (uint32_t)&CLK->PSIOSEL,    CLK_PSIOSEL_PSIO0SEL_Msk,       CLK_PSIOSEL_PSIO0SEL_HIRC48M_DIV4,
    PSIO0_MODULE,   (uint32_t)&CLK->PSIOSEL,    CLK_PSIOSEL_PSIO0SEL_Msk,       CLK_PSIOSEL_PSIO0SEL_PCLK1,
    PSIO0_MODULE,   (uint32_t)&CLK->PSIOSEL,    CLK_PSIOSEL_PSIO0SEL_Msk,       CLK_PSIOSEL_PSIO0SEL_APLL0_DIV2,
    QSPI0_MODULE,   (uint32_t)&CLK->QSPISEL,    CLK_QSPISEL_QSPI0SEL_Msk,       CLK_QSPISEL_QSPI0SEL_HXT,
    QSPI0_MODULE,   (uint32_t)&CLK->QSPISEL,    CLK_QSPISEL_QSPI0SEL_Msk,       CLK_QSPISEL_QSPI0SEL_APLL0_DIV2,
    QSPI0_MODULE,   (uint32_t)&CLK->QSPISEL,    CLK_QSPISEL_QSPI0SEL_Msk,       CLK_QSPISEL_QSPI0SEL_PCLK0,
    QSPI0_MODULE,   (uint32_t)&CLK->QSPISEL,    CLK_QSPISEL_QSPI0SEL_Msk,       CLK_QSPISEL_QSPI0SEL_HIRC,
    QSPI0_MODULE,   (uint32_t)&CLK->QSPISEL,    CLK_QSPISEL_QSPI0SEL_Msk,       CLK_QSPISEL_QSPI0SEL_HIRC48M_DIV4,
    QSPI1_MODULE,   (uint32_t)&CLK->QSPISEL,    CLK_QSPISEL_QSPI1SEL_Msk,       CLK_QSPISEL_QSPI1SEL_HXT,
    QSPI1_MODULE,   (uint32_t)&CLK->QSPISEL,    CLK_QSPISEL_QSPI1SEL_Msk,       CLK_QSPISEL_QSPI1SEL_APLL0_DIV2,
    QSPI1_MODULE,   (uint32_t)&CLK->QSPISEL,    CLK_QSPISEL_QSPI1SEL_Msk,       CLK_QSPISEL_QSPI1SEL_PCLK2,
    QSPI1_MODULE,   (uint32_t)&CLK->QSPISEL,    CLK_QSPISEL_QSPI1SEL_Msk,       CLK_QSPISEL_QSPI1SEL_HIRC,
    QSPI1_MODULE,   (uint32_t)&CLK->QSPISEL,    CLK_QSPISEL_QSPI1SEL_Msk,       CLK_QSPISEL_QSPI1SEL_HIRC48M_DIV4,
    SC0_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC0SEL_Msk,           CLK_SCSEL_SC0SEL_HXT,
    SC0_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC0SEL_Msk,           CLK_SCSEL_SC0SEL_APLL0_DIV2,
    SC0_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC0SEL_Msk,           CLK_SCSEL_SC0SEL_PCLK1,
    SC0_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC0SEL_Msk,           CLK_SCSEL_SC0SEL_HIRC,
    SC0_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC0SEL_Msk,           CLK_SCSEL_SC0SEL_HIRC48M_DIV4,
    SC1_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC1SEL_Msk,           CLK_SCSEL_SC1SEL_HXT,
    SC1_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC1SEL_Msk,           CLK_SCSEL_SC1SEL_APLL0_DIV2,
    SC1_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC1SEL_Msk,           CLK_SCSEL_SC1SEL_PCLK3,
    SC1_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC1SEL_Msk,           CLK_SCSEL_SC1SEL_HIRC,
    SC1_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC1SEL_Msk,           CLK_SCSEL_SC1SEL_HIRC48M_DIV4,
    SC2_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC2SEL_Msk,           CLK_SCSEL_SC2SEL_HXT,
    SC2_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC2SEL_Msk,           CLK_SCSEL_SC2SEL_APLL0_DIV2,
    SC2_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC2SEL_Msk,           CLK_SCSEL_SC2SEL_PCLK1,
    SC2_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC2SEL_Msk,           CLK_SCSEL_SC2SEL_HIRC,
    SC2_MODULE,     (uint32_t)&CLK->SCSEL,      CLK_SCSEL_SC2SEL_Msk,           CLK_SCSEL_SC2SEL_HIRC48M_DIV4,
    SDH0_MODULE,    (uint32_t)&CLK->SDHSEL,     CLK_SDHSEL_SDH0SEL_Msk,         CLK_SDHSEL_SDH0SEL_HXT,
    SDH0_MODULE,    (uint32_t)&CLK->SDHSEL,     CLK_SDHSEL_SDH0SEL_Msk,         CLK_SDHSEL_SDH0SEL_APLL1_DIV2,
    SDH0_MODULE,    (uint32_t)&CLK->SDHSEL,     CLK_SDHSEL_SDH0SEL_Msk,         CLK_SDHSEL_SDH0SEL_HCLK0,
    SDH0_MODULE,    (uint32_t)&CLK->SDHSEL,     CLK_SDHSEL_SDH0SEL_Msk,         CLK_SDHSEL_SDH0SEL_HIRC,
    SDH0_MODULE,    (uint32_t)&CLK->SDHSEL,     CLK_SDHSEL_SDH0SEL_Msk,         CLK_SDHSEL_SDH0SEL_HIRC48M_DIV4,
    SDH1_MODULE,    (uint32_t)&CLK->SDHSEL,     CLK_SDHSEL_SDH1SEL_Msk,         CLK_SDHSEL_SDH1SEL_HXT,
    SDH1_MODULE,    (uint32_t)&CLK->SDHSEL,     CLK_SDHSEL_SDH1SEL_Msk,         CLK_SDHSEL_SDH1SEL_APLL1_DIV2,
    SDH1_MODULE,    (uint32_t)&CLK->SDHSEL,     CLK_SDHSEL_SDH1SEL_Msk,         CLK_SDHSEL_SDH1SEL_HCLK0,
    SDH1_MODULE,    (uint32_t)&CLK->SDHSEL,     CLK_SDHSEL_SDH1SEL_Msk,         CLK_SDHSEL_SDH1SEL_HIRC,
    SDH1_MODULE,    (uint32_t)&CLK->SDHSEL,     CLK_SDHSEL_SDH1SEL_Msk,         CLK_SDHSEL_SDH1SEL_HIRC48M_DIV4,
    SPI0_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI0SEL_Msk,         CLK_SPISEL_SPI0SEL_HXT,
    SPI0_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI0SEL_Msk,         CLK_SPISEL_SPI0SEL_APLL1_DIV2,
    SPI0_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI0SEL_Msk,         CLK_SPISEL_SPI0SEL_APLL0_DIV2,
    SPI0_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI0SEL_Msk,         CLK_SPISEL_SPI0SEL_PCLK0,
    SPI0_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI0SEL_Msk,         CLK_SPISEL_SPI0SEL_HIRC,
    SPI0_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI0SEL_Msk,         CLK_SPISEL_SPI0SEL_HIRC48M,
    SPI1_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI1SEL_Msk,         CLK_SPISEL_SPI1SEL_HXT,
    SPI1_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI1SEL_Msk,         CLK_SPISEL_SPI1SEL_APLL1_DIV2,
    SPI1_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI1SEL_Msk,         CLK_SPISEL_SPI1SEL_APLL0_DIV2,
    SPI1_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI1SEL_Msk,         CLK_SPISEL_SPI1SEL_PCLK2,
    SPI1_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI1SEL_Msk,         CLK_SPISEL_SPI1SEL_HIRC,
    SPI1_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI1SEL_Msk,         CLK_SPISEL_SPI1SEL_HIRC48M,
    SPI2_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI2SEL_Msk,         CLK_SPISEL_SPI2SEL_HXT,
    SPI2_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI2SEL_Msk,         CLK_SPISEL_SPI2SEL_APLL1_DIV2,
    SPI2_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI2SEL_Msk,         CLK_SPISEL_SPI2SEL_APLL0_DIV2,
    SPI2_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI2SEL_Msk,         CLK_SPISEL_SPI2SEL_PCLK0,
    SPI2_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI2SEL_Msk,         CLK_SPISEL_SPI2SEL_HIRC,
    SPI2_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI2SEL_Msk,         CLK_SPISEL_SPI2SEL_HIRC48M,
    SPI3_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI3SEL_Msk,         CLK_SPISEL_SPI3SEL_HXT,
    SPI3_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI3SEL_Msk,         CLK_SPISEL_SPI3SEL_APLL1_DIV2,
    SPI3_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI3SEL_Msk,         CLK_SPISEL_SPI3SEL_APLL0_DIV2,
    SPI3_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI3SEL_Msk,         CLK_SPISEL_SPI3SEL_PCLK2,
    SPI3_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI3SEL_Msk,         CLK_SPISEL_SPI3SEL_HIRC,
    SPI3_MODULE,    (uint32_t)&CLK->SPISEL,     CLK_SPISEL_SPI3SEL_Msk,         CLK_SPISEL_SPI3SEL_HIRC48M,
    TMR0_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR0SEL_Msk,         CLK_TMRSEL_TMR0SEL_HXT,
    TMR0_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR0SEL_Msk,         CLK_TMRSEL_TMR0SEL_LXT,
    TMR0_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR0SEL_Msk,         CLK_TMRSEL_TMR0SEL_PCLK1,
    TMR0_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR0SEL_Msk,         CLK_TMRSEL_TMR0SEL_EXT,
    TMR0_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR0SEL_Msk,         CLK_TMRSEL_TMR0SEL_LIRC,
    TMR0_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR0SEL_Msk,         CLK_TMRSEL_TMR0SEL_HIRC,
    TMR0_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR0SEL_Msk,         CLK_TMRSEL_TMR0SEL_HIRC48M_DIV4,
    TMR1_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR1SEL_Msk,         CLK_TMRSEL_TMR1SEL_HXT,
    TMR1_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR1SEL_Msk,         CLK_TMRSEL_TMR1SEL_LXT,
    TMR1_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR1SEL_Msk,         CLK_TMRSEL_TMR1SEL_PCLK1,
    TMR1_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR1SEL_Msk,         CLK_TMRSEL_TMR1SEL_EXT,
    TMR1_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR1SEL_Msk,         CLK_TMRSEL_TMR1SEL_LIRC,
    TMR1_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR1SEL_Msk,         CLK_TMRSEL_TMR1SEL_HIRC,
    TMR1_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR1SEL_Msk,         CLK_TMRSEL_TMR1SEL_HIRC48M_DIV4,
    TMR2_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR2SEL_Msk,         CLK_TMRSEL_TMR2SEL_HXT,
    TMR2_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR2SEL_Msk,         CLK_TMRSEL_TMR2SEL_LXT,
    TMR2_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR2SEL_Msk,         CLK_TMRSEL_TMR2SEL_PCLK3,
    TMR2_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR2SEL_Msk,         CLK_TMRSEL_TMR2SEL_EXT,
    TMR2_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR2SEL_Msk,         CLK_TMRSEL_TMR2SEL_LIRC,
    TMR2_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR2SEL_Msk,         CLK_TMRSEL_TMR2SEL_HIRC,
    TMR2_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR2SEL_Msk,         CLK_TMRSEL_TMR2SEL_HIRC48M_DIV4,
    TMR3_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR3SEL_Msk,         CLK_TMRSEL_TMR3SEL_HXT,
    TMR3_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR3SEL_Msk,         CLK_TMRSEL_TMR3SEL_LXT,
    TMR3_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR3SEL_Msk,         CLK_TMRSEL_TMR3SEL_PCLK3,
    TMR3_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR3SEL_Msk,         CLK_TMRSEL_TMR3SEL_EXT,
    TMR3_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR3SEL_Msk,         CLK_TMRSEL_TMR3SEL_LIRC,
    TMR3_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR3SEL_Msk,         CLK_TMRSEL_TMR3SEL_HIRC,
    TMR3_MODULE,    (uint32_t)&CLK->TMRSEL,     CLK_TMRSEL_TMR3SEL_Msk,         CLK_TMRSEL_TMR3SEL_HIRC48M_DIV4,
    TTMR0_MODULE,   (uint32_t)&CLK->TTMRSEL,    CLK_TTMRSEL_TTMR0SEL_Msk,       CLK_TTMRSEL_TTMR0SEL_PCLK4,
    TTMR0_MODULE,   (uint32_t)&CLK->TTMRSEL,    CLK_TTMRSEL_TTMR0SEL_Msk,       CLK_TTMRSEL_TTMR0SEL_LXT,
    TTMR0_MODULE,   (uint32_t)&CLK->TTMRSEL,    CLK_TTMRSEL_TTMR0SEL_Msk,       CLK_TTMRSEL_TTMR0SEL_LIRC,
    TTMR0_MODULE,   (uint32_t)&CLK->TTMRSEL,    CLK_TTMRSEL_TTMR0SEL_Msk,       CLK_TTMRSEL_TTMR0SEL_MIRC,
    TTMR0_MODULE,   (uint32_t)&CLK->TTMRSEL,    CLK_TTMRSEL_TTMR0SEL_Msk,       CLK_TTMRSEL_TTMR0SEL_HIRC,
    TTMR1_MODULE,   (uint32_t)&CLK->TTMRSEL,    CLK_TTMRSEL_TTMR1SEL_Msk,       CLK_TTMRSEL_TTMR1SEL_PCLK4,
    TTMR1_MODULE,   (uint32_t)&CLK->TTMRSEL,    CLK_TTMRSEL_TTMR1SEL_Msk,       CLK_TTMRSEL_TTMR1SEL_LXT,
    TTMR1_MODULE,   (uint32_t)&CLK->TTMRSEL,    CLK_TTMRSEL_TTMR1SEL_Msk,       CLK_TTMRSEL_TTMR1SEL_LIRC,
    TTMR1_MODULE,   (uint32_t)&CLK->TTMRSEL,    CLK_TTMRSEL_TTMR1SEL_Msk,       CLK_TTMRSEL_TTMR1SEL_MIRC,
    TTMR1_MODULE,   (uint32_t)&CLK->TTMRSEL,    CLK_TTMRSEL_TTMR1SEL_Msk,       CLK_TTMRSEL_TTMR1SEL_HIRC,
    UART0_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART0SEL_Msk,      CLK_UARTSEL0_UART0SEL_HXT,
    UART0_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART0SEL_Msk,      CLK_UARTSEL0_UART0SEL_HIRC,
    UART0_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART0SEL_Msk,      CLK_UARTSEL0_UART0SEL_LXT,
    UART0_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART0SEL_Msk,      CLK_UARTSEL0_UART0SEL_APLL0_DIV2,
    UART0_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART0SEL_Msk,      CLK_UARTSEL0_UART0SEL_HIRC48M,
    UART1_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART1SEL_Msk,      CLK_UARTSEL0_UART1SEL_HXT,
    UART1_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART1SEL_Msk,      CLK_UARTSEL0_UART1SEL_HIRC,
    UART1_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART1SEL_Msk,      CLK_UARTSEL0_UART1SEL_LXT,
    UART1_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART1SEL_Msk,      CLK_UARTSEL0_UART1SEL_APLL0_DIV2,
    UART1_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART1SEL_Msk,      CLK_UARTSEL0_UART1SEL_HIRC48M,
    UART2_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART2SEL_Msk,      CLK_UARTSEL0_UART2SEL_HXT,
    UART2_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART2SEL_Msk,      CLK_UARTSEL0_UART2SEL_HIRC,
    UART2_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART2SEL_Msk,      CLK_UARTSEL0_UART2SEL_LXT,
    UART2_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART2SEL_Msk,      CLK_UARTSEL0_UART2SEL_APLL0_DIV2,
    UART2_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART2SEL_Msk,      CLK_UARTSEL0_UART2SEL_HIRC48M,
    UART3_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART3SEL_Msk,      CLK_UARTSEL0_UART3SEL_HXT,
    UART3_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART3SEL_Msk,      CLK_UARTSEL0_UART3SEL_HIRC,
    UART3_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART3SEL_Msk,      CLK_UARTSEL0_UART3SEL_LXT,
    UART3_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART3SEL_Msk,      CLK_UARTSEL0_UART3SEL_APLL0_DIV2,
    UART3_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART3SEL_Msk,      CLK_UARTSEL0_UART3SEL_HIRC48M,
    UART4_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART4SEL_Msk,      CLK_UARTSEL0_UART4SEL_HXT,
    UART4_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART4SEL_Msk,      CLK_UARTSEL0_UART4SEL_HIRC,
    UART4_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART4SEL_Msk,      CLK_UARTSEL0_UART4SEL_LXT,
    UART4_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART4SEL_Msk,      CLK_UARTSEL0_UART4SEL_APLL0_DIV2,
    UART4_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART4SEL_Msk,      CLK_UARTSEL0_UART4SEL_HIRC48M, 
    UART5_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART5SEL_Msk,      CLK_UARTSEL0_UART5SEL_HXT,
    UART5_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART5SEL_Msk,      CLK_UARTSEL0_UART5SEL_HIRC,
    UART5_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART5SEL_Msk,      CLK_UARTSEL0_UART5SEL_LXT,
    UART5_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART5SEL_Msk,      CLK_UARTSEL0_UART5SEL_APLL0_DIV2,
    UART5_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART5SEL_Msk,      CLK_UARTSEL0_UART5SEL_HIRC48M,
//    UART6_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART6SEL_Msk,      CLK_UARTSEL0_UART6SEL_HXT,
//    UART6_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART6SEL_Msk,      CLK_UARTSEL0_UART6SEL_HIRC,
//    UART6_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART6SEL_Msk,      CLK_UARTSEL0_UART6SEL_LXT,
//    UART6_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART6SEL_Msk,      CLK_UARTSEL0_UART6SEL_APLL0_DIV2,
//    UART6_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART6SEL_Msk,      CLK_UARTSEL0_UART6SEL_HIRC48M,
    UART7_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART7SEL_Msk,      CLK_UARTSEL0_UART7SEL_HXT,
    UART7_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART7SEL_Msk,      CLK_UARTSEL0_UART7SEL_HIRC,
    UART7_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART7SEL_Msk,      CLK_UARTSEL0_UART7SEL_LXT,
    UART7_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART7SEL_Msk,      CLK_UARTSEL0_UART7SEL_APLL0_DIV2,
    UART7_MODULE,   (uint32_t)&CLK->UARTSEL0,   CLK_UARTSEL0_UART7SEL_Msk,      CLK_UARTSEL0_UART7SEL_HIRC48M,
    UART8_MODULE,   (uint32_t)&CLK->UARTSEL1,   CLK_UARTSEL1_UART8SEL_Msk,      CLK_UARTSEL1_UART8SEL_HXT,
    UART8_MODULE,   (uint32_t)&CLK->UARTSEL1,   CLK_UARTSEL1_UART8SEL_Msk,      CLK_UARTSEL1_UART8SEL_HIRC,
    UART8_MODULE,   (uint32_t)&CLK->UARTSEL1,   CLK_UARTSEL1_UART8SEL_Msk,      CLK_UARTSEL1_UART8SEL_LXT,
    UART8_MODULE,   (uint32_t)&CLK->UARTSEL1,   CLK_UARTSEL1_UART8SEL_Msk,      CLK_UARTSEL1_UART8SEL_APLL0_DIV2,
    UART8_MODULE,   (uint32_t)&CLK->UARTSEL1,   CLK_UARTSEL1_UART8SEL_Msk,      CLK_UARTSEL1_UART8SEL_HIRC48M,
    UART9_MODULE,   (uint32_t)&CLK->UARTSEL1,   CLK_UARTSEL1_UART9SEL_Msk,      CLK_UARTSEL1_UART9SEL_HXT,
    UART9_MODULE,   (uint32_t)&CLK->UARTSEL1,   CLK_UARTSEL1_UART9SEL_Msk,      CLK_UARTSEL1_UART9SEL_HIRC,
    UART9_MODULE,   (uint32_t)&CLK->UARTSEL1,   CLK_UARTSEL1_UART9SEL_Msk,      CLK_UARTSEL1_UART9SEL_LXT,
    UART9_MODULE,   (uint32_t)&CLK->UARTSEL1,   CLK_UARTSEL1_UART9SEL_Msk,      CLK_UARTSEL1_UART9SEL_APLL0_DIV2,
    UART9_MODULE,   (uint32_t)&CLK->UARTSEL1,   CLK_UARTSEL1_UART9SEL_Msk,      CLK_UARTSEL1_UART9SEL_HIRC48M, 
    USBD0_MODULE,   (uint32_t)&CLK->USBSEL,     CLK_USBSEL_USBSEL_Msk,          CLK_USBSEL_USBSEL_HIRC48M,
    USBD0_MODULE,   (uint32_t)&CLK->USBSEL,     CLK_USBSEL_USBSEL_Msk,          CLK_USBSEL_USBSEL_APLL1_DIV2,
    USBH0_MODULE,   (uint32_t)&CLK->USBSEL,     CLK_USBSEL_USBSEL_Msk,          CLK_USBSEL_USBSEL_HIRC48M,
    USBH0_MODULE,   (uint32_t)&CLK->USBSEL,     CLK_USBSEL_USBSEL_Msk,          CLK_USBSEL_USBSEL_APLL1_DIV2,
    WDT0_MODULE,    (uint32_t)&CLK->WDTSEL,     CLK_WDTSEL_WDT0SEL_Msk,         CLK_WDTSEL_WDT0SEL_LXT,
    WDT0_MODULE,    (uint32_t)&CLK->WDTSEL,     CLK_WDTSEL_WDT0SEL_Msk,         CLK_WDTSEL_WDT0SEL_HCLK2_DIV2048,
    WDT0_MODULE,    (uint32_t)&CLK->WDTSEL,     CLK_WDTSEL_WDT0SEL_Msk,         CLK_WDTSEL_WDT0SEL_LIRC,
    WDT1_MODULE,    (uint32_t)&CLK->WDTSEL,     CLK_WDTSEL_WDT1SEL_Msk,         CLK_WDTSEL_WDT1SEL_LXT,
    WDT1_MODULE,    (uint32_t)&CLK->WDTSEL,     CLK_WDTSEL_WDT1SEL_Msk,         CLK_WDTSEL_WDT1SEL_HCLK2_DIV2048,
    WDT1_MODULE,    (uint32_t)&CLK->WDTSEL,     CLK_WDTSEL_WDT1SEL_Msk,         CLK_WDTSEL_WDT1SEL_LIRC,
    WWDT0_MODULE,   (uint32_t)&CLK->WWDTSEL,    CLK_WWDTSEL_WWDT0SEL_Msk,       CLK_WWDTSEL_WWDT0SEL_HCLK0_DIV2048,
    WWDT0_MODULE,   (uint32_t)&CLK->WWDTSEL,    CLK_WWDTSEL_WWDT0SEL_Msk,       CLK_WWDTSEL_WWDT0SEL_LIRC,
    WWDT1_MODULE,   (uint32_t)&CLK->WWDTSEL,    CLK_WWDTSEL_WWDT1SEL_Msk,       CLK_WWDTSEL_WWDT1SEL_HCLK0_DIV2048,
    WWDT1_MODULE,   (uint32_t)&CLK->WWDTSEL,    CLK_WWDTSEL_WWDT1SEL_Msk,       CLK_WWDTSEL_WWDT1SEL_LIRC,   

};

const uint64_t au64ModuleClkSrcDiv[] =
{
    CANFD0_MODULE,  (uint32_t)&CLK->CANFDDIV,   CLK_CANFDDIV_CANFD0DIV_Msk,     CLK_CANFDDIV_CANFD0DIV_Pos,
    CANFD1_MODULE,  (uint32_t)&CLK->CANFDDIV,   CLK_CANFDDIV_CANFD1DIV_Msk,     CLK_CANFDDIV_CANFD1DIV_Pos,
    DMIC0_MODULE,   (uint32_t)&CLK->DMICDIV,    CLK_DMICDIV_DMIC0DIV_Msk,       CLK_DMICDIV_DMIC0DIV_Pos,
    EADC0_MODULE,   (uint32_t)&CLK->EADCDIV,    CLK_EADCDIV_EADC0DIV_Msk,       CLK_EADCDIV_EADC0DIV_Pos,
    EADC1_MODULE,   (uint32_t)&CLK->EADCDIV,    CLK_EADCDIV_EADC1DIV_Msk,       CLK_EADCDIV_EADC1DIV_Pos,    
    I2S0_MODULE,    (uint32_t)&CLK->I2SDIV,     CLK_I2SDIV_I2S0DIV_Msk,         CLK_I2SDIV_I2S0DIV_Pos,
    I2S1_MODULE,    (uint32_t)&CLK->I2SDIV,     CLK_I2SDIV_I2S1DIV_Msk,         CLK_I2SDIV_I2S1DIV_Pos,
    KPI0_MODULE,    (uint32_t)&CLK->KPIDIV,     CLK_KPIDIV_KPI0DIV_Msk,         CLK_KPIDIV_KPI0DIV_Pos,
    LPADC0_MODULE,  (uint32_t)&CLK->LPADCDIV,   CLK_LPADCDIV_LPADC0DIV_Msk,     CLK_LPADCDIV_LPADC0DIV_Pos,
    LPUART0_MODULE, (uint32_t)&CLK->LPUARTDIV,  CLK_LPUARTDIV_LPUART0DIV_Msk,   CLK_LPUARTDIV_LPUART0DIV_Pos,
    PSIO0_MODULE,   (uint32_t)&CLK->PSIODIV,    CLK_PSIODIV_PSIO0DIV_Msk,       CLK_PSIODIV_PSIO0DIV_Pos,
    SC0_MODULE,     (uint32_t)&CLK->SCDIV,      CLK_SCDIV_SC0DIV_Msk,           CLK_SCDIV_SC0DIV_Pos,
    SC1_MODULE,     (uint32_t)&CLK->SCDIV,      CLK_SCDIV_SC1DIV_Msk,           CLK_SCDIV_SC1DIV_Pos,
    SC2_MODULE,     (uint32_t)&CLK->SCDIV,      CLK_SCDIV_SC2DIV_Msk,           CLK_SCDIV_SC2DIV_Pos,
    SDH0_MODULE,    (uint32_t)&CLK->SDHDIV,     CLK_SDHDIV_SDH0DIV_Msk,         CLK_SDHDIV_SDH0DIV_Pos,
    SDH1_MODULE,    (uint32_t)&CLK->SDHDIV,     CLK_SDHDIV_SDH1DIV_Msk,         CLK_SDHDIV_SDH1DIV_Pos,
    ST0_MODULE,     (uint32_t)&CLK->STDIV,      CLK_STDIV_ST0DIV_Msk,           CLK_STDIV_ST0DIV_Pos,
    UART0_MODULE,   (uint32_t)&CLK->UARTDIV0,   CLK_UARTDIV0_UART0DIV_Msk,      CLK_UARTDIV0_UART0DIV_Pos,
    UART1_MODULE,   (uint32_t)&CLK->UARTDIV0,   CLK_UARTDIV0_UART1DIV_Msk,      CLK_UARTDIV0_UART1DIV_Pos,
    UART2_MODULE,   (uint32_t)&CLK->UARTDIV0,   CLK_UARTDIV0_UART2DIV_Msk,      CLK_UARTDIV0_UART2DIV_Pos,
    UART3_MODULE,   (uint32_t)&CLK->UARTDIV0,   CLK_UARTDIV0_UART3DIV_Msk,      CLK_UARTDIV0_UART3DIV_Pos,
    UART4_MODULE,   (uint32_t)&CLK->UARTDIV0,   CLK_UARTDIV0_UART4DIV_Msk,      CLK_UARTDIV0_UART4DIV_Pos,
    UART5_MODULE,   (uint32_t)&CLK->UARTDIV0,   CLK_UARTDIV0_UART5DIV_Msk,      CLK_UARTDIV0_UART5DIV_Pos,
//    UART6_MODULE,   (uint32_t)&CLK->UARTDIV0,   CLK_UARTDIV0_UART6DIV_Msk,      CLK_UARTDIV0_UART6DIV_Pos,
    UART7_MODULE,   (uint32_t)&CLK->UARTDIV0,   CLK_UARTDIV0_UART7DIV_Msk,      CLK_UARTDIV0_UART7DIV_Pos,
    UART8_MODULE,   (uint32_t)&CLK->UARTDIV1,   CLK_UARTDIV1_UART8DIV_Msk,      CLK_UARTDIV1_UART8DIV_Pos,
    UART9_MODULE,   (uint32_t)&CLK->UARTDIV1,   CLK_UARTDIV1_UART9DIV_Msk,      CLK_UARTDIV1_UART9DIV_Pos,
    USBD0_MODULE,   (uint32_t)&CLK->USBDIV,     CLK_USBDIV_USBDIV_Msk,          CLK_USBDIV_USBDIV_Pos,
};
 
void TestFunc_CLK_SetModuleClock()
{
    uint16_t u16SrcSelIdx;  //clock source
    uint32_t u32TestClkDiv; //clock divider
    
    //wait UART print message finish before test
    UART_WAIT_TX_EMPTY(UART6);
    
    for(u16SrcSelIdx = 0; u16SrcSelIdx < (sizeof(au64ModuleClkSrcSel) / sizeof(uint64_t)) ;u16SrcSelIdx += 4)
    {
        CLK_SetModuleClock(au64ModuleClkSrcSel[u16SrcSelIdx],au64ModuleClkSrcSel[u16SrcSelIdx+3],MODULE_NoMsk);
        CU_ASSERT((inp32(au64ModuleClkSrcSel[u16SrcSelIdx+1]) & au64ModuleClkSrcSel[u16SrcSelIdx+2]) == au64ModuleClkSrcSel[u16SrcSelIdx+3]);
        CU_ASSERT(CLK_GetModuleClockSource(au64ModuleClkSrcSel[u16SrcSelIdx]) == (uint32_t)(au64ModuleClkSrcSel[u16SrcSelIdx+3] >> MODULE_CLKSEL_Pos(au64ModuleClkSrcSel[u16SrcSelIdx])));
//        printf("\n");
//        printf("address = 0x%08x\n",(uint32_t)(au64ModuleClkSrcSel[u16SrcSelIdx+1]));
//        printf("inp32([u16SrcSelIdx+1]) = 0x%08x\n",(uint32_t)inp32(au64ModuleClkSrcSel[u16SrcSelIdx+1]));
//        printf("[u16SrcSelIdx+2]        = 0x%08x\n",(uint32_t)au64ModuleClkSrcSel[u16SrcSelIdx+2]);
//        printf("[u16SrcSelIdx+3]        = 0x%08x\n",(uint32_t)au64ModuleClkSrcSel[u16SrcSelIdx+3]);
    }
    
    for(u16SrcSelIdx = 0; u16SrcSelIdx < (sizeof(au64ModuleClkSrcDiv) / sizeof(uint64_t)) ;u16SrcSelIdx += 4)
    {
        for(u32TestClkDiv = 0; u32TestClkDiv <= (au64ModuleClkSrcDiv[u16SrcSelIdx+2]>>au64ModuleClkSrcDiv[u16SrcSelIdx+3]); u32TestClkDiv++)
        {
            CLK_SetModuleClock(au64ModuleClkSrcDiv[u16SrcSelIdx],MODULE_NoMsk, u32TestClkDiv << au64ModuleClkSrcDiv[u16SrcSelIdx+3]);
            CU_ASSERT((inp32(au64ModuleClkSrcDiv[u16SrcSelIdx+1]) & au64ModuleClkSrcDiv[u16SrcSelIdx+2]) == (u32TestClkDiv << au64ModuleClkSrcDiv[u16SrcSelIdx+3]));
            CU_ASSERT(CLK_GetModuleClockDivider(au64ModuleClkSrcDiv[u16SrcSelIdx]) == u32TestClkDiv);
//            printf("\n");
//            printf("inp32([u16SrcSelIdx+1])              = 0x%08x\n",(uint32_t)inp32(au64ModuleClkSrcDiv[u16SrcSelIdx+1]));
//            printf("[u16SrcSelIdx+2]                     = 0x%08x\n",(uint32_t)au64ModuleClkSrcDiv[u16SrcSelIdx+2]);
//            printf("(u32TestClkDiv << [u16SrcSelIdx+3])  = 0x%08x\n",(uint32_t)(u32TestClkDiv << au64ModuleClkSrcDiv[u16SrcSelIdx+3])); 
        }
    }
}

void TestFunc_CLK_SystemClockUpdate()
{
    CLK_EnableXtalRC(CLK_SRCCTL_HIRCEN_Msk);
    CLK_WaitClockReady(CLK_STATUS_HIRCSTB_Msk);

    CLK_SetSCLK(CLK_SCLKSEL_SCLKSEL_HIRC48M);
    
    CLK_EnableAPLL(CLK_APLLCTL_APLLSRC_HIRC, FREQ_180MHZ, CLK_APLL0_SELECT);

    CLK_SetSCLK(CLK_SCLKSEL_SCLKSEL_APLL0);
 
    CLK_SetCoreClock(FREQ_50MHZ);
    CU_ASSERT(CLK_SystemClockUpdate() == FREQ_50MHZ);

    CLK_SetCoreClock(FREQ_100MHZ);
    CU_ASSERT(CLK_SystemClockUpdate() == FREQ_100MHZ);

    CLK_SetCoreClock(FREQ_100MHZ);
    CU_ASSERT(CLK_SystemClockUpdate() == FREQ_100MHZ);

    CLK_SetCoreClock(FREQ_180MHZ);
    CU_ASSERT(CLK_SystemClockUpdate() == FREQ_180MHZ);
}

void TestFunc_CLK_SetBusClock()
{
    CLK_SetBusClock(CLK_SCLKSEL_SCLKSEL_HIRC, NA, NA);
    CU_ASSERT(SystemCoreClock == __HIRC);
    
    CLK_SetBusClock(CLK_SCLKSEL_SCLKSEL_MIRC, NA, NA);
    CU_ASSERT(SystemCoreClock == CLK_GetMIRCFreq());
    
    CLK_SetBusClock(CLK_SCLKSEL_SCLKSEL_HIRC48M, NA, NA);
    CU_ASSERT(SystemCoreClock == __HIRC48M);
    
    CLK_SetBusClock(CLK_SCLKSEL_SCLKSEL_HXT, NA, NA);
    CU_ASSERT(SystemCoreClock == __HXT);
    
    CLK_SetBusClock(CLK_SCLKSEL_SCLKSEL_APLL0, CLK_APLLCTL_APLLSRC_HIRC, FREQ_50MHZ);
    CU_ASSERT(SystemCoreClock == CLK_GetAPLL0ClockFreq());
    
    CLK_SetBusClock(CLK_SCLKSEL_SCLKSEL_APLL0, CLK_APLLCTL_APLLSRC_HIRC, FREQ_100MHZ);
    CU_ASSERT(SystemCoreClock == CLK_GetAPLL0ClockFreq());
    
    CLK_SetBusClock(CLK_SCLKSEL_SCLKSEL_APLL0, CLK_APLLCTL_APLLSRC_HIRC, FREQ_150MHZ);
    CU_ASSERT(SystemCoreClock == CLK_GetAPLL0ClockFreq());
    
    CLK_SetBusClock(CLK_SCLKSEL_SCLKSEL_APLL0, CLK_APLLCTL_APLLSRC_HIRC, FREQ_200MHZ);
    CU_ASSERT(SystemCoreClock == CLK_GetAPLL0ClockFreq());
}

void TestFunc_CLK_EnableSysTick()
{
    uint32_t u32TickCount[4] = {0, 0x555555, 0xAAAAAA, 0xFFFFFF};

    uint8_t u8SysTickClkSrcSelIdx;
    uint8_t u8TickCountIdx;

    /* Test loop */
    for (u8SysTickClkSrcSelIdx = 0; u8SysTickClkSrcSelIdx < (sizeof(au32SysTickClkSrcSel) / sizeof(uint32_t)); u8SysTickClkSrcSelIdx++)
    {
        for (u8TickCountIdx = 0; u8TickCountIdx < 4; u8TickCountIdx++)
        {
            /* Enable Systick, clock source from external clock */
            CLK_EnableSysTick(au32SysTickClkSrcSel[u8SysTickClkSrcSelIdx], u32TickCount[u8TickCountIdx]);
            CU_ASSERT((CLK->STSEL & CLK_STSEL_ST0SEL_Msk) == au32SysTickClkSrcSel[u8SysTickClkSrcSelIdx]);
            CU_ASSERT((SysTick->CTRL & (SysTick_CTRL_TICKINT_Msk | SysTick_CTRL_ENABLE_Msk)) == (SysTick_CTRL_TICKINT_Msk | SysTick_CTRL_ENABLE_Msk));
            CU_ASSERT((SysTick->CTRL & SysTick_CTRL_CLKSOURCE_Msk) == 0);
            CU_ASSERT(SysTick->LOAD == u32TickCount[u8TickCountIdx]);

            /* Disable Systick */
            CLK_DisableSysTick();
            CU_ASSERT(SysTick->CTRL == 0);

            /* Enable Systick, clock source from ACLK(core clock) */
            CLK_EnableSysTick(CLK_STSEL_ACLK, u32TickCount[u8TickCountIdx]);
            CU_ASSERT((SysTick->CTRL & (SysTick_CTRL_TICKINT_Msk | SysTick_CTRL_ENABLE_Msk)) == (SysTick_CTRL_TICKINT_Msk | SysTick_CTRL_ENABLE_Msk));
            CU_ASSERT((SysTick->CTRL & SysTick_CTRL_CLKSOURCE_Msk) == SysTick_CTRL_CLKSOURCE_Msk);
            CU_ASSERT(SysTick->LOAD == u32TickCount[u8TickCountIdx]);

            /* Disable Systick */
            CLK_DisableSysTick();
            CU_ASSERT(SysTick->CTRL == 0);
        }
    }    
}
void TestFunc_CLK_TestConstant()
{
    uint64_t u64ConstantPara;   //Constant Parameter
    
    CU_ASSERT(FREQ_1MHZ     == 1000000UL);
    
    CU_ASSERT(FREQ_2MHZ     == 2000000UL);
    
    CU_ASSERT(FREQ_4MHZ     == 4000000UL);
    
    CU_ASSERT(FREQ_8MHZ     == 8000000UL);
    
    CU_ASSERT(FREQ_12MHZ    == 12000000UL);
    
    CU_ASSERT(FREQ_24MHZ    == 24000000UL);
    
    CU_ASSERT(FREQ_25MHZ    == 25000000UL);
    
    CU_ASSERT(FREQ_40MHZ    == 40000000UL);
    
    CU_ASSERT(FREQ_50MHZ    == 50000000UL);

    CU_ASSERT(FREQ_72MHZ    == 72000000UL);
    
    CU_ASSERT(FREQ_75MHZ    == 75000000UL);
    
    CU_ASSERT(FREQ_80MHZ    == 80000000UL);

    CU_ASSERT(FREQ_90MHZ    == 90000000UL);
    
    CU_ASSERT(FREQ_100MHZ   == 100000000UL);
    
    CU_ASSERT(FREQ_120MHZ   == 120000000UL);
    
    CU_ASSERT(FREQ_125MHZ   == 125000000UL);

    CU_ASSERT(FREQ_144MHZ   == 144000000UL);
    
    CU_ASSERT(FREQ_150MHZ   == 150000000UL);
    
    CU_ASSERT(FREQ_160MHZ   == 160000000UL);
    
    CU_ASSERT(FREQ_175MHZ   == 175000000UL);
    
    CU_ASSERT(FREQ_180MHZ   == 180000000UL);
    
    CU_ASSERT(FREQ_192MHZ   == 192000000UL);
    
    CU_ASSERT(FREQ_200MHZ   == 200000000UL);
    
    CU_ASSERT(FREQ_240MHZ   == 240000000UL);

    CU_ASSERT(FREQ_384MHZ   == 384000000UL);
    
    CU_ASSERT(FREQ_500MHZ   == 500000000UL);
    
    for (u64ConstantPara = 1; u64ConstantPara <= 15; u64ConstantPara++)
    {
        CU_ASSERT(CLK_APLLCTL_NR(u64ConstantPara) == ((u64ConstantPara-1) << CLK_APLL0CTL_INDIV_Pos));
    }

    for (u64ConstantPara = 2; u64ConstantPara <= 63; u64ConstantPara++)
    {
        CU_ASSERT(CLK_APLLCTL_NF(u64ConstantPara) == (u64ConstantPara-2));
    }    
}

void TestFunc_CLK_TestMacro()
{
    uint64_t u64MacroPara;   //Macro Parameter
    
    for(u64MacroPara = 0; u64MacroPara <= 0xFF; u64MacroPara++)
    {
        CU_ASSERT(MODULE_CLKCTL(MODULE_CLKCTL_ENC(u64MacroPara)) == u64MacroPara);
    }

    for(u64MacroPara = 0; u64MacroPara <= 0xFF; u64MacroPara++)
    {
        CU_ASSERT(MODULE_CLKSEL(MODULE_CLKSEL_ENC(u64MacroPara)) == u64MacroPara);
    }

    for(u64MacroPara = 0; u64MacroPara <= 0xFF; u64MacroPara++)
    {
        CU_ASSERT(MODULE_CLKDIV(MODULE_CLKDIV_ENC(u64MacroPara)) == u64MacroPara);
    }    
    
    for(u64MacroPara = 0; u64MacroPara <= 0xFF; u64MacroPara++)
    {
        CU_ASSERT(MODULE_CLKSEL_Msk(MODULE_CLKSEL_Msk_ENC(u64MacroPara)) == u64MacroPara);
    }    

    for(u64MacroPara = 0; u64MacroPara <= 0xFF; u64MacroPara++)
    {
        CU_ASSERT(MODULE_CLKDIV_Msk(MODULE_CLKDIV_Msk_ENC(u64MacroPara)) == u64MacroPara);
    }    
    
    for(u64MacroPara = 0; u64MacroPara <= 0x1F; u64MacroPara++)
    {
        CU_ASSERT(MODULE_CLKEN_Pos(MODULE_CLKEN_Pos_ENC(u64MacroPara)) == u64MacroPara);
    }    
    
    for(u64MacroPara = 0; u64MacroPara <= 0x1F; u64MacroPara++)
    {
        CU_ASSERT(MODULE_CLKSEL_Pos(MODULE_CLKSEL_Pos_ENC(u64MacroPara)) == u64MacroPara);
    }    
    
    for(u64MacroPara = 0; u64MacroPara <= 0x1F; u64MacroPara++)
    {
        CU_ASSERT(MODULE_CLKDIV_Pos(MODULE_CLKDIV_Pos_ENC(u64MacroPara)) == u64MacroPara);
    }
    
    CU_ASSERT(MODULE_NoMsk == NA);
    
    CLK_SetSCLK(CLK_SCLKSEL_SCLKSEL_HIRC);
    
    CLK->SRCCTL &= ~CLK_SRCCTL_APLL0EN_Msk;
    CLK->APLL0CTL =  CLK_APLLCTL_72MHz;
    CLK->SRCCTL |= CLK_SRCCTL_APLL0EN_Msk;
    CU_ASSERT(CLK_GetAPLL0ClockFreq() == FREQ_72MHZ);
    
    CLK->SRCCTL &= ~CLK_SRCCTL_APLL0EN_Msk;
    CLK->APLL0CTL =  CLK_APLLCTL_80MHz;
    CLK->SRCCTL |= CLK_SRCCTL_APLL0EN_Msk;
    CU_ASSERT(CLK_GetAPLL0ClockFreq() == FREQ_80MHZ);
    
    CLK->SRCCTL &= ~CLK_SRCCTL_APLL0EN_Msk;
    CLK->APLL0CTL =  CLK_APLLCTL_144MHz;
    CLK->SRCCTL |= CLK_SRCCTL_APLL0EN_Msk;
    CU_ASSERT(CLK_GetAPLL0ClockFreq() == FREQ_144MHZ);
    
    CLK->SRCCTL &= ~CLK_SRCCTL_APLL0EN_Msk;
    CLK->APLL0CTL =  CLK_APLLCTL_160MHz;
    CLK->SRCCTL |= CLK_SRCCTL_APLL0EN_Msk;
    CU_ASSERT(CLK_GetAPLL0ClockFreq() == FREQ_160MHZ);
    
    CLK->SRCCTL &= ~CLK_SRCCTL_APLL0EN_Msk;
    CLK->APLL0CTL =  CLK_APLLCTL_192MHz;
    CLK->SRCCTL |= CLK_SRCCTL_APLL0EN_Msk;
    CU_ASSERT(CLK_GetAPLL0ClockFreq() == FREQ_192MHZ);
    
    CLK->SRCCTL &= ~CLK_SRCCTL_APLL0EN_Msk;
    CLK->APLL0CTL =  CLK_APLLCTL_200MHz;
    CLK->SRCCTL |= CLK_SRCCTL_APLL0EN_Msk;
    CU_ASSERT(CLK_GetAPLL0ClockFreq() == FREQ_200MHZ);
    
    CLK->SRCCTL &= ~CLK_SRCCTL_APLL0EN_Msk;
    CLK->APLL0CTL =  CLK_APLLCTL_384MHz;
    CLK->SRCCTL |= CLK_SRCCTL_APLL0EN_Msk;
    CU_ASSERT(CLK_GetAPLL0ClockFreq() == FREQ_384MHZ);
    
    CLK->SRCCTL &= ~CLK_SRCCTL_APLL0EN_Msk;
    CLK->APLL0CTL =  CLK_APLLCTL_180MHz;
    CLK->SRCCTL |= CLK_SRCCTL_APLL0EN_Msk;
    CU_ASSERT(CLK_GetAPLL0ClockFreq() == FREQ_180MHZ);
    
    CLK_SetSCLK(CLK_SCLKSEL_SCLKSEL_APLL0);

}

CU_SuiteInfo CLKSuites[] = {
    { "CLK Function Test", CLK_Test_Init, CLK_Test_Clean, NULL, NULL, CLK_FuncTest },
    { "CLK Constant Test", CLK_Test_Init, CLK_Test_Clean, NULL, NULL, CLK_ConstTest },
    { "CLK Macro Test", CLK_Test_Init, CLK_Test_Clean, NULL, NULL, CLK_MacroTest },
    CU_SUITE_INFO_NULL
};

CU_TestInfo  CLK_ConstTest[] = {
    {"Constant.", TestFunc_CLK_TestConstant},
    CU_TEST_INFO_NULL
};

CU_TestInfo  CLK_MacroTest[] = {
    {"Macro.", TestFunc_CLK_TestMacro},
    CU_TEST_INFO_NULL
};

CU_TestInfo  CLK_FuncTest[] = {
    {"CLK_Enable/DisableModuleClock.",  TestFunc_CLK_EnableModuleClock},
    {"CLK_GetFrequency.",               TestFunc_CLK_GetFreq},
    {"CLK_Enable/DisableXtalRC.",       TestFunc_CLK_EnableXtalRC},
    {"CLK_Enable/DisableMIRC.",         TestFunc_CLK_EnableMIRC},
    {"CLK_CLK_SetCoreClock.",           TestFunc_CLK_SetCoreClock},
    {"CLK_Enable/DisableCKO.",          TestFunc_CLK_EnableCKO},
    {"CLK_Enable/Disable.",             TestFunc_CLK_EnableSysTick },
    {"CLK_SetSysTickClockSrc.",         TestFunc_CLK_SetSysTickClockSrc},
    {"CLK_SetModuleClock.",             TestFunc_CLK_SetModuleClock},
    {"CLK_SystemClockUpdate.",          TestFunc_CLK_SystemClockUpdate },
    {"CLK_SetBusClock.",                TestFunc_CLK_SetBusClock },    
    CU_TEST_INFO_NULL
};
