/******************************************************************************
* @file    pmc_cunit.c
* @version V1.00
* @brief   CUnit test pmc
*
* SPDX-License-Identifier: Apache-2.0
* @copyright (C) 2023 Nuvoton Technology Corp. All rights reserved.
*****************************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "NuMicro.h"
#include "CUnit.h"
#include "Console.h"
#include "pmc_cunit.h"


int pmc_Test_Init(void)
{
    return 0;
}
int pmc_Test_Clean(void)
{
    return 0;
}

void WDT0_IRQHandler(void)
{
    /* Clear WDT time-out interrupt and wake-up flag */
    WDT_CLEAR_TIMEOUT_INT_FLAG(WDT0);
    WDT_CLEAR_TIMEOUT_WAKEUP_FLAG(WDT0);
    //printf(" WDT INT!!!\n");
}

void TestFunc_PMC_PowerDown(void)
{
    /* Enable Internal RC 12MHz clock */
    CLK_EnableXtalRC(CLK_SRCCTL_LIRCEN_Msk);

    /* Waiting for Internal RC clock ready */
    CLK_WaitClockReady(CLK_STATUS_LIRCSTB_Msk);
    
    CLK_EnableModuleClock(WDT0_MODULE);
    CLK_SetModuleClock(WDT0_MODULE, CLK_WDTSEL_WDT0SEL_LIRC, 0);

    /* Enable WDT NVIC */
    NVIC_EnableIRQ(WDT0_IRQn);
    
    /* Enable WDT wake-up function and select time-out interval to 2^14 * WDT clock then start WDT counting */
    WDT_Open(WDT0, WDT_TIMEOUT_2POW4, NULL, FALSE, TRUE);

    /* Enable WDT interrupt function */
    WDT_EnableInt(WDT0);

    /* System entry into Power-down Mode */
    PMC->INTEN |= PMC_INTEN_PDWKIEN_Msk;

    UART_WAIT_TX_EMPTY(UART0);

    PMC_SetPowerDownMode(PMC_NPD0,PMC_PLCTL_PLSEL_PL0);    
    PMC_PowerDown();

    CU_ASSERT(PMC->INTSTS & PMC_INTSTS_PDWKIF_Msk);

    /* Clear Power-down wake-up interrupt flag */
    PMC->INTSTS |= PMC_INTSTS_CLRWK_Msk;

    /* Disable WDT counting */
    WDT_Close(WDT0);
}

void TestFunc_PMC_Idle(void)
{

    CLK_EnableXtalRC(CLK_SRCCTL_LIRCEN_Msk);
    CLK_WaitClockReady(CLK_STATUS_LIRCSTB_Msk);
    
    CLK_EnableModuleClock(WDT0_MODULE);
    CLK_SetModuleClock(WDT0_MODULE, CLK_WDTSEL_WDT0SEL_LIRC, 0);

    /* Enable WDT NVIC */
    NVIC_EnableIRQ(WDT0_IRQn);

    /* Enable WDT wake-up function and select time-out interval to 2^14 * WDT clock then start WDT counting */
    WDT_Open(WDT0, WDT_TIMEOUT_2POW4, NULL, FALSE, FALSE);

    /* Enable WDT interrupt function */
    WDT_EnableInt(WDT0);

    UART_WAIT_TX_EMPTY(UART0);

    PMC_Idle();

    /* Disable WDT counting */
    WDT_Close(WDT0);    
}

void TestFunc_PMC_SetPowerLevel(void)
{
    PMC_SetPowerLevel(PMC_PLCTL_PLSEL_PL0);
    CU_ASSERT((PMC->PLCTL & PMC_PLCTL_PLSEL_Msk) >> PMC_PLCTL_PLSEL_Pos == 0x0UL);
    CU_ASSERT((PMC->PLSTS & PMC_PLSTS_PLSTATUS_Msk) == PMC_PLSTS_PLSTATUS_PL0);
    
    PMC_SetPowerLevel(PMC_PLCTL_PLSEL_PL1);
    CU_ASSERT((PMC->PLCTL & PMC_PLCTL_PLSEL_Msk) >> PMC_PLCTL_PLSEL_Pos == 0x1UL);
    CU_ASSERT((PMC->PLSTS & PMC_PLSTS_PLSTATUS_Msk) == PMC_PLSTS_PLSTATUS_PL1);
    
    PMC_SetPowerLevel(PMC_PLCTL_PLSEL_PL2);
    CU_ASSERT((PMC->PLCTL & PMC_PLCTL_PLSEL_Msk) >> PMC_PLCTL_PLSEL_Pos == 0x2UL);
    CU_ASSERT((PMC->PLSTS & PMC_PLSTS_PLSTATUS_Msk) == PMC_PLSTS_PLSTATUS_PL2);
    
    PMC_SetPowerLevel(PMC_PLCTL_PLSEL_PL3);
    CU_ASSERT((PMC->PLCTL & PMC_PLCTL_PLSEL_Msk) >> PMC_PLCTL_PLSEL_Pos == 0x3UL);
    CU_ASSERT((PMC->PLSTS & PMC_PLSTS_PLSTATUS_Msk) == PMC_PLSTS_PLSTATUS_PL3);
}

void TestFunc_PMC_SetPowerRegulator(void)
{
    SYS->MEGPMCTL |= 0x00080000; //for Palladium behavior model
    PMC_SetPowerRegulator(PMC_VRCTL_MVRS_LDO);
    CU_ASSERT((PMC->VRCTL & PMC_VRCTL_MVRS_Msk) >> PMC_VRCTL_MVRS_Pos == 0x0UL);
    CU_ASSERT((PMC->VRSTS & PMC_VRSTS_CURMVR_Msk) == PMC_VRSTS_CURMVR_LDO);

    PMC_SetPowerRegulator(PMC_VRCTL_MVRS_DCDC);
    CU_ASSERT((PMC->VRCTL & PMC_VRCTL_MVRS_Msk) >> PMC_VRCTL_MVRS_Pos == 0x1UL);
    CU_ASSERT((PMC->VRSTS & PMC_VRSTS_CURMVR_Msk) == PMC_VRSTS_CURMVR_DCDC);
}

void TestFunc_PMC_SetSRAMPowerMode(void)
{
    //Test in Palladium enviroment
    //SRAM0
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM0PMS_Msk,PMC_SYSRB0PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM0PMS_Msk)>>PMC_SYSRB0PC_SRAM0PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM0PMS_Msk,PMC_SYSRB0PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM0PMS_Msk)>>PMC_SYSRB0PC_SRAM0PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM0PMS_Msk,PMC_SYSRB0PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM0PMS_Msk)>>PMC_SYSRB0PC_SRAM0PMS_Pos == 0x2UL);

    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM1PMS_Msk,PMC_SYSRB0PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM1PMS_Msk)>>PMC_SYSRB0PC_SRAM1PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM1PMS_Msk,PMC_SYSRB0PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM1PMS_Msk)>>PMC_SYSRB0PC_SRAM1PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM1PMS_Msk,PMC_SYSRB0PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM1PMS_Msk)>>PMC_SYSRB0PC_SRAM1PMS_Pos == 0x2UL);
    
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM2PMS_Msk,PMC_SYSRB0PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM2PMS_Msk)>>PMC_SYSRB0PC_SRAM2PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM2PMS_Msk,PMC_SYSRB0PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM2PMS_Msk)>>PMC_SYSRB0PC_SRAM2PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM2PMS_Msk,PMC_SYSRB0PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM2PMS_Msk)>>PMC_SYSRB0PC_SRAM2PMS_Pos == 0x2UL);
    
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM3PMS_Msk,PMC_SYSRB0PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM3PMS_Msk)>>PMC_SYSRB0PC_SRAM3PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM3PMS_Msk,PMC_SYSRB0PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM3PMS_Msk)>>PMC_SYSRB0PC_SRAM3PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM3PMS_Msk,PMC_SYSRB0PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM3PMS_Msk)>>PMC_SYSRB0PC_SRAM3PMS_Pos == 0x2UL);  

    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM4PMS_Msk,PMC_SYSRB0PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM4PMS_Msk)>>PMC_SYSRB0PC_SRAM4PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM4PMS_Msk,PMC_SYSRB0PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM4PMS_Msk)>>PMC_SYSRB0PC_SRAM4PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM4PMS_Msk,PMC_SYSRB0PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM4PMS_Msk)>>PMC_SYSRB0PC_SRAM4PMS_Pos == 0x2UL);  

    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM5PMS_Msk,PMC_SYSRB0PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM5PMS_Msk)>>PMC_SYSRB0PC_SRAM5PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM5PMS_Msk,PMC_SYSRB0PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM5PMS_Msk)>>PMC_SYSRB0PC_SRAM5PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM5PMS_Msk,PMC_SYSRB0PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM5PMS_Msk)>>PMC_SYSRB0PC_SRAM5PMS_Pos == 0x2UL);  

    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM6PMS_Msk,PMC_SYSRB0PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM6PMS_Msk)>>PMC_SYSRB0PC_SRAM6PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM6PMS_Msk,PMC_SYSRB0PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM6PMS_Msk)>>PMC_SYSRB0PC_SRAM6PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM6PMS_Msk,PMC_SYSRB0PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM6PMS_Msk)>>PMC_SYSRB0PC_SRAM6PMS_Pos == 0x2UL);

    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM7PMS_Msk,PMC_SYSRB0PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM7PMS_Msk)>>PMC_SYSRB0PC_SRAM7PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM7PMS_Msk,PMC_SYSRB0PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM7PMS_Msk)>>PMC_SYSRB0PC_SRAM7PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB0PC_SRAM7PMS_Msk,PMC_SYSRB0PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB0PC&PMC_SYSRB0PC_SRAM7PMS_Msk)>>PMC_SYSRB0PC_SRAM7PMS_Pos == 0x2UL);
    
    //SRAM1
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM0PMS_Msk,PMC_SYSRB1PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM0PMS_Msk)>>PMC_SYSRB1PC_SRAM0PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM0PMS_Msk,PMC_SYSRB1PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM0PMS_Msk)>>PMC_SYSRB1PC_SRAM0PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM0PMS_Msk,PMC_SYSRB1PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM0PMS_Msk)>>PMC_SYSRB1PC_SRAM0PMS_Pos == 0x2UL);

    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM1PMS_Msk,PMC_SYSRB1PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM1PMS_Msk)>>PMC_SYSRB1PC_SRAM1PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM1PMS_Msk,PMC_SYSRB1PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM1PMS_Msk)>>PMC_SYSRB1PC_SRAM1PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM1PMS_Msk,PMC_SYSRB1PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM1PMS_Msk)>>PMC_SYSRB1PC_SRAM1PMS_Pos == 0x2UL);
    
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM2PMS_Msk,PMC_SYSRB1PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM2PMS_Msk)>>PMC_SYSRB1PC_SRAM2PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM2PMS_Msk,PMC_SYSRB1PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM2PMS_Msk)>>PMC_SYSRB1PC_SRAM2PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM2PMS_Msk,PMC_SYSRB1PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM2PMS_Msk)>>PMC_SYSRB1PC_SRAM2PMS_Pos == 0x2UL);
    
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM3PMS_Msk,PMC_SYSRB1PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM3PMS_Msk)>>PMC_SYSRB1PC_SRAM3PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM3PMS_Msk,PMC_SYSRB1PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM3PMS_Msk)>>PMC_SYSRB1PC_SRAM3PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM3PMS_Msk,PMC_SYSRB1PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM3PMS_Msk)>>PMC_SYSRB1PC_SRAM3PMS_Pos == 0x2UL);  

    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM4PMS_Msk,PMC_SYSRB1PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM4PMS_Msk)>>PMC_SYSRB1PC_SRAM4PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM4PMS_Msk,PMC_SYSRB1PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM4PMS_Msk)>>PMC_SYSRB1PC_SRAM4PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM4PMS_Msk,PMC_SYSRB1PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM4PMS_Msk)>>PMC_SYSRB1PC_SRAM4PMS_Pos == 0x2UL);  

    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM5PMS_Msk,PMC_SYSRB1PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM5PMS_Msk)>>PMC_SYSRB1PC_SRAM5PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM5PMS_Msk,PMC_SYSRB1PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM5PMS_Msk)>>PMC_SYSRB1PC_SRAM5PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM5PMS_Msk,PMC_SYSRB1PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM5PMS_Msk)>>PMC_SYSRB1PC_SRAM5PMS_Pos == 0x2UL);  

    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM6PMS_Msk,PMC_SYSRB1PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM6PMS_Msk)>>PMC_SYSRB1PC_SRAM6PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM6PMS_Msk,PMC_SYSRB1PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM6PMS_Msk)>>PMC_SYSRB1PC_SRAM6PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM6PMS_Msk,PMC_SYSRB1PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM6PMS_Msk)>>PMC_SYSRB1PC_SRAM6PMS_Pos == 0x2UL);

    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM7PMS_Msk,PMC_SYSRB1PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM7PMS_Msk)>>PMC_SYSRB1PC_SRAM7PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM7PMS_Msk,PMC_SYSRB1PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM7PMS_Msk)>>PMC_SYSRB1PC_SRAM7PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB1PC_SRAM7PMS_Msk,PMC_SYSRB1PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB1PC&PMC_SYSRB1PC_SRAM7PMS_Msk)>>PMC_SYSRB1PC_SRAM7PMS_Pos == 0x2UL);
        
    //SRAM2
    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM0PMS_Msk,PMC_SYSRB2PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM0PMS_Msk)>>PMC_SYSRB2PC_SRAM0PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM0PMS_Msk,PMC_SYSRB2PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM0PMS_Msk)>>PMC_SYSRB2PC_SRAM0PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM0PMS_Msk,PMC_SYSRB2PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM0PMS_Msk)>>PMC_SYSRB2PC_SRAM0PMS_Pos == 0x2UL);

    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM1PMS_Msk,PMC_SYSRB2PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM1PMS_Msk)>>PMC_SYSRB2PC_SRAM1PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM1PMS_Msk,PMC_SYSRB2PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM1PMS_Msk)>>PMC_SYSRB2PC_SRAM1PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM1PMS_Msk,PMC_SYSRB2PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM1PMS_Msk)>>PMC_SYSRB2PC_SRAM1PMS_Pos == 0x2UL);
    
    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM2PMS_Msk,PMC_SYSRB2PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM2PMS_Msk)>>PMC_SYSRB2PC_SRAM2PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM2PMS_Msk,PMC_SYSRB2PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM2PMS_Msk)>>PMC_SYSRB2PC_SRAM2PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM2PMS_Msk,PMC_SYSRB2PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM2PMS_Msk)>>PMC_SYSRB2PC_SRAM2PMS_Pos == 0x2UL);
    
    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM3PMS_Msk,PMC_SYSRB2PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM3PMS_Msk)>>PMC_SYSRB2PC_SRAM3PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM3PMS_Msk,PMC_SYSRB2PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM3PMS_Msk)>>PMC_SYSRB2PC_SRAM3PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM3PMS_Msk,PMC_SYSRB2PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM3PMS_Msk)>>PMC_SYSRB2PC_SRAM3PMS_Pos == 0x2UL);  

    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM4PMS_Msk,PMC_SYSRB2PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM4PMS_Msk)>>PMC_SYSRB2PC_SRAM4PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM4PMS_Msk,PMC_SYSRB2PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM4PMS_Msk)>>PMC_SYSRB2PC_SRAM4PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB2PC_SRAM4PMS_Msk,PMC_SYSRB2PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB2PC&PMC_SYSRB2PC_SRAM4PMS_Msk)>>PMC_SYSRB2PC_SRAM4PMS_Pos == 0x2UL);  

    //SRAM3
    PMC_SetSRAMPowerMode(PMC_SYSRB3PC_SRAM0PMS_Msk,PMC_SYSRB3PC_SRAM_NORMAL);
    CU_ASSERT((PMC->SYSRB3PC&PMC_SYSRB3PC_SRAM0PMS_Msk)>>PMC_SYSRB3PC_SRAM0PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB3PC_SRAM0PMS_Msk,PMC_SYSRB3PC_SRAM_RETENTION);
    CU_ASSERT((PMC->SYSRB3PC&PMC_SYSRB3PC_SRAM0PMS_Msk)>>PMC_SYSRB3PC_SRAM0PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_SYSRB3PC_SRAM0PMS_Msk,PMC_SYSRB3PC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->SYSRB3PC&PMC_SYSRB3PC_SRAM0PMS_Msk)>>PMC_SYSRB3PC_SRAM0PMS_Pos == 0x2UL);

    //LPSRAM
    PMC_SetSRAMPowerMode(PMC_LPSYSRPC_SRAM0PMS_Msk,PMC_LPSYSRPC_SRAM_NORMAL);
    CU_ASSERT((PMC->LPSYSRPC&PMC_LPSYSRPC_SRAM0PMS_Msk)>>PMC_LPSYSRPC_SRAM0PMS_Pos == 0x0UL);
    PMC_SetSRAMPowerMode(PMC_LPSYSRPC_SRAM0PMS_Msk,PMC_LPSYSRPC_SRAM_RETENTION);
    CU_ASSERT((PMC->LPSYSRPC&PMC_LPSYSRPC_SRAM0PMS_Msk)>>PMC_LPSYSRPC_SRAM0PMS_Pos == 0x1UL);
    PMC_SetSRAMPowerMode(PMC_LPSYSRPC_SRAM0PMS_Msk,PMC_LPSYSRPC_SRAM_POWER_SHUT_DOWN);
    CU_ASSERT((PMC->LPSYSRPC&PMC_LPSYSRPC_SRAM0PMS_Msk)>>PMC_LPSYSRPC_SRAM0PMS_Pos == 0x2UL);    
}

void TestFunc_PMC_SetPowerDownMode(void)
{
    //Power level settings are ignored in PMC_NPD2/PMC_NPD4/PMC_SPD1/PMC_DPD0/PMC_DPD1.
    
    //NPD0
    PMC_SetPowerDownMode(PMC_NPD0,PMC_PLCTL_PLSEL_PL0);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x1UL);
    
    PMC_SetPowerDownMode(PMC_NPD0,PMC_PLCTL_PLSEL_PL1);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x1UL);
    
    PMC_SetPowerDownMode(PMC_NPD0,PMC_PLCTL_PLSEL_PL2);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x2UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x1UL);
    
    PMC_SetPowerDownMode(PMC_NPD0,PMC_PLCTL_PLSEL_PL3);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x3UL);  
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x1UL);
    
    //NPD1    
    PMC_SetPowerDownMode(PMC_NPD1,PMC_PLCTL_PLSEL_PL0);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    PMC_SetPowerDownMode(PMC_NPD1,PMC_PLCTL_PLSEL_PL1);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    PMC_SetPowerDownMode(PMC_NPD1,PMC_PLCTL_PLSEL_PL2);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x2UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    PMC_SetPowerDownMode(PMC_NPD1,PMC_PLCTL_PLSEL_PL3);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x3UL);  
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    //NPD2
    PMC_SetPowerDownMode(PMC_NPD2,PMC_PLCTL_PLSEL_PL0); 
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    //NPD3
    PMC_SetPowerDownMode(PMC_NPD3,PMC_PLCTL_PLSEL_PL0);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    PMC_SetPowerDownMode(PMC_NPD3,PMC_PLCTL_PLSEL_PL1);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    PMC_SetPowerDownMode(PMC_NPD3,PMC_PLCTL_PLSEL_PL2);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x2UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    PMC_SetPowerDownMode(PMC_NPD3,PMC_PLCTL_PLSEL_PL3);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x3UL);  
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    //NPD4
    PMC_SetPowerDownMode(PMC_NPD4,PMC_PLCTL_PLSEL_PL0);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    //SPD0
    PMC_SetPowerDownMode(PMC_SPD0,PMC_PLCTL_PLSEL_PL0);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    PMC_SetPowerDownMode(PMC_SPD0,PMC_PLCTL_PLSEL_PL1);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    PMC_SetPowerDownMode(PMC_SPD0,PMC_PLCTL_PLSEL_PL2);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x2UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    PMC_SetPowerDownMode(PMC_SPD0,PMC_PLCTL_PLSEL_PL3);
    CU_ASSERT((PMC->PLCTL  & PMC_PLCTL_PLSEL_Msk)    >> PMC_PLCTL_PLSEL_Pos      == 0x3UL);  
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    //SPD1
    PMC_SetPowerDownMode(PMC_SPD1,PMC_PLCTL_PLSEL_PL0);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);
    
    //DPD0
    PMC_SetPowerDownMode(PMC_DPD0,PMC_PLCTL_PLSEL_PL0);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x1UL);
    
    //DPD1
    PMC_SetPowerDownMode(PMC_DPD1,PMC_PLCTL_PLSEL_PL0);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D0PGEN_Msk)  >> PMC_PWRCTL_D0PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D1PGEN_Msk)  >> PMC_PWRCTL_D1PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D2PGEN_Msk)  >> PMC_PWRCTL_D2PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_D3PGEN_Msk)  >> PMC_PWRCTL_D3PGEN_Pos    == 0x1UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_VDROPEN_Msk) >> PMC_PWRCTL_VDROPEN_Pos   == 0x0UL);
    CU_ASSERT((PMC->PWRCTL & PMC_PWRCTL_FWEN_Msk)    >> PMC_PWRCTL_FWEN_Pos      == 0x0UL);    
}

void TestFunc_PMC_EnableWKPIN (void)
{
    //WKPIN0
    PMC_EnableWKPIN(PMC_WKPIN0_RISING);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN0_Msk) >> PMC_PINWKCTL_WKPINEN0_Pos == 0x1UL);
    PMC_EnableWKPIN(PMC_WKPIN0_FALLING);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN0_Msk) >> PMC_PINWKCTL_WKPINEN0_Pos == 0x2UL);    
    PMC_EnableWKPIN(PMC_WKPIN0_BOTHEDGE);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN0_Msk) >> PMC_PINWKCTL_WKPINEN0_Pos == 0x3UL);    
    PMC_DISABLE_WKPIN0();
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN0_Msk) >> PMC_PINWKCTL_WKPINEN0_Pos == 0x0UL);
    
    //WKPIN1    
    PMC_EnableWKPIN(PMC_WKPIN1_RISING);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN1_Msk) >> PMC_PINWKCTL_WKPINEN1_Pos == 0x1UL);
    PMC_EnableWKPIN(PMC_WKPIN1_FALLING);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN1_Msk) >> PMC_PINWKCTL_WKPINEN1_Pos == 0x2UL);
    PMC_EnableWKPIN(PMC_WKPIN1_BOTHEDGE);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN1_Msk) >> PMC_PINWKCTL_WKPINEN1_Pos == 0x3UL);
    PMC_DISABLE_WKPIN1();
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN1_Msk) >> PMC_PINWKCTL_WKPINEN1_Pos == 0x0UL);
    
    //WKPIN2    
    PMC_EnableWKPIN(PMC_WKPIN2_RISING);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN2_Msk) >> PMC_PINWKCTL_WKPINEN2_Pos == 0x1UL);
    PMC_EnableWKPIN(PMC_WKPIN2_FALLING);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN2_Msk) >> PMC_PINWKCTL_WKPINEN2_Pos == 0x2UL);
    PMC_EnableWKPIN(PMC_WKPIN2_BOTHEDGE);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN2_Msk) >> PMC_PINWKCTL_WKPINEN2_Pos == 0x3UL);
    PMC_DISABLE_WKPIN2();
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN2_Msk) >> PMC_PINWKCTL_WKPINEN2_Pos == 0x0UL);
    
    //WKPIN3    
    PMC_EnableWKPIN(PMC_WKPIN3_RISING);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN3_Msk) >> PMC_PINWKCTL_WKPINEN3_Pos == 0x1UL);
    PMC_EnableWKPIN(PMC_WKPIN3_FALLING);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN3_Msk) >> PMC_PINWKCTL_WKPINEN3_Pos == 0x2UL);
    PMC_EnableWKPIN(PMC_WKPIN3_BOTHEDGE);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN3_Msk) >> PMC_PINWKCTL_WKPINEN3_Pos == 0x3UL);
    PMC_DISABLE_WKPIN3();
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN3_Msk) >> PMC_PINWKCTL_WKPINEN3_Pos == 0x0UL);
    
    //WKPIN4    
    PMC_EnableWKPIN(PMC_WKPIN4_RISING);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN4_Msk) >> PMC_PINWKCTL_WKPINEN4_Pos == 0x1UL);
    PMC_EnableWKPIN(PMC_WKPIN4_FALLING);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN4_Msk) >> PMC_PINWKCTL_WKPINEN4_Pos == 0x2UL);
    PMC_EnableWKPIN(PMC_WKPIN4_BOTHEDGE);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN4_Msk) >> PMC_PINWKCTL_WKPINEN4_Pos == 0x3UL);
    PMC_DISABLE_WKPIN4();
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN4_Msk) >> PMC_PINWKCTL_WKPINEN4_Pos == 0x0UL);
    
    //WKPIN5    
    PMC_EnableWKPIN(PMC_WKPIN5_RISING);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN5_Msk) >> PMC_PINWKCTL_WKPINEN5_Pos == 0x1UL);
    PMC_EnableWKPIN(PMC_WKPIN5_FALLING);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN5_Msk) >> PMC_PINWKCTL_WKPINEN5_Pos == 0x2UL);
    PMC_EnableWKPIN(PMC_WKPIN5_BOTHEDGE);
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN5_Msk) >> PMC_PINWKCTL_WKPINEN5_Pos == 0x3UL);
    PMC_DISABLE_WKPIN5();
    CU_ASSERT((PMC->PINWKCTL & PMC_PINWKCTL_WKPINEN5_Msk) >> PMC_PINWKCTL_WKPINEN5_Pos == 0x0UL);
}

/**
 * @brief       Set specified GPIO as wake up source or triggrt source
 * @param[in]   u32Port GPIO port.
 *              - \ref PMC_TGPIN_PA
 *              - \ref PMC_TGPIN_PB
 *              - \ref PMC_TGPIN_PC
 *              - \ref PMC_TGPIN_PD
 * @param[in]   u32Pin The pin of specified GPIO port. It could be 0 ~ 15.
 * @param[in]   u32TriggerType TG pin trigger type
 *              - \ref PMC_TGPIN_RISING
 *              - \ref PMC_TGPIN_FALLING
 *              - \ref PMC_TGPIN_BOTH
 * @param[in]   u32DebounceEn TG pin de-bounce function
 *              - \ref PMC_TGPIN_DEBOUNCEEN
 *              - \ref PMC_TGPIN_DEBOUNCEDIS
 * @param[in]   u32WakeupEn TG Pin wake-up function
 *              - \ref PMC_TGPIN_WAKEUP_ENABLE
 *              - \ref PMC_TGPIN_WAKEUP_DISABLE
 * @details     This function is used to set specified GPIO as trigger or wake up source.
 */
 
void TestFunc_PMC_EnableTGPin(void)
{
    uint32_t TempSel;
    
    //TGP_A
    for(TempSel = 0; TempSel <= 15; TempSel++)
    {
        PMC_EnableTGPin(PMC_TGPIN_PA,TempSel,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
        CU_ASSERT((PMC->GPATGCTL & PMC_GPATGCTL_TGPSEL_Msk) >> PMC_GPATGCTL_TGPSEL_Pos == TempSel);
    }
    PMC_DISABLE_TGPIN_GPA();
    PMC_EnableTGPin(PMC_TGPIN_PA,0,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPATGCTL & PMC_GPATGCTL_TGPREN_Msk) >> PMC_GPATGCTL_TGPREN_Pos == 0x1UL);
    CU_ASSERT((PMC->GPATGCTL & PMC_GPATGCTL_TGPFEN_Msk) >> PMC_GPATGCTL_TGPFEN_Pos == 0x0UL);
    
    PMC_DISABLE_TGPIN_GPA();
    PMC_EnableTGPin(PMC_TGPIN_PA,0,PMC_TGPIN_FALLING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPATGCTL & PMC_GPATGCTL_TGPREN_Msk) >> PMC_GPATGCTL_TGPREN_Pos == 0x0UL);
    CU_ASSERT((PMC->GPATGCTL & PMC_GPATGCTL_TGPFEN_Msk) >> PMC_GPATGCTL_TGPFEN_Pos == 0x1UL);
    
    PMC_DISABLE_TGPIN_GPA();
    PMC_EnableTGPin(PMC_TGPIN_PA,0,PMC_TGPIN_BOTH,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPATGCTL & PMC_GPATGCTL_TGPREN_Msk) >> PMC_GPATGCTL_TGPREN_Pos == 0x1UL);
    CU_ASSERT((PMC->GPATGCTL & PMC_GPATGCTL_TGPFEN_Msk) >> PMC_GPATGCTL_TGPFEN_Pos == 0x1UL);
    
    PMC_DISABLE_TGPIN_GPA();   
    CU_ASSERT((PMC->GPATGCTL & PMC_GPATGCTL_TGPREN_Msk) >> PMC_GPATGCTL_TGPREN_Pos == 0x0UL);
    CU_ASSERT((PMC->GPATGCTL & PMC_GPATGCTL_TGPFEN_Msk) >> PMC_GPATGCTL_TGPFEN_Pos == 0x0UL);

    PMC_EnableTGPin(PMC_TGPIN_PA,0,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEEN,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPATGCTL & PMC_GPATGCTL_TGPDBEN_Msk) >> PMC_GPATGCTL_TGPDBEN_Pos == 0x1UL)
    CU_ASSERT((PMC->GPATGCTL & PMC_GPATGCTL_TGPWKEN_Msk) >> PMC_GPATGCTL_TGPWKEN_Pos == 0x0UL)
    
    PMC_EnableTGPin(PMC_TGPIN_PA,0,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_ENABLE);
    CU_ASSERT((PMC->GPATGCTL & PMC_GPATGCTL_TGPDBEN_Msk) >> PMC_GPATGCTL_TGPDBEN_Pos == 0x0UL)
    CU_ASSERT((PMC->GPATGCTL & PMC_GPATGCTL_TGPWKEN_Msk) >> PMC_GPATGCTL_TGPWKEN_Pos == 0x1UL) 

    //TGP_B
    for(TempSel = 0; TempSel <= 15; TempSel++)
    {
        PMC_EnableTGPin(PMC_TGPIN_PB,TempSel,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
        CU_ASSERT((PMC->GPBTGCTL & PMC_GPBTGCTL_TGPSEL_Msk) >> PMC_GPBTGCTL_TGPSEL_Pos == TempSel);
    }
    PMC_DISABLE_TGPIN_GPB();
    PMC_EnableTGPin(PMC_TGPIN_PB,0,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPBTGCTL & PMC_GPBTGCTL_TGPREN_Msk) >> PMC_GPBTGCTL_TGPREN_Pos == 0x1UL);
    CU_ASSERT((PMC->GPBTGCTL & PMC_GPBTGCTL_TGPFEN_Msk) >> PMC_GPBTGCTL_TGPFEN_Pos == 0x0UL);
    
    PMC_DISABLE_TGPIN_GPB();
    PMC_EnableTGPin(PMC_TGPIN_PB,0,PMC_TGPIN_FALLING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPBTGCTL & PMC_GPBTGCTL_TGPREN_Msk) >> PMC_GPBTGCTL_TGPREN_Pos == 0x0UL);
    CU_ASSERT((PMC->GPBTGCTL & PMC_GPBTGCTL_TGPFEN_Msk) >> PMC_GPBTGCTL_TGPFEN_Pos == 0x1UL);
    
    PMC_DISABLE_TGPIN_GPB();
    PMC_EnableTGPin(PMC_TGPIN_PB,0,PMC_TGPIN_BOTH,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPBTGCTL & PMC_GPBTGCTL_TGPREN_Msk) >> PMC_GPBTGCTL_TGPREN_Pos == 0x1UL);
    CU_ASSERT((PMC->GPBTGCTL & PMC_GPBTGCTL_TGPFEN_Msk) >> PMC_GPBTGCTL_TGPFEN_Pos == 0x1UL);
    
    PMC_DISABLE_TGPIN_GPB();   
    CU_ASSERT((PMC->GPBTGCTL & PMC_GPBTGCTL_TGPREN_Msk) >> PMC_GPBTGCTL_TGPREN_Pos == 0x0UL);
    CU_ASSERT((PMC->GPBTGCTL & PMC_GPBTGCTL_TGPFEN_Msk) >> PMC_GPBTGCTL_TGPFEN_Pos == 0x0UL);

    PMC_EnableTGPin(PMC_TGPIN_PB,0,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEEN,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPBTGCTL & PMC_GPBTGCTL_TGPDBEN_Msk) >> PMC_GPBTGCTL_TGPDBEN_Pos == 0x1UL)
    CU_ASSERT((PMC->GPBTGCTL & PMC_GPBTGCTL_TGPWKEN_Msk) >> PMC_GPBTGCTL_TGPWKEN_Pos == 0x0UL)
    
    PMC_EnableTGPin(PMC_TGPIN_PB,0,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_ENABLE);
    CU_ASSERT((PMC->GPBTGCTL & PMC_GPBTGCTL_TGPDBEN_Msk) >> PMC_GPBTGCTL_TGPDBEN_Pos == 0x0UL)
    CU_ASSERT((PMC->GPBTGCTL & PMC_GPBTGCTL_TGPWKEN_Msk) >> PMC_GPBTGCTL_TGPWKEN_Pos == 0x1UL)
    
    //TGP_C
    for(TempSel = 0; TempSel <= 15; TempSel++)
    {
        PMC_EnableTGPin(PMC_TGPIN_PC,TempSel,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
        CU_ASSERT((PMC->GPCTGCTL & PMC_GPCTGCTL_TGPSEL_Msk) >> PMC_GPCTGCTL_TGPSEL_Pos == TempSel);
    }
    PMC_DISABLE_TGPIN_GPC();
    PMC_EnableTGPin(PMC_TGPIN_PC,0,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPCTGCTL & PMC_GPCTGCTL_TGPREN_Msk) >> PMC_GPCTGCTL_TGPREN_Pos == 0x1UL);
    CU_ASSERT((PMC->GPCTGCTL & PMC_GPCTGCTL_TGPFEN_Msk) >> PMC_GPCTGCTL_TGPFEN_Pos == 0x0UL);
    
    PMC_DISABLE_TGPIN_GPC();
    PMC_EnableTGPin(PMC_TGPIN_PC,0,PMC_TGPIN_FALLING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPCTGCTL & PMC_GPCTGCTL_TGPREN_Msk) >> PMC_GPCTGCTL_TGPREN_Pos == 0x0UL);
    CU_ASSERT((PMC->GPCTGCTL & PMC_GPCTGCTL_TGPFEN_Msk) >> PMC_GPCTGCTL_TGPFEN_Pos == 0x1UL);
    
    PMC_DISABLE_TGPIN_GPC();
    PMC_EnableTGPin(PMC_TGPIN_PC,0,PMC_TGPIN_BOTH,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPCTGCTL & PMC_GPCTGCTL_TGPREN_Msk) >> PMC_GPCTGCTL_TGPREN_Pos == 0x1UL);
    CU_ASSERT((PMC->GPCTGCTL & PMC_GPCTGCTL_TGPFEN_Msk) >> PMC_GPCTGCTL_TGPFEN_Pos == 0x1UL);
    
    PMC_DISABLE_TGPIN_GPC();   
    CU_ASSERT((PMC->GPCTGCTL & PMC_GPCTGCTL_TGPREN_Msk) >> PMC_GPCTGCTL_TGPREN_Pos == 0x0UL);
    CU_ASSERT((PMC->GPCTGCTL & PMC_GPCTGCTL_TGPFEN_Msk) >> PMC_GPCTGCTL_TGPFEN_Pos == 0x0UL);

    PMC_EnableTGPin(PMC_TGPIN_PC,0,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEEN,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPCTGCTL & PMC_GPCTGCTL_TGPDBEN_Msk) >> PMC_GPCTGCTL_TGPDBEN_Pos == 0x1UL)
    CU_ASSERT((PMC->GPCTGCTL & PMC_GPCTGCTL_TGPWKEN_Msk) >> PMC_GPCTGCTL_TGPWKEN_Pos == 0x0UL)
    
    PMC_EnableTGPin(PMC_TGPIN_PC,0,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_ENABLE);
    CU_ASSERT((PMC->GPCTGCTL & PMC_GPCTGCTL_TGPDBEN_Msk) >> PMC_GPCTGCTL_TGPDBEN_Pos == 0x0UL)
    CU_ASSERT((PMC->GPCTGCTL & PMC_GPCTGCTL_TGPWKEN_Msk) >> PMC_GPCTGCTL_TGPWKEN_Pos == 0x1UL)    
    
    //TGP_D
    for(TempSel = 0; TempSel <= 15; TempSel++)
    {
        PMC_EnableTGPin(PMC_TGPIN_PD,TempSel,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
        CU_ASSERT((PMC->GPDTGCTL & PMC_GPDTGCTL_TGPSEL_Msk) >> PMC_GPDTGCTL_TGPSEL_Pos == TempSel);
    }
    PMC_DISABLE_TGPIN_GPD();
    PMC_EnableTGPin(PMC_TGPIN_PD,0,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPDTGCTL & PMC_GPDTGCTL_TGPREN_Msk) >> PMC_GPDTGCTL_TGPREN_Pos == 0x1UL);
    CU_ASSERT((PMC->GPDTGCTL & PMC_GPDTGCTL_TGPFEN_Msk) >> PMC_GPDTGCTL_TGPFEN_Pos == 0x0UL);
    
    PMC_DISABLE_TGPIN_GPD();
    PMC_EnableTGPin(PMC_TGPIN_PD,0,PMC_TGPIN_FALLING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPDTGCTL & PMC_GPDTGCTL_TGPREN_Msk) >> PMC_GPDTGCTL_TGPREN_Pos == 0x0UL);
    CU_ASSERT((PMC->GPDTGCTL & PMC_GPDTGCTL_TGPFEN_Msk) >> PMC_GPDTGCTL_TGPFEN_Pos == 0x1UL);
    
    PMC_DISABLE_TGPIN_GPD();
    PMC_EnableTGPin(PMC_TGPIN_PD,0,PMC_TGPIN_BOTH,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPDTGCTL & PMC_GPDTGCTL_TGPREN_Msk) >> PMC_GPDTGCTL_TGPREN_Pos == 0x1UL);
    CU_ASSERT((PMC->GPDTGCTL & PMC_GPDTGCTL_TGPFEN_Msk) >> PMC_GPDTGCTL_TGPFEN_Pos == 0x1UL);
    
    PMC_DISABLE_TGPIN_GPD();   
    CU_ASSERT((PMC->GPDTGCTL & PMC_GPDTGCTL_TGPREN_Msk) >> PMC_GPDTGCTL_TGPREN_Pos == 0x0UL);
    CU_ASSERT((PMC->GPDTGCTL & PMC_GPDTGCTL_TGPFEN_Msk) >> PMC_GPDTGCTL_TGPFEN_Pos == 0x0UL);

    PMC_EnableTGPin(PMC_TGPIN_PD,0,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEEN,PMC_TGPIN_WAKEUP_DISABLE);
    CU_ASSERT((PMC->GPDTGCTL & PMC_GPDTGCTL_TGPDBEN_Msk) >> PMC_GPDTGCTL_TGPDBEN_Pos == 0x1UL)
    CU_ASSERT((PMC->GPDTGCTL & PMC_GPDTGCTL_TGPWKEN_Msk) >> PMC_GPDTGCTL_TGPWKEN_Pos == 0x0UL)
    
    PMC_EnableTGPin(PMC_TGPIN_PD,0,PMC_TGPIN_RISING,PMC_TGPIN_DEBOUNCEDIS,PMC_TGPIN_WAKEUP_ENABLE);
    CU_ASSERT((PMC->GPDTGCTL & PMC_GPDTGCTL_TGPDBEN_Msk) >> PMC_GPDTGCTL_TGPDBEN_Pos == 0x0UL)
    CU_ASSERT((PMC->GPDTGCTL & PMC_GPDTGCTL_TGPWKEN_Msk) >> PMC_GPDTGCTL_TGPWKEN_Pos == 0x1UL)
}

void TestFunc_PMC_Wait_BusyFlag(void)
{
    CU_ASSERT(PMC_Wait_BusyFlag(PMC_PWRCTL_BUSY_FLAG) == PMC_OK);
    CU_ASSERT(PMC_Wait_BusyFlag(PMC_PLCTL_BUSY_FLAG) == PMC_OK);
    CU_ASSERT(PMC_Wait_BusyFlag(PMC_PLSTS_BUSY_FLAG) == PMC_OK);
    CU_ASSERT(PMC_Wait_BusyFlag(PMC_VRCTL_BUSY_FLAG) == PMC_OK);
    CU_ASSERT(PMC_Wait_BusyFlag(PMC_VRSTS_BUSY_FLAG) == PMC_OK);
    CU_ASSERT(PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG) == PMC_OK);
    CU_ASSERT(PMC_Wait_BusyFlag(PMC_SYSRB0PC_BUSY_FLAG) == PMC_OK);
    CU_ASSERT(PMC_Wait_BusyFlag(PMC_SYSRB1PC_BUSY_FLAG) == PMC_OK);
    CU_ASSERT(PMC_Wait_BusyFlag(PMC_SYSRB2PC_BUSY_FLAG) == PMC_OK);
    CU_ASSERT(PMC_Wait_BusyFlag(PMC_SYSRB3PC_BUSY_FLAG) == PMC_OK);
    CU_ASSERT(PMC_Wait_BusyFlag(PMC_LPSYSRPC_BUSY_FLAG) == PMC_OK);
    CU_ASSERT(PMC_Wait_BusyFlag(PMC_KSRPC_BUSY_FLAG) == PMC_OK);
}

void PMC_Macro_Test(void)
{
    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_SET_STMRWK_INTERVAL(PMC_STMRWKCTL_STMRIS_512);
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMRIS_Msk) >> PMC_STMRWKCTL_STMRIS_Pos == 0x0UL)

    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_SET_STMRWK_INTERVAL(PMC_STMRWKCTL_STMRIS_1024);
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMRIS_Msk) >> PMC_STMRWKCTL_STMRIS_Pos == 0x1UL)    
    
    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_SET_STMRWK_INTERVAL(PMC_STMRWKCTL_STMRIS_2048);
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMRIS_Msk) >> PMC_STMRWKCTL_STMRIS_Pos == 0x2UL)    
  
    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_SET_STMRWK_INTERVAL(PMC_STMRWKCTL_STMRIS_4096);
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMRIS_Msk) >> PMC_STMRWKCTL_STMRIS_Pos == 0x3UL)    
 
    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_SET_STMRWK_INTERVAL(PMC_STMRWKCTL_STMRIS_8192);
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMRIS_Msk) >> PMC_STMRWKCTL_STMRIS_Pos == 0x4UL)    
    
    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_SET_STMRWK_INTERVAL(PMC_STMRWKCTL_STMRIS_16384);
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMRIS_Msk) >> PMC_STMRWKCTL_STMRIS_Pos == 0x5UL)    
    
    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_SET_STMRWK_INTERVAL(PMC_STMRWKCTL_STMRIS_32768);
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMRIS_Msk) >> PMC_STMRWKCTL_STMRIS_Pos == 0x6UL)    
    
    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_SET_STMRWK_INTERVAL(PMC_STMRWKCTL_STMRIS_65536);
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMRIS_Msk) >> PMC_STMRWKCTL_STMRIS_Pos == 0x7UL)    
    
    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_SET_STMRWK_INTERVAL(PMC_STMRWKCTL_STMRIS_131072);
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMRIS_Msk) >> PMC_STMRWKCTL_STMRIS_Pos == 0x8UL)    
    
    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_SET_STMRWK_INTERVAL(PMC_STMRWKCTL_STMRIS_262144);
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMRIS_Msk) >> PMC_STMRWKCTL_STMRIS_Pos == 0x9UL)    
    
    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_SET_STMRWK_INTERVAL(PMC_STMRWKCTL_STMRIS_524288);
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMRIS_Msk) >> PMC_STMRWKCTL_STMRIS_Pos == 0xaUL)    
    
    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_SET_STMRWK_INTERVAL(PMC_STMRWKCTL_STMRIS_1048576);
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMRIS_Msk) >> PMC_STMRWKCTL_STMRIS_Pos == 0xbUL)    
    
    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_SET_STMRWK_INTERVAL(PMC_STMRWKCTL_STMRIS_2097152);
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMRIS_Msk) >> PMC_STMRWKCTL_STMRIS_Pos == 0xcUL)    
    
    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_SET_STMRWK_INTERVAL(PMC_STMRWKCTL_STMRIS_4194304);
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMRIS_Msk) >> PMC_STMRWKCTL_STMRIS_Pos == 0xdUL)

    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_ENABLE_STMR();
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMREN_Msk) >> PMC_STMRWKCTL_STMREN_Pos == 0x1UL)

    PMC_Wait_BusyFlag(PMC_STMRWKCTL_BUSY_FLAG);
    PMC_DISABLE_STMR();
    CU_ASSERT((PMC->STMRWKCTL & PMC_STMRWKCTL_STMREN_Msk) >> PMC_STMRWKCTL_STMREN_Pos == 0x0UL)
}

void PMC_Const_Test(void)
{
    CU_ASSERT(PMC_PWRCTL_BUSY_FLAG      == 0x40002000UL);
    CU_ASSERT(PMC_PLCTL_BUSY_FLAG       == 0x40002010UL);
    CU_ASSERT(PMC_PLSTS_BUSY_FLAG       == 0x40002014UL);
    CU_ASSERT(PMC_VRCTL_BUSY_FLAG       == 0x40002018UL);
    CU_ASSERT(PMC_VRSTS_BUSY_FLAG       == 0x4000201CUL); 
    CU_ASSERT(PMC_STMRWKCTL_BUSY_FLAG   == 0x40002050UL);
    CU_ASSERT(PMC_SYSRB0PC_BUSY_FLAG    == 0x40002100UL);
    CU_ASSERT(PMC_SYSRB1PC_BUSY_FLAG    == 0x40002104UL);
    CU_ASSERT(PMC_SYSRB2PC_BUSY_FLAG    == 0x40002108UL); 
    CU_ASSERT(PMC_SYSRB3PC_BUSY_FLAG    == 0x4000210CUL);
    CU_ASSERT(PMC_LPSYSRPC_BUSY_FLAG    == 0x40002110UL);
    CU_ASSERT(PMC_KSRPC_BUSY_FLAG       == 0x40002140UL);
}

CU_SuiteInfo pmcSuites[] = {
    { "pmc Const Test", pmc_Test_Init, pmc_Test_Clean, NULL, NULL, pmc_ConstTest },
    { "pmc Macro Test", pmc_Test_Init, pmc_Test_Clean, NULL, NULL, pmc_MacroTest },
    { "pmc Func  Test", pmc_Test_Init, pmc_Test_Clean, NULL, NULL, pmc_FuncTest },
    CU_SUITE_INFO_NULL
};

CU_TestInfo  pmc_ConstTest[] = {
    { "PMC_Const_Test",  PMC_Const_Test },
    CU_TEST_INFO_NULL
};

CU_TestInfo  pmc_MacroTest[] = {
    { "PMC_Macro_Test",  PMC_Macro_Test },
    CU_TEST_INFO_NULL
};

CU_TestInfo  pmc_FuncTest[] = {
    { "PMC_PowerDown",              TestFunc_PMC_PowerDown },
    { "PMC_Idle",                   TestFunc_PMC_Idle },
    { "PMC_SetPowerLevel",          TestFunc_PMC_SetPowerLevel },
    { "PMC_SetPowerRegulator",      TestFunc_PMC_SetPowerRegulator },
    { "PMC_SetSRAMPowerMode",       TestFunc_PMC_SetSRAMPowerMode },
    { "PMC_SetPowerDownMode",       TestFunc_PMC_SetPowerDownMode },
    { "PMC_Enable/DisableWKPIN",    TestFunc_PMC_EnableWKPIN },
    { "PMC_EnableTGPin",            TestFunc_PMC_EnableTGPin },
    { "PMC_Wait_BusyFlag",          TestFunc_PMC_Wait_BusyFlag },
    CU_TEST_INFO_NULL
};

/*** (C) COPYRIGHT 2023 Nuvoton Technology Corp. ***/