/******************************************************************************
* @file    template_cunit.c
* @version V1.00
* @brief   CUnit test ecap
*
* SPDX-License-Identifier: Apache-2.0
* @copyright (C) 2023 Nuvoton Technology Corp. All rights reserved.
*****************************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "NuMicro.h"
#include "CUnit.h"
#include "Console.h"
#include "ecap_cunit.h"

ECAP_T *ECAPCh[] =
{
    ECAP0,
    ECAP1,
    ECAP2,
    ECAP3
};

void Enable_SelfTest(void)
{
    /* Enable global self test mode */
    outp32(0x40000E00, 1);
}

void Disable_SelfTest(void)
{
    /* Enable global self test mode */
    outp32(0x40000E00, 0);
}

int ECAP_Test_Init(void)
{
    return 0;
}
int ECAP_Test_Clean(void)
{
    return 0;
}
uint32_t CAP_ENPIN[2][3] = {0};
#define C0PIN 0
#define C1PIN 1
#define C2PIN 2

volatile uint32_t  *au32EcapPin[12] =
{
    &PA10, &PA9, &PA8,
    &PC10, &PC11, &PC12,
    &PD1, &PD0, &PD13,
    &PA12, &PA13, &PA14,
};

void SysTick_Handler(void)
{
    if (CAP_ENPIN[0][C0PIN] == 1)
    {
        *au32EcapPin[C0PIN] ^= 1;
    }

    if (CAP_ENPIN[0][C1PIN] == 1)
    {
        *au32EcapPin[C1PIN] ^= 1;
    }

    if (CAP_ENPIN[0][C2PIN] == 1)
    {
        *au32EcapPin[C2PIN] ^= 1;;
    }
}

void ECAP0_IRQHandler(void) {};
void ECAP1_IRQHandler(void) {};
void ECAP2_IRQHandler(void) {};
void ECAP3_IRQHandler(void) {};

void CONST_Input_Channel(void)
{
    CU_ASSERT_EQUAL(ECAP_IC0, 0);
    CU_ASSERT_EQUAL(ECAP_IC1, 1);
    CU_ASSERT_EQUAL(ECAP_IC2, 2);
}

void CONST_Noise_Filter_DIV(void)
{
    CU_ASSERT_EQUAL(ECAP_NOISE_FILTER_CLKDIV_1, 0);
    CU_ASSERT_EQUAL(ECAP_NOISE_FILTER_CLKDIV_2, 1);
    CU_ASSERT_EQUAL(ECAP_NOISE_FILTER_CLKDIV_4, 2);
    CU_ASSERT_EQUAL(ECAP_NOISE_FILTER_CLKDIV_16, 3);
    CU_ASSERT_EQUAL(ECAP_NOISE_FILTER_CLKDIV_32, 4);
    CU_ASSERT_EQUAL(ECAP_NOISE_FILTER_CLKDIV_64, 5);
}

void CONST_Input_Source(void)
{
    CU_ASSERT_EQUAL(ECAP_CAP_INPUT_SRC_FROM_IC, 0);
    CU_ASSERT_EQUAL(ECAP_CAP_INPUT_SRC_FROM_ACMP, 1);
    CU_ASSERT_EQUAL(ECAP_CAP_INPUT_SRC_FROM_CH, 2);
}

void CONST_Input_Cleared_Events(void)
{
    CU_ASSERT_EQUAL(ECAP_CNT_CLR_EVENT_DISABLE, 0);
    CU_ASSERT_EQUAL(ECAP_CNT_CLR_BY_CMP, ECAP_CTL0_CMPCLREN_Msk);
    CU_ASSERT_EQUAL(ECAP_CNT_CLR_BY_CAPTURE, ECAP_CTL1_CAP0CLREN_Msk | ECAP_CTL1_CAP1CLREN_Msk | ECAP_CTL1_CAP2CLREN_Msk);
    CU_ASSERT_EQUAL(ECAP_CNT_CLR_BY_CAMCMPF, ECAP_CTL0_CMPCLREN_Msk | ECAP_CTL1_CAP0CLREN_Msk | ECAP_CTL1_CAP1CLREN_Msk | ECAP_CTL1_CAP2CLREN_Msk);
}

void CONST_ECAP_Func(void)
{
    CU_ASSERT_EQUAL(ECAP_DISABLE_COMPARE_RELOAD, 0);
    CU_ASSERT_EQUAL(ECAP_RELOAD_FUNCTION, 1);
    CU_ASSERT_EQUAL(ECAP_COMPARE_FUNCTION, 2);
    CU_ASSERT_EQUAL(ECAP_RELOAD_COMPARE_FUNCTION, 3);
    CU_ASSERT_EQUAL(ECAP_DISABLE_COMPARE, 0);
}

void CONST_ECAP_Edge(void)
{
    CU_ASSERT_EQUAL(ECAP_RISING_EDGE, 0);
    CU_ASSERT_EQUAL(ECAP_FALLING_EDGE, 1);
    CU_ASSERT_EQUAL(ECAP_RISING_FALLING_EDGE, 2);
}

void CONST_Reload_Trig_Source(void)
{
    CU_ASSERT_EQUAL(ECAP_RELOAD_TRIG_SRC_CAPF0, ECAP_CTL1_CAP0RLDEN_Msk);
    CU_ASSERT_EQUAL(ECAP_RELOAD_TRIG_SRC_CAPF1, ECAP_CTL1_CAP1RLDEN_Msk);
    CU_ASSERT_EQUAL(ECAP_RELOAD_TRIG_SRC_CAPF2, ECAP_CTL1_CAP2RLDEN_Msk);
    CU_ASSERT_EQUAL(ECAP_RELOAD_TRIG_SRC_OVF, ECAP_CTL1_OVRLDEN_Msk);
}

void CONST_Timer_CLKDIV(void)
{
    CU_ASSERT_EQUAL(ECAP_CAPTURE_TIMER_CLKDIV_1, 0 << ECAP_CTL1_CLKSEL_Pos);
    CU_ASSERT_EQUAL(ECAP_CAPTURE_TIMER_CLKDIV_4, 1 << ECAP_CTL1_CLKSEL_Pos);
    CU_ASSERT_EQUAL(ECAP_CAPTURE_TIMER_CLKDIV_16, 2 << ECAP_CTL1_CLKSEL_Pos);
    CU_ASSERT_EQUAL(ECAP_CAPTURE_TIMER_CLKDIV_32, 3 << ECAP_CTL1_CLKSEL_Pos);
    CU_ASSERT_EQUAL(ECAP_CAPTURE_TIMER_CLKDIV_64, 4 << ECAP_CTL1_CLKSEL_Pos);
    CU_ASSERT_EQUAL(ECAP_CAPTURE_TIMER_CLKDIV_96, 5 << ECAP_CTL1_CLKSEL_Pos);
    CU_ASSERT_EQUAL(ECAP_CAPTURE_TIMER_CLKDIV_112, 6 << ECAP_CTL1_CLKSEL_Pos);
    CU_ASSERT_EQUAL(ECAP_CAPTURE_TIMER_CLKDIV_128, 7 << ECAP_CTL1_CLKSEL_Pos);
}

void CONST_Timer_Source(void)
{
    CU_ASSERT_EQUAL(ECAP_CAPTURE_TIMER_CLK_SRC_CAP_CLK, (0UL << ECAP_CTL1_CNTSRCSEL_Pos));
    CU_ASSERT_EQUAL(ECAP_CAPTURE_TIMER_CLK_SRC_CAP0, (1UL << ECAP_CTL1_CNTSRCSEL_Pos));
    CU_ASSERT_EQUAL(ECAP_CAPTURE_TIMER_CLK_SRC_CAP1, (2UL << ECAP_CTL1_CNTSRCSEL_Pos));
    CU_ASSERT_EQUAL(ECAP_CAPTURE_TIMER_CLK_SRC_CAP2, (3UL << ECAP_CTL1_CNTSRCSEL_Pos));
}

void MACRO_ECAP_Enable_Disable(void)
{
    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);
    /* Enable Capture0 timer/counter */
    ECAP_ENABLE_CAP(ECAP0);
    CU_ASSERT((ECAP0->CTL0 & ECAP_CTL0_CAPEN_Msk) == ECAP_CTL0_CAPEN_Msk);
    CU_ASSERT((ECAP1->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    CU_ASSERT((ECAP2->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    CU_ASSERT((ECAP3->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    /* Disable Capture0 timer/counter */
    ECAP_DISABLE_CAP(ECAP0);
    CU_ASSERT((ECAP0->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    /* Enable Capture1 timer/counter */
    ECAP_ENABLE_CAP(ECAP1);
    CU_ASSERT((ECAP1->CTL0 & ECAP_CTL0_CAPEN_Msk) == ECAP_CTL0_CAPEN_Msk);
    CU_ASSERT((ECAP0->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    CU_ASSERT((ECAP2->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    CU_ASSERT((ECAP3->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    /* Disable Capture1 timer/counter */
    ECAP_DISABLE_CAP(ECAP1);
    CU_ASSERT((ECAP1->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    /* Enable Capture2 timer/counter */
    ECAP_ENABLE_CAP(ECAP2);
    CU_ASSERT((ECAP2->CTL0 & ECAP_CTL0_CAPEN_Msk) == ECAP_CTL0_CAPEN_Msk);
    CU_ASSERT((ECAP1->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    CU_ASSERT((ECAP0->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    CU_ASSERT((ECAP3->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    /* Disable Capture2 timer/counter */
    ECAP_DISABLE_CAP(ECAP2);
    CU_ASSERT((ECAP2->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    /* Enable Capture3 timer/counter */
    ECAP_ENABLE_CAP(ECAP3);
    CU_ASSERT((ECAP3->CTL0 & ECAP_CTL0_CAPEN_Msk) == ECAP_CTL0_CAPEN_Msk);
    CU_ASSERT((ECAP0->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    CU_ASSERT((ECAP2->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    CU_ASSERT((ECAP1->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
    /* Disable Capture3 timer/counter */
    ECAP_DISABLE_CAP(ECAP3);
    CU_ASSERT((ECAP3->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);
}

void MACRO_Noise_Filter(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_ENABLE_CNT(ECAPCh[i]);

        /* Enable and Select CAP_CLK/1*/
        ECAP_NOISE_FILTER_ENABLE(ECAPCh[i], ECAP_NOISE_FILTER_CLKDIV_1);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPNFDIS_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_NFCLKSEL_Msk) == ECAP_NOISE_FILTER_CLKDIV_1);
        ECAP_NOISE_FILTER_DISABLE(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPNFDIS_Msk) == ECAP_CTL0_CAPNFDIS_Msk);
        /* Enable and Select CAP_CLK/2*/
        ECAP_NOISE_FILTER_ENABLE(ECAPCh[i], ECAP_NOISE_FILTER_CLKDIV_2);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPNFDIS_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_NFCLKSEL_Msk) == ECAP_NOISE_FILTER_CLKDIV_2);
        ECAP_NOISE_FILTER_DISABLE(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPNFDIS_Msk) == ECAP_CTL0_CAPNFDIS_Msk);
        /* Enable and Select CAP_CLK/4*/
        ECAP_NOISE_FILTER_ENABLE(ECAPCh[i], ECAP_NOISE_FILTER_CLKDIV_4);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPNFDIS_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_NFCLKSEL_Msk) == ECAP_NOISE_FILTER_CLKDIV_4);
        ECAP_NOISE_FILTER_DISABLE(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPNFDIS_Msk) == ECAP_CTL0_CAPNFDIS_Msk);
        /* Enable and Select CAP_CLK/16*/
        ECAP_NOISE_FILTER_ENABLE(ECAPCh[i], ECAP_NOISE_FILTER_CLKDIV_16);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPNFDIS_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_NFCLKSEL_Msk) == ECAP_NOISE_FILTER_CLKDIV_16);
        ECAP_NOISE_FILTER_DISABLE(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPNFDIS_Msk) == ECAP_CTL0_CAPNFDIS_Msk);
        /* Enable and Select CAP_CLK/32*/
        ECAP_NOISE_FILTER_ENABLE(ECAPCh[i], ECAP_NOISE_FILTER_CLKDIV_32);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPNFDIS_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_NFCLKSEL_Msk) == ECAP_NOISE_FILTER_CLKDIV_32);
        ECAP_NOISE_FILTER_DISABLE(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPNFDIS_Msk) == ECAP_CTL0_CAPNFDIS_Msk);
        /* Enable and Select CAP_CLK/64*/
        ECAP_NOISE_FILTER_ENABLE(ECAPCh[i], ECAP_NOISE_FILTER_CLKDIV_64);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPNFDIS_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_NFCLKSEL_Msk) == ECAP_NOISE_FILTER_CLKDIV_64);
        ECAP_NOISE_FILTER_DISABLE(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPNFDIS_Msk) == ECAP_CTL0_CAPNFDIS_Msk);

        /* Enable Capture Timer/Counter */
        ECAP_NOISE_FILTER_ENABLE(ECAPCh[i], ECAP_NOISE_FILTER_CLKDIV_1);
        /* Select CAP_CLK/64*/
        ECAP_SET_NOISE_FILTER_CLKDIV(ECAPCh[i], ECAP_NOISE_FILTER_CLKDIV_64);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_NFCLKSEL_Msk) == ECAP_NOISE_FILTER_CLKDIV_64);
        /* Select CAP_CLK/32*/
        ECAP_SET_NOISE_FILTER_CLKDIV(ECAPCh[i], ECAP_NOISE_FILTER_CLKDIV_32);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_NFCLKSEL_Msk) == ECAP_NOISE_FILTER_CLKDIV_32);
        /* Select CAP_CLK/16*/
        ECAP_SET_NOISE_FILTER_CLKDIV(ECAPCh[i], ECAP_NOISE_FILTER_CLKDIV_16);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_NFCLKSEL_Msk) == ECAP_NOISE_FILTER_CLKDIV_16);
        /* Select CAP_CLK/4*/
        ECAP_SET_NOISE_FILTER_CLKDIV(ECAPCh[i], ECAP_NOISE_FILTER_CLKDIV_4);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_NFCLKSEL_Msk) == ECAP_NOISE_FILTER_CLKDIV_4);
        /* Select CAP_CLK/2*/
        ECAP_SET_NOISE_FILTER_CLKDIV(ECAPCh[i], ECAP_NOISE_FILTER_CLKDIV_2);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_NFCLKSEL_Msk) == ECAP_NOISE_FILTER_CLKDIV_2);
        /* Select CAP_CLK/1*/
        ECAP_SET_NOISE_FILTER_CLKDIV(ECAPCh[i], ECAP_NOISE_FILTER_CLKDIV_1);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_NFCLKSEL_Msk) == ECAP_NOISE_FILTER_CLKDIV_1);

        ECAP_NOISE_FILTER_DISABLE(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPNFDIS_Msk) == ECAP_CTL0_CAPNFDIS_Msk);
    }
}

void MACRO_Input_Channel(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_ENABLE_CNT(ECAPCh[i]);

        /* Enable IC0 */
        ECAP_ENABLE_INPUT_CHANNEL(ECAPCh[i], ECAP_CTL0_IC0EN_Msk);
        CU_ASSERT_EQUAL((ECAPCh[i]->CTL0 & ECAP_CTL0_IC0EN_Msk), ECAP_CTL0_IC0EN_Msk);
        /* Disable IC0 */
        ECAP_DISABLE_INPUT_CHANNEL(ECAPCh[i], ECAP_CTL0_IC0EN_Msk);
        CU_ASSERT_EQUAL((ECAPCh[i]->CTL0 & ECAP_CTL0_IC0EN_Msk), 0);

        /* Enable IC1 */
        ECAP_ENABLE_INPUT_CHANNEL(ECAPCh[i], ECAP_CTL0_IC1EN_Msk);
        CU_ASSERT_EQUAL((ECAPCh[i]->CTL0 & ECAP_CTL0_IC1EN_Msk), ECAP_CTL0_IC1EN_Msk);
        /* Disable IC1 */
        ECAP_DISABLE_INPUT_CHANNEL(ECAPCh[i], ECAP_CTL0_IC1EN_Msk);
        CU_ASSERT_EQUAL((ECAPCh[i]->CTL0 & ECAP_CTL0_IC1EN_Msk), 0);

        /* Enable IC2 */
        ECAP_ENABLE_INPUT_CHANNEL(ECAPCh[i], ECAP_CTL0_IC2EN_Msk);
        CU_ASSERT_EQUAL((ECAPCh[i]->CTL0 & ECAP_CTL0_IC2EN_Msk), ECAP_CTL0_IC2EN_Msk);
        /* Disable IC2 */
        ECAP_DISABLE_INPUT_CHANNEL(ECAPCh[i], ECAP_CTL0_IC2EN_Msk);
        CU_ASSERT_EQUAL((ECAPCh[i]->CTL0 & ECAP_CTL0_IC2EN_Msk), 0);

        /* Enable IC0, IC1 */
        ECAP_ENABLE_INPUT_CHANNEL(ECAPCh[i], ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC1EN_Msk);
        CU_ASSERT_EQUAL((ECAPCh[i]->CTL0 & (ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC1EN_Msk)), (ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC1EN_Msk));
        /* Disable IC0, IC1 */
        ECAP_DISABLE_INPUT_CHANNEL(ECAPCh[i], ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC1EN_Msk);
        CU_ASSERT_EQUAL((ECAPCh[i]->CTL0 & (ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC1EN_Msk)), 0);

        /* Enable IC0, IC2 */
        ECAP_ENABLE_INPUT_CHANNEL(ECAPCh[i], ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC2EN_Msk);
        CU_ASSERT_EQUAL((ECAPCh[i]->CTL0 & (ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC2EN_Msk)), (ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC2EN_Msk));
        /* Disable IC0, IC2 */
        ECAP_DISABLE_INPUT_CHANNEL(ECAPCh[i], ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC2EN_Msk);
        CU_ASSERT_EQUAL((ECAPCh[i]->CTL0 & (ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC2EN_Msk)), 0);

        /* Enable IC1, IC2 */
        ECAP_ENABLE_INPUT_CHANNEL(ECAPCh[i], ECAP_CTL0_IC1EN_Msk | ECAP_CTL0_IC2EN_Msk);
        CU_ASSERT_EQUAL((ECAPCh[i]->CTL0 & (ECAP_CTL0_IC1EN_Msk | ECAP_CTL0_IC2EN_Msk)), (ECAP_CTL0_IC1EN_Msk | ECAP_CTL0_IC2EN_Msk));
        /* Disable IC1, IC2 */
        ECAP_DISABLE_INPUT_CHANNEL(ECAPCh[i], ECAP_CTL0_IC1EN_Msk | ECAP_CTL0_IC2EN_Msk);
        CU_ASSERT_EQUAL((ECAPCh[i]->CTL0 & (ECAP_CTL0_IC1EN_Msk | ECAP_CTL0_IC2EN_Msk)), 0);

        /* Enable IC0, IC1, IC2 */
        ECAP_ENABLE_INPUT_CHANNEL(ECAPCh[i], ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC1EN_Msk | ECAP_CTL0_IC2EN_Msk);
        CU_ASSERT_EQUAL((ECAPCh[i]->CTL0 & (ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC1EN_Msk | ECAP_CTL0_IC2EN_Msk)), (ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC1EN_Msk | ECAP_CTL0_IC2EN_Msk));
        /* Disable IC0, IC1, IC2 */
        ECAP_DISABLE_INPUT_CHANNEL(ECAPCh[i], ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC1EN_Msk | ECAP_CTL0_IC2EN_Msk);
        CU_ASSERT_EQUAL((ECAPCh[i]->CTL0 & (ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC1EN_Msk | ECAP_CTL0_IC2EN_Msk)), 0);


        ECAP_DISABLE_CNT(ECAPCh[i]);
    }
}

void MACRO_Input_Source(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_ENABLE_CNT(ECAPCh[i]);

        /* IC0 Source Selection */
        ECAP_SEL_INPUT_SRC(ECAPCh[i], ECAP_IC0, ECAP_CAP_INPUT_SRC_FROM_IC);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPSEL0_Msk) == (ECAP_CAP_INPUT_SRC_FROM_IC << ECAP_CTL0_CAPSEL0_Pos));
        ECAP_SEL_INPUT_SRC(ECAPCh[i], ECAP_IC0, ECAP_CAP_INPUT_SRC_FROM_ACMP);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPSEL0_Msk) == (ECAP_CAP_INPUT_SRC_FROM_ACMP << ECAP_CTL0_CAPSEL0_Pos));
        ECAP_SEL_INPUT_SRC(ECAPCh[i], ECAP_IC0, ECAP_CAP_INPUT_SRC_FROM_CH);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPSEL0_Msk) == (ECAP_CAP_INPUT_SRC_FROM_CH << ECAP_CTL0_CAPSEL0_Pos));

        /* IC1 Source Selection */
        ECAP_SEL_INPUT_SRC(ECAPCh[i], ECAP_IC1, ECAP_CAP_INPUT_SRC_FROM_IC);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPSEL1_Msk) == (ECAP_CAP_INPUT_SRC_FROM_IC << ECAP_CTL0_CAPSEL1_Pos));
        ECAP_SEL_INPUT_SRC(ECAPCh[i], ECAP_IC1, ECAP_CAP_INPUT_SRC_FROM_ACMP);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPSEL1_Msk) == (ECAP_CAP_INPUT_SRC_FROM_ACMP << ECAP_CTL0_CAPSEL1_Pos));
        ECAP_SEL_INPUT_SRC(ECAPCh[i], ECAP_IC1, ECAP_CAP_INPUT_SRC_FROM_CH);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPSEL1_Msk) == (ECAP_CAP_INPUT_SRC_FROM_CH << ECAP_CTL0_CAPSEL1_Pos));

        /* IC2 Source Selection */
        ECAP_SEL_INPUT_SRC(ECAPCh[i], ECAP_IC2, ECAP_CAP_INPUT_SRC_FROM_IC);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPSEL2_Msk) == (ECAP_CAP_INPUT_SRC_FROM_IC << ECAP_CTL0_CAPSEL2_Pos));
        ECAP_SEL_INPUT_SRC(ECAPCh[i], ECAP_IC2, ECAP_CAP_INPUT_SRC_FROM_ACMP);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPSEL2_Msk) == (ECAP_CAP_INPUT_SRC_FROM_ACMP << ECAP_CTL0_CAPSEL2_Pos));
        ECAP_SEL_INPUT_SRC(ECAPCh[i], ECAP_IC2, ECAP_CAP_INPUT_SRC_FROM_CH);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPSEL2_Msk) == (ECAP_CAP_INPUT_SRC_FROM_CH << ECAP_CTL0_CAPSEL2_Pos));

        ECAP_DISABLE_CNT(ECAPCh[i]);
    }
}

void MACRO_Input_INT(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_ENABLE_CNT(ECAPCh[i]);

        /* one channel enable */
        ECAP_ENABLE_INT(ECAPCh[i], ECAP_CTL0_CAPIEN0_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == ECAP_CTL0_CAPIEN0_Msk);
        ECAP_ENABLE_INT(ECAPCh[i], ECAP_CTL0_CAPIEN1_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == ECAP_CTL0_CAPIEN0_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN1_Msk) == ECAP_CTL0_CAPIEN1_Msk);
        ECAP_ENABLE_INT(ECAPCh[i], ECAP_CTL0_CAPIEN2_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == ECAP_CTL0_CAPIEN0_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN1_Msk) == ECAP_CTL0_CAPIEN1_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN2_Msk) == ECAP_CTL0_CAPIEN2_Msk);

        /* one channel disable */
        ECAP_DISABLE_INT(ECAPCh[i], ECAP_CTL0_CAPIEN0_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN1_Msk) == ECAP_CTL0_CAPIEN1_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN2_Msk) == ECAP_CTL0_CAPIEN2_Msk);
        ECAP_DISABLE_INT(ECAPCh[i], ECAP_CTL0_CAPIEN1_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN1_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN2_Msk) == ECAP_CTL0_CAPIEN2_Msk);
        ECAP_DISABLE_INT(ECAPCh[i], ECAP_CTL0_CAPIEN2_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN1_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN2_Msk) == 0);

        /* two channel 0,1 enable */
        ECAP_ENABLE_INT(ECAPCh[i], ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN1_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == ECAP_CTL0_CAPIEN0_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN1_Msk) == ECAP_CTL0_CAPIEN1_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN2_Msk) == 0);
        /* two channel 0,1 disable */
        ECAP_DISABLE_INT(ECAPCh[i], ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN1_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN1_Msk) == 0);
        /* two channel 0,2 enable */
        ECAP_ENABLE_INT(ECAPCh[i], ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN2_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == ECAP_CTL0_CAPIEN0_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN2_Msk) == ECAP_CTL0_CAPIEN2_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN1_Msk) == 0);
        /* two channel 0,2 disable */
        ECAP_DISABLE_INT(ECAPCh[i], ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN2_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN2_Msk) == 0);
        /* two channel 1,2 enable */
        ECAP_ENABLE_INT(ECAPCh[i], ECAP_CTL0_CAPIEN1_Msk | ECAP_CTL0_CAPIEN2_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN1_Msk) == ECAP_CTL0_CAPIEN1_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN2_Msk) == ECAP_CTL0_CAPIEN2_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == 0);
        /* two channel 1,2 disable */
        ECAP_DISABLE_INT(ECAPCh[i], ECAP_CTL0_CAPIEN1_Msk | ECAP_CTL0_CAPIEN2_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN1_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN2_Msk) == 0);
        /* three  channel 0,1, 2 enable */
        ECAP_ENABLE_INT(ECAPCh[i], ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN1_Msk | ECAP_CTL0_CAPIEN2_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == ECAP_CTL0_CAPIEN0_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN1_Msk) == ECAP_CTL0_CAPIEN1_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN2_Msk) == ECAP_CTL0_CAPIEN2_Msk);
        /* three  channel 0,1,2 disable */
        ECAP_DISABLE_INT(ECAPCh[i], ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN1_Msk | ECAP_CTL0_CAPIEN2_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN1_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN2_Msk) == 0);

        /* Over flow INT enabe/disable */
        ECAP_ENABLE_OVF_INT(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_OVIEN_Msk) == ECAP_CTL0_OVIEN_Msk);
        ECAP_DISABLE_OVF_INT(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_OVIEN_Msk) == 0);

        /* Compare-Match INT enabe/disable */
        ECAP_ENABLE_CMP_MATCH_INT(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPIEN_Msk) == ECAP_CTL0_CMPIEN_Msk);
        ECAP_DISABLE_CMP_MATCH_INT(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPIEN_Msk) == 0);

        ECAP_DISABLE_CNT(ECAPCh[i]);
    }
}

void MACRO_Input_edge(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_ENABLE_CNT(ECAPCh[i]);

        ECAP_SEL_CAPTURE_EDGE(ECAPCh[i], ECAP_IC0, ECAP_RISING_EDGE);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_EDGESEL0_Msk) == (ECAP_RISING_EDGE << ECAP_CTL1_EDGESEL0_Pos));
        ECAP_SEL_CAPTURE_EDGE(ECAPCh[i], ECAP_IC0, ECAP_FALLING_EDGE);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_EDGESEL0_Msk) == (ECAP_FALLING_EDGE << ECAP_CTL1_EDGESEL0_Pos));
        ECAP_SEL_CAPTURE_EDGE(ECAPCh[i], ECAP_IC0, ECAP_RISING_FALLING_EDGE);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_EDGESEL0_Msk) == (ECAP_RISING_FALLING_EDGE << ECAP_CTL1_EDGESEL0_Pos));

        ECAP_SEL_CAPTURE_EDGE(ECAPCh[i], ECAP_IC1, ECAP_RISING_EDGE);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_EDGESEL1_Msk) == (ECAP_RISING_EDGE << ECAP_CTL1_EDGESEL1_Pos));
        ECAP_SEL_CAPTURE_EDGE(ECAPCh[i], ECAP_IC1, ECAP_FALLING_EDGE);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_EDGESEL1_Msk) == (ECAP_FALLING_EDGE << ECAP_CTL1_EDGESEL1_Pos));
        ECAP_SEL_CAPTURE_EDGE(ECAPCh[i], ECAP_IC1, ECAP_RISING_FALLING_EDGE);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_EDGESEL1_Msk) == (ECAP_RISING_FALLING_EDGE << ECAP_CTL1_EDGESEL1_Pos));

        ECAP_SEL_CAPTURE_EDGE(ECAPCh[i], ECAP_IC2, ECAP_RISING_EDGE);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_EDGESEL2_Msk) == (ECAP_RISING_EDGE << ECAP_CTL1_EDGESEL2_Pos));
        ECAP_SEL_CAPTURE_EDGE(ECAPCh[i], ECAP_IC2, ECAP_FALLING_EDGE);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_EDGESEL2_Msk) == (ECAP_FALLING_EDGE << ECAP_CTL1_EDGESEL2_Pos));
        ECAP_SEL_CAPTURE_EDGE(ECAPCh[i], ECAP_IC2, ECAP_RISING_FALLING_EDGE);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_EDGESEL2_Msk) == (ECAP_RISING_FALLING_EDGE << ECAP_CTL1_EDGESEL2_Pos));

        ECAP_DISABLE_CNT(ECAPCh[i]);
    }
}

void MACRO_Input_Reload(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_ENABLE_CNT(ECAPCh[i]);

        ECAP_SEL_RELOAD_TRIG_SRC(ECAPCh[i], ECAP_RELOAD_TRIG_SRC_CAPF0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0RLDEN_Msk) == (ECAP_CTL1_CAP0RLDEN_Msk));
        ECAP_SEL_RELOAD_TRIG_SRC(ECAPCh[i], ECAP_RELOAD_TRIG_SRC_CAPF1);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1RLDEN_Msk) == (ECAP_CTL1_CAP1RLDEN_Msk));
        ECAP_SEL_RELOAD_TRIG_SRC(ECAPCh[i], ECAP_RELOAD_TRIG_SRC_CAPF2);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2RLDEN_Msk) == (ECAP_CTL1_CAP2RLDEN_Msk));
        ECAP_SEL_RELOAD_TRIG_SRC(ECAPCh[i], ECAP_RELOAD_TRIG_SRC_OVF);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_OVRLDEN_Msk) == (ECAP_CTL1_OVRLDEN_Msk));
        ECAPCh[i]->CTL1 = 0;
        ECAP_SEL_OVRRLD_TRIG_SRC(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_OVRLDEN_Msk) == (ECAP_CTL1_OVRLDEN_Msk));

        ECAP_DISABLE_CNT(ECAPCh[i]);
    }
}

void MACRO_Input_ClkSel(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_ENABLE_CNT(ECAPCh[i]);

        ECAP_SEL_TIMER_CLK_DIV(ECAPCh[i], ECAP_CAPTURE_TIMER_CLKDIV_1);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CLKSEL_Msk) == (ECAP_CAPTURE_TIMER_CLKDIV_1));
        ECAP_SEL_TIMER_CLK_DIV(ECAPCh[i], ECAP_CAPTURE_TIMER_CLKDIV_4);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CLKSEL_Msk) == (ECAP_CAPTURE_TIMER_CLKDIV_4));
        ECAP_SEL_TIMER_CLK_DIV(ECAPCh[i], ECAP_CAPTURE_TIMER_CLKDIV_16);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CLKSEL_Msk) == (ECAP_CAPTURE_TIMER_CLKDIV_16));
        ECAP_SEL_TIMER_CLK_DIV(ECAPCh[i], ECAP_CAPTURE_TIMER_CLKDIV_32);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CLKSEL_Msk) == (ECAP_CAPTURE_TIMER_CLKDIV_32));
        ECAP_SEL_TIMER_CLK_DIV(ECAPCh[i], ECAP_CAPTURE_TIMER_CLKDIV_64);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CLKSEL_Msk) == (ECAP_CAPTURE_TIMER_CLKDIV_64));
        ECAP_SEL_TIMER_CLK_DIV(ECAPCh[i], ECAP_CAPTURE_TIMER_CLKDIV_96);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CLKSEL_Msk) == (ECAP_CAPTURE_TIMER_CLKDIV_96));
        ECAP_SEL_TIMER_CLK_DIV(ECAPCh[i], ECAP_CAPTURE_TIMER_CLKDIV_112);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CLKSEL_Msk) == (ECAP_CAPTURE_TIMER_CLKDIV_112));
        ECAP_SEL_TIMER_CLK_DIV(ECAPCh[i], ECAP_CAPTURE_TIMER_CLKDIV_128);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CLKSEL_Msk) == (ECAP_CAPTURE_TIMER_CLKDIV_128));

        ECAP_DISABLE_CNT(ECAPCh[i]);
    }
}

void MACRO_Input_ClkSrc(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_ENABLE_CNT(ECAPCh[i]);

        ECAP_SEL_TIMER_CLK_SRC(ECAPCh[i], ECAP_CAPTURE_TIMER_CLK_SRC_CAP_CLK);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CNTSRCSEL_Msk) == (0UL));
        ECAP_SEL_TIMER_CLK_SRC(ECAPCh[i], ECAP_CAPTURE_TIMER_CLK_SRC_CAP0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CNTSRCSEL_Msk) == (BIT16));
        ECAP_SEL_TIMER_CLK_SRC(ECAPCh[i], ECAP_CAPTURE_TIMER_CLK_SRC_CAP1);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CNTSRCSEL_Msk) == (BIT17));
        ECAP_SEL_TIMER_CLK_SRC(ECAPCh[i], ECAP_CAPTURE_TIMER_CLK_SRC_CAP2);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CNTSRCSEL_Msk) == (BIT16 | BIT17));
        ECAP_DISABLE_CNT(ECAPCh[i]);
    }
}

void MACRO_CNT_STA_STO(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_ENABLE_CNT(ECAPCh[i]);

        ECAP_CNT_START(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CNTEN_Msk) == ECAP_CTL0_CNTEN_Msk);
        ECAP_CNT_STOP(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CNTEN_Msk) == 0);

        ECAP_DISABLE_CNT(ECAPCh[i]);
    }
}

void MACRO_CNT_CLRRLD(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_ENABLE_CNT(ECAPCh[i]);

        ECAP_SET_CNT_CLRRLD_EVENT(ECAPCh[i], ECAP_CTL0_CMPCLREN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPCLREN_Msk) == ECAP_CTL0_CMPCLREN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_OVRLDEN_Msk) == 0);

        ECAP_SET_CNT_CLRRLD_EVENT(ECAPCh[i], ECAP_CTL1_CAP0RLDEN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0RLDEN_Msk) == ECAP_CTL1_CAP0RLDEN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPCLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_OVRLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2CLREN_Msk) == 0);

        ECAP_SET_CNT_CLRRLD_EVENT(ECAPCh[i], ECAP_CTL1_CAP1RLDEN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1RLDEN_Msk) == ECAP_CTL1_CAP1RLDEN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPCLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_OVRLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2CLREN_Msk) == 0);

        ECAP_SET_CNT_CLRRLD_EVENT(ECAPCh[i], ECAP_CTL1_CAP2RLDEN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2RLDEN_Msk) == ECAP_CTL1_CAP2RLDEN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPCLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_OVRLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2CLREN_Msk) == 0);

        ECAP_SET_CNT_CLRRLD_EVENT(ECAPCh[i], ECAP_CTL1_OVRLDEN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_OVRLDEN_Msk) == ECAP_CTL1_OVRLDEN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPCLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2CLREN_Msk) == 0);

        ECAP_SET_CNT_CLRRLD_EVENT(ECAPCh[i], ECAP_CTL1_CAP0CLREN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPCLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0CLREN_Msk) == ECAP_CTL1_CAP0CLREN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_OVRLDEN_Msk) == 0);

        ECAP_SET_CNT_CLRRLD_EVENT(ECAPCh[i], ECAP_CTL1_CAP1CLREN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPCLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1CLREN_Msk) == ECAP_CTL1_CAP1CLREN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_OVRLDEN_Msk) == 0);

        ECAP_SET_CNT_CLRRLD_EVENT(ECAPCh[i], ECAP_CTL1_CAP2CLREN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPCLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1CLREN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2CLREN_Msk) == ECAP_CTL1_CAP2CLREN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP0RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP1RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_CAP2RLDEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1 & ECAP_CTL1_OVRLDEN_Msk) == 0);

        ECAPCh[i]->CTL1 = 0;
        ECAP_ENABLE_RELOAD(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL1) == (ECAP_CTL1_CAP0RLDEN_Msk | ECAP_CTL1_CAP1RLDEN_Msk | ECAP_CTL1_CAP2RLDEN_Msk | ECAP_CTL1_OVRLDEN_Msk));
        ECAP_SEL_ALLRLDCLR_TRIG_SRC(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL1) == 0);
        ECAP_DISABLE_CNT(ECAPCh[i]);
    }
}

void MACRO_Capture_Mode(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_ENABLE_CNT(ECAPCh[i]);

        ECAP_ENABLE_CMP(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPEN_Msk) == ECAP_CTL0_CMPEN_Msk);
        ECAP_DISABLE_CMP(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPEN_Msk) == 0);

        ECAP_DISABLE_CNT(ECAPCh[i]);
    }
}

void MACRO_Set_CNT_Value(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_ENABLE_CNT(ECAPCh[i]);
        ECAP_SET_CNT_VALUE(ECAPCh[i], 0x00FFFFFF);
        CU_ASSERT((ECAPCh[i]->CNT) == 0x00FFFFFF);
        CU_ASSERT(ECAP_GET_CNT_VALUE(ECAPCh[i]) == 0x00FFFFFF);
        ECAP_SET_CNT_VALUE(ECAPCh[i], 0x005A5A5A);
        CU_ASSERT((ECAPCh[i]->CNT) == 0x005A5A5A);
        CU_ASSERT(ECAP_GET_CNT_VALUE(ECAPCh[i]) == 0x005A5A5A);
        ECAP_SET_CNT_VALUE(ECAPCh[i], 0x00A5A5A5);
        CU_ASSERT((ECAPCh[i]->CNT) == 0x00A5A5A5);
        CU_ASSERT(ECAP_GET_CNT_VALUE(ECAPCh[i]) == 0x00A5A5A5);
        ECAP_DISABLE_CNT(ECAPCh[i]);
    }
}

void MACRO_OVF_CMP(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_ENABLE_CNT(ECAPCh[i]);
        ECAP_SET_CNT_VALUE(ECAPCh[i], 0x00FFFF00);
        CU_ASSERT((ECAPCh[i]->CNT) == 0x00FFFF00);
        ECAP_CNT_START(ECAPCh[i]);                                       //Start up-counting

        while (!ECAP_GET_CAPTURE_FLAG(ECAPCh[i], ECAP_STATUS_CAPOVF_Msk)) {};

        CU_ASSERT(ECAP_GET_CAPTURE_FLAG(ECAPCh[i], ECAP_STATUS_CAPOVF_Msk) == 1);

        ECAP_CLR_CAPTURE_FLAG(ECAPCh[i], ECAP_STATUS_CAPOVF_Msk);

        CU_ASSERT(ECAP_GET_CAPTURE_FLAG(ECAPCh[i], ECAP_STATUS_CAPOVF_Msk) == 0);

        ECAP_CNT_STOP(ECAPCh[i]);

        ECAP_Open(ECAPCh[i], ECAP_DISABLE_COMPARE);

        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPEN_Msk) == 0);

        ECAP_ENABLE_CMP(ECAPCh[i]);

        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPEN_Msk) == ECAP_CTL0_CMPEN_Msk);

        ECAP_SET_CNT_CMP(ECAPCh[i], 0x111111);

        ECAP_SET_CNT_VALUE(ECAPCh[i], 0x111111);

        CU_ASSERT(ECAP_GET_CAPTURE_FLAG(ECAPCh[i], ECAP_STATUS_CAPCMPF_Msk) == 1);

        ECAP_DISABLE_CMP(ECAPCh[i]);

        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPEN_Msk) == 0);

        ECAP_CLR_CAPTURE_FLAG(ECAPCh[i], ECAP_STATUS_CAPCMPF_Msk);

        CU_ASSERT(ECAP_GET_CAPTURE_FLAG(ECAPCh[i], ECAP_STATUS_CAPCMPF_Msk) == 0);
    }
}

void MACRO_INT_Hold(void)
{
    uint32_t u32STS, u32Buf, CxIdex;
    uint32_t CAPENx[] = {ECAP_CTL0_IC0EN_Msk, ECAP_CTL0_IC1EN_Msk, ECAP_CTL0_IC2EN_Msk};
    volatile uint32_t *Holdx[3] = {(&ECAP0->HLD0), (&ECAP0->HLD1), (&ECAP0->HLD2)};
    uint32_t Statusx[] = {ECAP_STATUS_CAPTF0_Msk, ECAP_STATUS_CAPTF1_Msk, ECAP_STATUS_CAPTF2_Msk};

    CLK_EnableModuleClock(GPIOA_MODULE);
    GPIO_SetMode(PA, BIT8 | BIT9 | BIT10, GPIO_MODE_OUTPUT);
    SYS_ResetModule(SYS_ECAP0RST);

    ECAP_ENABLE_CNT(ECAP0);
    Enable_SelfTest();
    ECAP_SEL_TIMER_CLK_DIV(ECAP0, ECAP_CAPTURE_TIMER_CLKDIV_1);
    ECAP_SEL_CAPTURE_EDGE(ECAP0, ECAP_IC0, ECAP_RISING_FALLING_EDGE);
    ECAP_SEL_CAPTURE_EDGE(ECAP0, ECAP_IC1, ECAP_RISING_FALLING_EDGE);
    ECAP_SEL_CAPTURE_EDGE(ECAP0, ECAP_IC2, ECAP_RISING_FALLING_EDGE);

    ECAP_DISABLE_INPUT_CHANNEL(ECAP0, ECAP_CTL0_IC0EN_Msk | ECAP_CTL0_IC1EN_Msk | ECAP_CTL0_IC2EN_Msk);
    ECAP_NOISE_FILTER_DISABLE(ECAP0);
    ECAP0->STATUS = 0xFF;

    for (CxIdex = 0; CxIdex < 3; CxIdex++)
    {
        //CHECK IC0
        ECAP_ENABLE_INPUT_CHANNEL(ECAP0, CAPENx[CxIdex]);
        CAP_ENPIN[0][CxIdex] = 1;
        CLK_EnableSysTick(CLK_SCLKSEL_SCLKSEL_APLL0, SystemCoreClock / 2000);
        ECAP_CNT_START(ECAP0);                                       //Start up-counting

        while (!ECAP_GET_CAPTURE_FLAG(ECAP0, Statusx[CxIdex])) {};

        u32STS = ECAP_GET_INT_STATUS(ECAP0);

        CU_ASSERT_EQUAL(ECAP0->STATUS, u32STS);

        CU_ASSERT(ECAP_GET_CAPTURE_FLAG(ECAP0, Statusx[CxIdex]) == 1);

        u32STS = ECAP_CLR_CAPTURE_FLAG(ECAP0, Statusx[CxIdex]);

        CU_ASSERT(ECAP_GET_CAPTURE_FLAG(ECAP0, Statusx[CxIdex]) == 0);

        u32Buf = ECAP_GET_CNT_HOLD_VALUE(ECAP0, CxIdex);

        CU_ASSERT(*(volatile uint32_t *)(Holdx[CxIdex]) == u32Buf);

        CAP_ENPIN[0][CxIdex] = 0;

        //printf("ECAP0->HOLD0=0x%08x,u32Buf=0x%08x\n",ECAP0->HLD0,u32Buf);
    }

    CLK_DisableSysTick();
    Disable_SelfTest();
    CLK_DisableModuleClock(GPIOA_MODULE);
}

void API_ECAP_Open_Close(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_Open(ECAPCh[i], ECAP_COMPARE_FUNCTION);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPEN_Msk) == ECAP_CTL0_CAPEN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPEN_Msk) == ECAP_CTL0_CMPEN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL1) == 0);
        ECAP_Close(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);

        ECAP_Open(ECAPCh[i], ECAP_RELOAD_FUNCTION);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPEN_Msk) == ECAP_CTL0_CAPEN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1) == (ECAP_CTL1_CAP0RLDEN_Msk | ECAP_CTL1_CAP1RLDEN_Msk | ECAP_CTL1_CAP2RLDEN_Msk));
        ECAP_Close(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);

        ECAP_Open(ECAPCh[i], ECAP_DISABLE_COMPARE);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPEN_Msk) == ECAP_CTL0_CAPEN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPEN_Msk) == 0);
        CU_ASSERT((ECAPCh[i]->CTL1) == 0);
        ECAP_Close(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);

        ECAP_Open(ECAPCh[i], ECAP_RELOAD_COMPARE_FUNCTION);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPEN_Msk) == ECAP_CTL0_CAPEN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CMPEN_Msk) == ECAP_CTL0_CMPEN_Msk);
        CU_ASSERT((ECAPCh[i]->CTL1) == (ECAP_CTL1_CAP0RLDEN_Msk | ECAP_CTL1_CAP1RLDEN_Msk | ECAP_CTL1_CAP2RLDEN_Msk));
        ECAP_Close(ECAPCh[i]);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPEN_Msk) == 0);

        ECAP_DISABLE_CNT(ECAP0);
    }
}

void API_ECAP_INT_EN(void)
{
    volatile uint32_t i;

    SYS_ResetModule(SYS_ECAP0RST);
    SYS_ResetModule(SYS_ECAP1RST);
    SYS_ResetModule(SYS_ECAP2RST);
    SYS_ResetModule(SYS_ECAP3RST);

    for (i = 0; i < 4; i++)
    {
        ECAP_ENABLE_CNT(ECAPCh[i]);

        ECAP_EnableINT(ECAPCh[i], ECAP_CTL0_CAPIEN0_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == ECAP_CTL0_CAPIEN0_Msk);
        ECAP_DisableINT(ECAPCh[i], ECAP_CTL0_CAPIEN0_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN0_Msk) == 0);

        ECAP_EnableINT(ECAPCh[i], ECAP_CTL0_CAPIEN1_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN1_Msk) == ECAP_CTL0_CAPIEN1_Msk);
        ECAP_DisableINT(ECAPCh[i], ECAP_CTL0_CAPIEN1_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN1_Msk) == 0);

        ECAP_EnableINT(ECAPCh[i], ECAP_CTL0_CAPIEN2_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN2_Msk) == ECAP_CTL0_CAPIEN2_Msk);
        ECAP_DisableINT(ECAPCh[i], ECAP_CTL0_CAPIEN2_Msk);
        CU_ASSERT((ECAPCh[i]->CTL0 & ECAP_CTL0_CAPIEN2_Msk) == 0);

        ECAP_EnableINT(ECAPCh[i], (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN1_Msk));
        CU_ASSERT((ECAPCh[i]->CTL0 & (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN1_Msk)) == (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN1_Msk));
        ECAP_DisableINT(ECAPCh[i], (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN1_Msk));
        CU_ASSERT((ECAPCh[i]->CTL0 & (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN1_Msk)) == 0);

        ECAP_EnableINT(ECAPCh[i], (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN2_Msk));
        CU_ASSERT((ECAPCh[i]->CTL0 & (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN2_Msk)) == (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN2_Msk));
        ECAP_DisableINT(ECAPCh[i], (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN2_Msk));
        CU_ASSERT((ECAPCh[i]->CTL0 & (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN2_Msk)) == 0);

        ECAP_EnableINT(ECAPCh[i], (ECAP_CTL0_CAPIEN1_Msk | ECAP_CTL0_CAPIEN2_Msk));
        CU_ASSERT((ECAPCh[i]->CTL0 & (ECAP_CTL0_CAPIEN1_Msk | ECAP_CTL0_CAPIEN2_Msk)) == (ECAP_CTL0_CAPIEN1_Msk | ECAP_CTL0_CAPIEN2_Msk));
        ECAP_DisableINT(ECAPCh[i], (ECAP_CTL0_CAPIEN1_Msk | ECAP_CTL0_CAPIEN2_Msk));
        CU_ASSERT((ECAPCh[i]->CTL0 & (ECAP_CTL0_CAPIEN1_Msk | ECAP_CTL0_CAPIEN2_Msk)) == 0);

        ECAP_EnableINT(ECAPCh[i], (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN1_Msk | ECAP_CTL0_CAPIEN2_Msk));
        CU_ASSERT((ECAPCh[i]->CTL0 & (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN1_Msk | ECAP_CTL0_CAPIEN2_Msk)) == (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN1_Msk | ECAP_CTL0_CAPIEN2_Msk));
        ECAP_DisableINT(ECAPCh[i], (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN1_Msk | ECAP_CTL0_CAPIEN2_Msk));
        CU_ASSERT((ECAPCh[i]->CTL0 & (ECAP_CTL0_CAPIEN0_Msk | ECAP_CTL0_CAPIEN1_Msk | ECAP_CTL0_CAPIEN2_Msk)) == 0);

        ECAP_DISABLE_CNT(ECAPCh[i]);
    }
}

CU_SuiteInfo ECAPSuites[] =
{
    { "ECAP Const Test", ECAP_Test_Init, ECAP_Test_Clean, NULL, NULL, ECAP_ConstTest },
    { "ECAP Macro Test", ECAP_Test_Init, ECAP_Test_Clean, NULL, NULL, ECAP_MacroTest },
    { "ECAP Func  Test", ECAP_Test_Init, ECAP_Test_Clean, NULL, NULL, ECAP_FuncTest },
    CU_SUITE_INFO_NULL
};

CU_TestInfo  ECAP_ConstTest[] =
{
    {"Input channel num", CONST_Input_Channel},
    {"Noise Filter DIV", CONST_Noise_Filter_DIV},
    {"Input souce", CONST_Input_Source},
    {"Input Cleared Events", CONST_Input_Cleared_Events},
    {"ECAP Function", CONST_ECAP_Func},
    {"ECAP Edge", CONST_ECAP_Edge},
    {"Reload trigger Source", CONST_Reload_Trig_Source},
    {"Timer Clock Divide", CONST_Timer_CLKDIV},
    {"Timer Clock Source", CONST_Timer_Source},
    CU_TEST_INFO_NULL
};

CU_TestInfo  ECAP_MacroTest[] =
{
    {"ECAP Enable/Disable", MACRO_ECAP_Enable_Disable},
    {"Noise Filter", MACRO_Noise_Filter},
    {"Input Channel enable", MACRO_Input_Channel},
    {"Input Channel source", MACRO_Input_Source},
    {"Input Channel INT", MACRO_Input_INT},
    {"Capture Counter Start/Stop", MACRO_CNT_STA_STO},
    {"Capture Counter Clear", MACRO_CNT_CLRRLD},
    {"Capture Input Mode", MACRO_Capture_Mode},

    {"Input Edge", MACRO_Input_edge},
    {"Input Reload", MACRO_Input_Reload},
    {"Input ClkSel", MACRO_Input_ClkSel},
    {"Input ClkSrc", MACRO_Input_ClkSrc},
    {"Set/Get CNT", MACRO_Set_CNT_Value},
    {"OVF & CMP flag", MACRO_OVF_CMP},
    {"INT & CLR flag & Hold Val", MACRO_INT_Hold},
    CU_TEST_INFO_NULL
};

CU_TestInfo  ECAP_FuncTest[] =
{
    {"ECAP_Open_Close", API_ECAP_Open_Close},
    {"ECAP_INT_Enable_Disable", API_ECAP_INT_EN},
    CU_TEST_INFO_NULL
};

/*** (C) COPYRIGHT 2023 Nuvoton Technology Corp. ***/
